[알트] 1단계 - HTTP 웹 서버 구현 미션 제출합니다.
woowacourse/jwp-was pull request #123
Opened 2020-09-15 19:54 UTC by KS-KIM

안녕하세요 휴! 처음뵙겠습니다🙇‍♂️

계속 어떻게 리팩토링할지 고민하다가 빠른 피드백을 받는 편이 낫겠다고 생각하여 리뷰 보냅니다.

스프링 내부구조에 관해 공부하면서 코드를 작성하다 보니 어렵기도 하고 재밌기도 하네요😊

따끔한 리뷰 부탁드립니다!!

2020-09-16 17:50 UTC, Hue9010 requested changes
의미 있는 수준으로 객체 분리를 잘해주셨네요 👍 
피드백 남겼는데 확인 해주세요! 궁금하신 사항은 코멘트나 DM으로 문의주세요.

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/RequestLine.java
> +    private final String protocol;
마지막은 version을 의미합니다.
https://developer.mozilla.org/ko/docs/Web/HTTP/Messages
> 마지막으로 ​​​​HTTP 버전이 들어갑니다. 메시지의 남은 구조를 결정하기 때문에, 응답 메시지에서 써야 할 HTTP 버전을 알려주는 역할을 합니다.

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/RequestHandler.java
> +            if (StaticResourceType.anyMatch(httpRequest.getRequestLine().getUri())) {
httpRequest의 requestLine이 직접 필요한 상황이 아니라면 외부로 드러내지 않고 httpRequest.getUri()를 통해서 uri를 알아오는건 어떨까요? 😏

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/RequestHandler.java
> +            if (StaticResourceType.anyMatch(httpRequest.getRequestLine().getUri())) {
ResourceType이 아니라 handlerMappings에 등록된 RequestMapping인지 확인해서 등록된 방법 또는 기본 방식으로 핸들링하는 건 어떨까요?

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/RequestHandler.java
> +                new FrontController().doService(httpRequest, httpResponse);
ResourceRequestHandler와 FrontController를 매번 new로 만들어줘야 할까요? 🤔 
바로 위에 말씀드린 것과 일부 합쳐서 처리한다면 `Map<RequestMapping, Handler> handlerMappings`를 통해 여기서 확인한다음 이미 map에 들어가 있는 handler를 받아다 사용하면 되지 않을까요?

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/HandlerNotFoundException.java
> +public class HandlerNotFoundException extends RuntimeException {
커스텀 Exception을 만드는 버릇 드는게 쉽지 않은데 적절한 Exception을 잘 만들어 주셨네요. 👏

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/FrontController.java
> +    private static final Map<RequestMapping, Handler> handlerMappings = new LinkedHashMap<>();
LinkedHashMap으로 만드신 이유가 있을까요? 🤔

2020-09-16 17:50 UTC, Hue9010 commented on README.md
> +### 🚀 1단계 - HTTP 웹 서버 구현
요구사항 정리를 잘해주셨네요. 👍 

한가지 얘기 나누고 싶은 부분이 있네요. 과제의 기본적인 요구사항과 별개로 플러스 알파로 DispatcherServlet이나 Controller를 사용할 때 하나의 컨트롤러에서도 다양한 path와 method를 처리 해주는 기능을 구현하고자 하신 것 같네요.

2단계 내용이 일부 포함된 상태로 1단계 요구 사항 외적인 내용도 있는 것 같은데 구현하시고 하셨던 방향을 알려주신다면 리뷰하는데 도움이 될 것 같아요. 😉 

어떻게 리팩토링 할지 고민되셨다고 하셨는데 무엇을 하려고 했는지의 목적을 명확히 하는게 어떻게 리펙토링을 할지의 방향성을 제시해줄 수 있답니다. 특히 학습단계에서는 모든걸 다 하려고 하기보다는 선택과 집중으로 이전에 사용하던 스프링 기능 중 구현 해보고 싶은 기능과 구현 수준을 조금은 명확히 정하고 해보는게 좋답니다. 안그러면 어디서 완료를 해서 멈춰야할지 판단을 하기 힘들답니다.
게다가 처음부터 완성버전을 보고 달리는 것도 좋지만 기초적인 기능에서 최종 단계로 단계 구분을 해둬서 최종 단계가 아니라도 기능상 문제가 없고, 중간에 멈추게 되어도 최종이 아니여서 그렇지 완성된 버전으로 멈출 수 있는 장점이 있답니다.

다만 이건 개인마다 학습 스타일도 다르니까 참고만 하시면 됩니다. 🙏

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes("\r\n");
개행 문자는 os마다 일부 차이가 존재합니다. 그래서 사용 os에 맞는 개행 문자를 제공하는 `System.lineSeparator()`가 존재하는데 이름에서도 느껴질테지만 검색을 해보기보다는 우선 메서드 내부를 따라가면 있는 설명만 읽어보셔도 충분하실 겁니다. 😉

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes("\r\n");
대체적으로 문자열들을 더하는 형태로 사용을 하고 계시는데 문자열 + 시 자동으로 최적화를 한다는걸 인지하고 사용하시는건지 궁금합니다. 알고서 사용하는 것과 모르고 있는건 다르다고 생각하거든요.ㅎㅎ
대략적인 내용은 아래 있습니다.
https://gist.github.com/benelog/b81b4434fb8f2220cd0e900be1634753
https://stackoverrun.com/ko/q/4044880

지금처럼 성능에 치명적인 문제를 일으킬 정도가 아닐때는 집착적으로 처리하실 필요도 없고 위 내용을 어느정도 인지하고 있으면 된다고 봅니다. 도리어 간단한 문자열 연산에 매번 StringBuilder/Buffer를 사용하면 코드가 장황해지는 편이죠.

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes("\r\n");
try-with-resources 👍

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/FrontController.java
> +    public Handler getHandler(final HttpRequest httpRequest) {
내부에서만 사용하는 메서드라면 private로! 😉

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/Uri.java
> +        return getPath().equals(path);
getPath()로 비교할 필요가 있을까요?
생성자에 존재하는 `Objects.requireNonNull(path, "uri path가 존재하지 않습니다.");`로 this.path가 null이라서 NPE가 발생할 일은 없겠네요. 👍

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/http/QueryParameters.java
> +public class QueryParameters {
세세한 부분까지 챙기시느라 고생하셨을 것 같네요. 대신 그만큼 꼼꼼하게 필요한 객체들을 잘 만들어 주셨네요. 👍 
고민을 많이하셨을 게 눈에 보이네요. 고생 많으셨어요. 👏

2020-09-16 17:50 UTC, Hue9010 commented on src/test/java/http/HttpRequestTest.java
> +package http;
이 위치에 말씀드릴 내용은 아니지만 test/java/coordinate 에 있는 테스트들은 과감(?)하게 지워버리는걸 추천드립니다. 사용하지 않고 사용 유무를 떠나서도 현재 프로젝트에 불필요한 코드를 지워보는 것도 좋은 경험이라고 생각합니다.

너무 과감히 지우는것도 어쩌다 실수를 유발하지만 지워도 되는걸 알지도 안지우고 놔둬도 되지 않을까 싶은 레거시 코드들이 프로젝트에 산적하게 되는 지름길이 됩니다. 😉

2020-09-16 17:50 UTC, Hue9010 commented on src/test/java/http/StaticResourceTypeTest.java
> +    void findByUri_NotMatchUri_ExceptionThrown() {
예외 케이스 테스트 💯 👍

2020-09-16 17:50 UTC, Hue9010 commented on src/main/java/webserver/FrontController.java
> +            logger.info(exception.getMessage());
logback.xml을 보면 debug 레벨부터 출력을 해주는데 info와 error만 사용해주셨네요.
약 두 달간 프로젝트를 진행하시면서 로그 레벨을 어떻게 구분해서 사용하셨고 효용성이 있으셨는지 궁금합니다. 로그에 대해서 얼마나 아시는지 확인하기 위한게 아니라 제가 알려드릴 부분이 없나 알기 위해서 가볍게 여쭙는거니까 부담 가지지 마시고요. 😉

2020-09-29 16:00 UTC, KS-KIM reviewed
피드백 반영이 늦어 죄송합니다 😭
리뷰 내용에 코멘트를 달아 두었으니 확인해 주셨으면 좋겠습니다!!
감사합니다🙇‍♂️

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes("\r\n");
유닉스 시스템, MS 윈도우에서 서로 다른 개행 문자를 사용해서 이를 응답객체 구성시 처리해줘야 하는군요! 좋은 팁 알아갑니다👍

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes("\r\n");
인지하고 있던 내용인데 한번 더 생각할 수 있게 해주셔서 감사합니다!
기존에 주어진 코드를 의심없이 사용했는데, 사소한 부분이라도 꼼꼼히 봐야겠네요 😊

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/http/RequestLine.java
> +    private final String protocol;
시작 라인 세 번째 요소가 `프로토콜/버전` 형태여서 `protocol`이라고 명명했는데 MDN 문서에서 `version`이라고 하는군요. 새로 알아갑니다 👍
생각해보니 HTTP 메시지의 시작 라인을 나타내니 프로토콜은 당연히 HTTP겠네요😅

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/http/Uri.java
> +        return getPath().equals(path);
불필요한 메서드 호출이네요. `this.path`와 비교하도록 수정했습니다!

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/webserver/FrontController.java
> +    private static final Map<RequestMapping, Handler> handlerMappings = new LinkedHashMap<>();
`HashMap`의 삽입 순서에 맞추어 비교할 필요가 없기에 `LinkedHashMap`을 사용할 필요가 없었네요. 불필요한 리소스 낭비가 발생할 것 같아요! 해당 부분 바로 수정했습니다.

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/webserver/FrontController.java
> +    public Handler getHandler(final HttpRequest httpRequest) {
불필요한 메서드 노출이었네요. 😅
바로 수정했습니다!

2020-09-29 16:00 UTC, KS-KIM commented on src/test/java/http/HttpRequestTest.java
> +package http;
프로젝트와 무관한데도 불구하고 방치하고 있었네요😅
불필요한 코드가 있다면 제가 작성한 코드가 아니더라도 바로바로 처리하는 습관을 들여야겠네요!!

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/webserver/RequestHandler.java
> +            if (StaticResourceType.anyMatch(httpRequest.getRequestLine().getUri())) {
resource, path를 통한 요청을 동일한 방식으로 처리하기 위해 `HandlerMapping` 인터페이스를 추가했습니다.
resource와 path는 현재 다른 방식으로 일치 여부를 식별하고 있기에 위 인터페이스를 구현하는 `ResourceHandlerMapping`과 `UrlHandlerMapping`를 만들어서 처리했습니다.

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/webserver/RequestHandler.java
> +                new FrontController().doService(httpRequest, httpResponse);
HandlerMapping 인터페이스를 추가하여 resource, path에 따른 처리를 변경함에 따라 `Map<RequestMapping, Handler> handlerMappings`을 `List< HandlerMapping> handlerMappings`로 변경했습니다.
또한, 매번 new 키워드 사용하는 부분을 제거하기 위해 상수처리 했습니다.

2020-09-29 16:00 UTC, KS-KIM commented on src/main/java/webserver/FrontController.java
> +            logger.info(exception.getMessage());
이번에 프로젝트를 진행하면서 아래와 같이 로그 레벨을 적용했습니다.

- `ERROR`: 직접 handling하지 않은 예외 출력시 사용. (ControllerAdvice에서 의도적으로 잡은 Exception을 제외한 나머지 Exception)
- `INFO`: 커스텀 예외 발생시 사용.
- `DEBUG`: 로컬 환경에서 테스트 중 예상치 못한 예외 발생시 사용. 커밋시에는 제거.

위의 로그 레벨 외에는 [이 글](https://blog.lulab.net/programmer/what-should-i-log-with-an-intention-method-and-level/)을 참고하여 별도로 사용하지 않았습니다.

`ERROR`레벨은 slack appender를 적용하여 배포 환경에서 발생한 경우 슬랙으로 알림 메시지를 받아보니 편리성을 느꼈습니다. 단, 예외 메시지가 어떤 상태인지 예측 가능한 경우에만 유효했습니다.
```
[2020-09-24 13:22:32:1377096][http-nio-8080-exec-8] ERROR k.t.c.c.ApiControllerAdvice - Request method 'POST' not supported
```
위와 같은 메시지가 오면 어디부터 손대야 할지 모르겠더라구요😭. 지금 보니 제가 위에서 작성한 예외 처리도 비슷하겠네요. 최소한 어떤 메서드가 호출되었고, path는 무엇인지 안다면 예외를 추적하기 훨씬 쉬울텐데, 메시지가 담고있는 정보가 한정적이다보니 접근하기 어려웠습니다. 실제로 저런 에러가 발생하면 저희가 직접 증상을 재현하는 수 밖에 없었어요.

어떤 방식으로 처리하면 더 좋은 로깅이 될 수 있을지 궁금하던 참인데 물어봐주셔서 감사합니다 🙇‍♂️
팀 프로젝트에서 사용한 로깅 전략에서 개선할 수 있는 부분이 있다면 피드백 부탁드립니다!!

2020-09-29 16:00 UTC, KS-KIM commented on README.md
> +### 🚀 1단계 - HTTP 웹 서버 구현
처음에는 `RequestHandler`에서 모든 요청에 대한 처리를 했었는데, 하나의 클래스가 너무 많은 일을 하고 있다는 생각이 들었습니다. spring 작동방식을 레퍼런스로 하여 책임을 분리하려고 했는데 굉장히 어설프게 따라하게 되었네요 😅

리팩토링의 주요 방향은 아래와 같았습니다.
- 어떤 요청이 들어왔는지 식별하는 로직을 분리한다. (HandlerMappings)
- 식별한 요청을 처리하는 로직을 분리한다. (Handler(Controller))

스프링처럼 Controller에서 사용하는 각종 애너테이션(e.g. `RequestMapping`)을 만들고 리플렉션을 사용하여 처리할까 생각했는데 지금 시점에서는 오버스펙인 것 같아서 멈췄습니다.

미션 2단계를 읽어보니 1단계에서는 Request, Response 객체 구현정도만 신경썼어도 됐을거라는 생각이 드네요 😅
다음 단계에서는 PR 요청시에 제가 중점적으로 노력을 기울인 부분에 대해 작성하여 피드백 주실 때 도움이 되도록 하겠습니다!!

2020-09-30 18:14 UTC, Hue9010 approved these changes
깔끔히 잘 구현해주셨네요. 👍 
고생하셨습니다. 이번 단계는 머지하도록 할게요.
간단한 피드백 남겼는데 혹시 문의 주신 내용 중 놓친 부분 있다면 말씀주세요. 😉

2020-09-30 18:14 UTC, Hue9010 commented on src/main/java/http/RequestLine.java
> +        this.version = Objects.requireNonNull(version, "protocol이 존재하지 않습니다.");
여기와 toString에 protocol 문구가 남아 있습니다.

2020-09-30 18:14 UTC, Hue9010 commented on src/main/java/http/HttpResponse.java
> +            dataOutputStream.writeBytes(System.lineSeparator());
Response 내에서 System.lineSepar의 사용이 많은데 별도 상수로 빼두는 선택지도 있을 것 같아요.

2020-09-30 18:14 UTC, Hue9010 commented on src/main/java/http/QueryParameters.java
> +        return Collections.unmodifiableMap(parameters);
👍

2020-09-30 18:14 UTC, Hue9010 commented on src/main/java/http/HttpResponse.java
> +    public void response200Header(String contentType, int lengthOfBodyContent) {
ResponseEntity를 참고해서 ok, noContent로 이름을 지어주면 어떨까요?

(빌더패턴을 적용한다던지의 따라해보시려고하진 마시고) 이쯤에서 예전부터 사용했던 ResponseEntity는 어떻게 Response를 만드는 기능을 제공하는지 보면 좋을것 같아요.
```java
        ResponseEntity.ok("body");
        ResponseEntity.ok().body("body");
        ResponseEntity.ok().header("headerName", "value").body("body");
        ResponseEntity.ok().build();
        
        ResponseEntity.created(URI.create("URI"));
        ResponseEntity.status(HttpStatus.CREATED).build();
        ResponseEntity.notFound().build();
```

ResponseEntity 덕분에 참 편했다는걸 깨달을 수 있죠. 😄

2020-09-30 18:14 UTC, Hue9010 commented on README.md
> +### 🚀 1단계 - HTTP 웹 서버 구현
고민하신 방향과는 조금 다르고, 학습 단계에서는 좋은 코드를 짜기 위해 집중하는게 맞다고 생각하지만 기간이 정해져 있는 학습이라면
https://twitter.com/nong____/status/1295374333716529157
전 위 글에 크게 공감하는 편이라 애노테이션을 추가하지 않은건 잘했다고 생각됩니다. 👍 빠르게 기간 내에 추가했다면 더 좋았을테지만 추가를 할지 말지에 대한 고민을 하시고 결정을 하는 과정을 거치신 게 더 좋은 경험이라고 생각해요.

다음 단계때 여유가 되면 추가해보는 것도 좋지만 아니라면 마지막 단계쯤에서 부가사항으로 적용해보시는 것도 좋을 것 같아요. tdd도 마찬가지인데 테스트 코드를 통해 마음편히(?) 리팩토링을 할 수 있다는 장점 외에도 우선 돌아가는 코드가 있다는 점에서도 안도감이 오지 않던가요?ㅎㅎ 그 측면에서 우선 요구사항부터 모두 끝낸다음 진행하는걸 추천해요. (이런 부분은 각자한테 맞는 학습방법도 있고 어느것에 가치를 두는지도 사람마다 다르기 때문에 적당히 필터링해서 참고하시는게 좋아요. 😉)

2020-09-30 18:14 UTC, Hue9010 commented on src/test/java/http/HttpRequestTest.java
> +package http;
[보이 스카웃 규칙](https://johngrib.github.io/wiki/Boy-Scout-Rule/)을 실제 캠핑장에서 쓰레기를 줍는다고 생각하면 내가 만든 쓰레기만 줍지는 않겠죠? 😏 
다만 실제 product에서는 이게 쓰레기인지 아닌지 판단이 안되는 경우들이 있을 수 있으니 최소한 자신의 쓰레기는 최대한 정리하는 좋다고 생각합니다.

나중에 다시 사용할 수도 있는 코드라고 생각될 때도 있는데 정말 다시 사용할 게 확실하게 정해져 있는 코드가 아니라면 전 git에 기록이 남아 있다는걸 믿고 지우는 편입니다. 게다가 경험 측면에서 그 코드 그대로 다시 재사용하는 경우가 드물기도 하고 그런 경우라면 보통 단기간 내에 다시 사용하는 경우라서 기존 git commit log를 통해 확인하는 것만으로도 충분한 편이더군요.

2020-09-30 18:14 UTC, Hue9010 commented on src/main/java/webserver/FrontController.java
> +            logger.info(exception.getMessage());
예시로 보여주신 `Request method 'POST' not supported`는 에러로 볼 사항이 아닌데
```java
    @ExceptionHandler(Exception.class)
    public ResponseEntity<String> handleException(final Exception exception) {
        log.error(exception.getMessage());

        return ResponseEntity
                .status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body("서버 내부적인 문제가 발생했습니다.");
    }
```
Exception e로 잡기때문에 ApiControllerAdvice에서 잡지 않는 예외들은 모두 500응답을 하게 되는 상황이네요. 심지어 예시처럼 클라가 지원하지 않는 메서드로 요청을 한 서버 측 문제가 아닌 클라쪽에서 잘못 요청한 상황에도 말이죠. try-catch도 마찬가지로 Exception 레벨로 잡으면 이런 문제가 발생 할 수 있습니다.

해결 방법은 HttpRequestMethodNotSupportedException에 대한 핸들링을 `HttpStatus.METHOD_NOT_ALLOWED`(405, "Method Not Allowed")로 응답하게 추가해주면 되겠네요. 간단하죠? 모든 걸 다 이렇게 추가할 순 없으니 사실 이건 말도 안되고 😋 ApiControllerAdvice에 ResponseEntityExceptionHandler를 상속해주면 기본적인 예외 처리를 해결됩니다.(검색해 보셔도 되지만 내부 구현도 생각보다 안 어렵습니다.😉) 우선적으로 `HttpRequestMethodNotSupportedException`처럼 `handleException`로 가지 말아야 할 것들은 제외 시켜주는게 좋을 것 같습니다. 모두가 알고 있는 "양치기 소년" 내용처럼 에러가 아닌 상황이 에러 알람으로 계속 오면 새로운 에러 알람이 와도 바로 보지 않게 됩니다.

---

메시지가 부족하다고 느끼셨다면 내용을 좀더 풍성하게 해주시면 됩니다. stacktrace까지 받을 수 있게 `log.error(exception.getMessage());`가 아니라 `log.error("Exception", exception);`로 stacktrace까지 출력하는건 어떨까요?

그리고 url, method 등 Request에 대한 정보를 아는건 생각보다 간단하답니다.
[Exception Handling in Spring MVC](https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc#controller-based-exception-handling) Controller Based Exception Handling 예시 코드
```java
  @ExceptionHandler(Exception.class)
  public ModelAndView handleError(HttpServletRequest req, Exception ex) {
    logger.error("Request: " + req.getRequestURL() + " raised " + ex);

    ModelAndView mav = new ModelAndView();
    mav.addObject("exception", ex);
    mav.addObject("url", req.getRequestURL());
    mav.setViewName("error");
    return mav;
  }
```
2~3 Line만 봐도 알겠죠? 😏 

---

> ERROR: 직접 handling하지 않은 예외 출력시 사용. (ControllerAdvice에서 의도적으로 잡은 Exception을 제외한 나머지 Exception)  

로그를 남길때가 주로 예외가 발생했을 때라서 예외와 로그를 묶어서 생각하신게 아닐까 싶어요. 예외와 로그는 서로 별개로 봐주시실 바랍니다. ERROR, WARN, INFO, ... 이름 그대로 `에러, 경고, 정보`성 출력을 남길 필요가 있을 때 사용하면 됩니다. 예외를 기준으로 잡는건 로그를 예외에 종속적인 존재로 인식한걸로 보입니다. (직접 핸들링하고 있지 않던 `Request method 'POST' not supported`가 에러 상황이 맞을까요?)

개발 단계에서 예외에 대한 로깅이 아니라 입력한 값이 제대로 넘어 오는지 값 확인을 위해서 System.out.println이 아니라 logger를 통해 확인해 보신적은 없나요?(테스트를 이용해서만 확인하는게 가장 좋지만 간혹 눈으로 확인해보고 싶은것들도 있죠? 😋 ) 이 상황은 예외와 관련이 있었을까요? sysout 대신 logger를 사용하는 이유가 무엇일까요? sysout은 단순한 출력 기능이고 logger는 예외와 관련된 출력 기능 일까요?
충분히 잘 활용하고 계셔서 logger를 예외와 너무 직접적으로 연관지어서 생각하지만 않으면 충분해 보입니다. 👍

2020-09-30 18:15 UTC, merged

2020-10-02 07:25 UTC, KS-KIM commented on src/main/java/http/HttpResponse.java
> +    public void response200Header(String contentType, int lengthOfBodyContent) {
빌더패턴 좋네요👍
`Response` 객체를 보면서 "`dataOutputStream.flush();`가 호출되지 않으면 클라이언트에 정상적으로 응답이 내려지지 않을 것 같다" 고 생각했는데, 빌더패턴을 활용하면 이와 같은 문제도 해결할 수 있을 것 같네요.

2020-10-02 07:25 UTC, KS-KIM commented on src/main/java/webserver/FrontController.java
> +            logger.info(exception.getMessage());
`ResponseEntityExceptionHandler`는 처음 알았네요! 말씀하신대로 공통 예외처리로 가지 말아야 할 메서드는 적절하게 제외 처리하는것을 고려해보겠습니다😊

그동안 ControllerAdvice에 대한 이해가 부족한 상태에서 사용법만 익히고 적용했던 것을 반성하게 되네요. 이번 기회를 통해 문서를 읽으면서 활용법을 더 익혀보겠습니다!!

---

말씀하신대로 기존에 로깅을 주로 예외 출력용으로만 사용해왔습니다. 환경별로 로그 대상을 설정할 수 있으니 조금 더 유연하게 적용할 수 있겠네요! 제가 설정한 부분이 아니라서 큰 관심을 가지지 않았었는데, 이번 기회를 통해 어떤 내용을 로그로 출력하는 것이 좋을지 한번 고민해봐야겠네요. 생각지도 못한 부분까지 섬세한 리뷰에 감사드립니다!!🙇‍♂️