[오구] 2단계 - HTTP 웹 서버 리펙토링 미션 제출합니다.
woowacourse/jwp-was pull request #138
Opened 2020-09-21 08:08 UTC by LTTTTTE

2020-09-23 04:52 UTC, Hue9010 requested changes
리뷰가 늦었습니다. 🙏 
몇가지 피드백을 남겼는데 확인해주세요! 
몇가지 변화가 필요해 보이는데 반영 이후 변화를 확인하는것도 괜찮지만 코멘트로 의견을 나누는 것도 좋을 것 같아요. 😉

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/WebServer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(16);
쓰레드풀 👍 
16으로 잡으신 이유가 있을까요?

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/request/RequestType.java
> +            return new RequestType(request.getMethod(), "");
RequestType의 path를 사용하는 곳이 없는 것 같은데 확인 부탁드려요.
사용하는 곳이라면 equals와 hashCode를 통해서 map에서 사용되겠네요. 
(지금 볼 내용은 아니지만 여유 되실 때 [Java HashMap은 어떻게 동작하는가?](https://d2.naver.com/helloworld/831311) 보시면 좋답니다.)
RequestType에서 path를 제거하면 HTTP Method 별로 하나씩 밖에는 등록하지 못하는 문제점이 있겠네요. 추가적으로 Request도 path와 method를 가지고 있는데 RequestType을 사용하면 어떨까요?

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/Status.java
> +    NOT_FOUND(404, "Not Found");
404 👍 
가능하다면 (기능 구현에만 목적을 두고 단순하게)500 에러도 추가해보면 좋을 것 같아요 😉

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/response/Response.java
> +    public void getResponse(Request request) {
메서드 이름만 봤을 때는 response를 get하는 메서드로 보입니다.

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/handler/RequestHandler.java
>      }
RequestHandler의 역할을 어디까지로 정하신걸까요? 응답에 대한 처리는 Response로 모두 옮기는게 좋지 않을까요?
마찬가지로 requestParser도 RequestHandler가 책임 져 줄 필요가 없을 것 같아요.

2020-09-23 04:52 UTC, Hue9010 commented on src/test/java/webserver/RequestTest.java
> +    public void requestTest_POST() throws Exception {
마지막에 있는 추가 요구사항이 구현이 안된 것 같네요
> HTTP에서 POST 방식으로 데이터를 전달할 때 body를 통한 데이터 전달뿐만 아니라 Query String을 활용한 데이터 전달도 지원해야 한다.

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/response/Response.java
> +    public void getResponse(Request request) {
네이밍이나 기능이 고민될 때는 이미 사용하던 것들에서 아이디어를 얻는 것도 좋아요.
ResponseEntity를 한번 참고해보면 어떨까요? (굳이 빌더까지 사용할 필요는 없을 것 같아요.)
> ResponseEntity.ok()

2020-09-23 04:52 UTC, Hue9010 commented on src/main/java/webserver/handler/Controller.java
> +                response.redirectTo("http://localhost:8080/index.html ");
redirectTo가 온전히 제 역할을 해주지 못하기때문에 위와같이 post와 같이 호출을 해줘야하는 것 같네요. redirectTo에서도 버전 정보를 세팅해주는건 어떨까요?

2020-09-23 04:52 UTC, Hue9010 commented on src/test/java/webserver/RequestTest.java
> +    public void requestTest_POST() throws Exception {
readme를 통해서 요구사항과 구현된 사항을 정리 해주는 것도 좋을 것 같아요.(단계 내에 있지 않는 사항이 있다면 그것도 포함해서!)

2020-09-23 05:17 UTC, LTTTTTE commented on src/main/java/webserver/WebServer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(16);
코어수 * 2 로 잡았습니다.

좀더 찾아보니 `전체 작업중 대기시간 비율`을 코어수에 곱해주는 공식을 사용하는거 같던데.
이것이 더 좋은 방법이겟죠?

2020-09-23 05:55 UTC, LTTTTTE commented on src/main/java/webserver/handler/Controller.java
> +                response.redirectTo("http://localhost:8080/index.html ");
redirectTo메소드가 온전하도록 수정하겠습니다.

2020-09-23 06:22 UTC, LTTTTTE commented on src/main/java/webserver/request/RequestType.java
> +            return new RequestType(request.getMethod(), "");
POST요청에서 url에따라 로직을 분리하기위해 사용되고있습니다.
RequestType객체를 사용해야할 곳에 사용하겠습니다.😅

2020-09-23 06:25 UTC, LTTTTTE commented on src/main/java/webserver/response/Response.java
> +    public void getResponse(Request request) {
좀더 고민해서 메서드명을 수정해보겠습니다😁

2020-09-23 06:31 UTC, LTTTTTE commented on src/main/java/webserver/handler/RequestHandler.java
>      }
Response객체를 생성한곳에서 Response객체를 참고해서 응답처리를 하는게 좋을거라 생각해서 이렇게 코딩했습니다.

저도 request파싱은 Request에서 해주는게 맞다고 생각합니다! 수정하겠습니다.😃

2020-09-23 06:32 UTC, LTTTTTE commented on src/test/java/webserver/RequestTest.java
> +    public void requestTest_POST() throws Exception {
역시 요구사항 정리가 없으니 빠트린 부분도 존재하군요.😢
요구사항 정리하고 누락된 부분도 추가하겠습니다.

2020-09-23 10:22 UTC, Hue9010 commented on src/main/java/webserver/WebServer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(16);
사실 알 수 없답니다. 🙄
[How to set an ideal thread pool size](https://engineering.zalando.com/posts/2019/04/how-to-set-an-ideal-thread-pool-size.html)를 보셨을 것 같은데 결론부에도 적혀 있다시피 물리나 수학 공식처럼 모든 곳에서 절대 진리로 사용될 수 있는 공식은 아니고 시작 점으로 사용 할 수 있는 공식입니다. 쓰레드 풀에 대한 튜닝이 필요한 경우라면 장비의 성능 뿐 아니라 db의 커넥션 풀 등의 다른 작업도 고려해서 결정을 해야합니다. 게다가 결정을 했다고 끝이 아니라 변경 후 모니터닝을 통해서(가능하다면 부하테스트로 먼저) 자신의 서비스에 맞는 값을 찾아가야 합니다.

핵심은 was 구현이라는 과제에 맞춰 톰캣이 쓰레드 풀을 사용한다는 점을 아는 것과 쓰레드 풀에 대해서 고민해보는 걸로 충분하다고 그 다음 플러스 알파는 본인의 흥미에 맞춰 찾아가면 된다고 생각됩니다. 😉 

여기서 질문! 톰캣의 기본 쓰레드 풀 사이즈는 몇일까요?

2020-09-24 07:57 UTC, LTTTTTE commented on src/main/java/webserver/WebServer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(16);
전혀 모르고있어서 검색을 했는데 최대 풀 사이즈가 200이군요
application.properties 설정값들중 자동완성에서 보니 tomcat 설정들도 여럿 많이 할수 있네요

2020-09-24 14:14 UTC, Hue9010 commented on src/main/java/webserver/WebServer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(16);
넵, 정확히는 default값이 200이죠. 나중에 쓰레드 풀을 만질 일이 있다면 톰캣보다는 [Commons DBCP 이해하기](https://d2.naver.com/helloworld/5102792) 이쪽을 먼저 깊게 봐야 할 확률이 높을 겁니다. 😉 
쉬운 내용도 아니고 지금 당장 깊게 볼 내용은 아니니 이런게 있구나 + 풀 관리가 단순 공식으로는 안되고 고려할 사항이 많구나정도로 보시면 됩니다.
핵심은 pool이 왜 필요한지와 개념을 아는 것이라고 생각됩니다.

2020-09-28 20:37 UTC, Hue9010 approved these changes
2단계도 고생 많으셨습니다! 👍 
간단한 피드백 남겼는데 확인하시고 다음 단계 때 반영하거나 스프링에선 어떻게 되어 있었을까 한번 쯤 생각해보면 좋을 것 같아요.

2020-09-28 20:37 UTC, Hue9010 commented on src/main/java/webserver/handler/Controller.java
> +                response.redirectTo(request, "http://localhost:8080/index.html ");
상대주소로도 가능합니다. 😉  [HTTP location](https://en.wikipedia.org/wiki/HTTP_location)

> An obsolete version of the HTTP 1.1 specifications (IETF RFC 2616) required a complete absolute URI for redirection. The IETF HTTP working group found that the most popular web browsers tolerate the passing of a relative URL and, consequently, the updated HTTP 1.1 specifications (IETF RFC 7231) relaxed the original constraint, allowing the use of relative URLs in Location headers.

2020-09-28 20:37 UTC, Hue9010 commented on src/main/java/webserver/handler/Controller.java
> +    }
간단한 퀴즈! 스프링처럼 직접 매핑하지 않고 동적으로 매핑되게 하려면 어떻게 해야 할까요? 한번 생각해보세요.

2020-09-28 20:37 UTC, Hue9010 commented on src/test/java/webserver/WebServerTest.java
> +//        }
사용하지 않는 코드는 그때그때 제거해주세요!

2020-09-28 20:37 UTC, Hue9010 commented on src/main/java/webserver/handler/RequestHandler.java
> +        }
로그만 찍지 말고 500 응답을 해줄 수 있을 것 같아요.

스프링을 사용할 때를 생각해보면 예외를 발생시키만 하고 예외 발생에 대한 처리를 안하면(핸들러 작성 포함) 500 에러를 응답 받았을 겁니다. 어딘가에서 예외 발생시 500으로 응답하는 부분이 있었겠죠? 그게 어디인지 찾는건 크게 의미가 없고 스프링처럼 예상하지 못한 응답에 대해선 500을 발생시켜주면 좋을 것 같아요. 😄

2020-09-30 06:38 UTC, merged