[디디] 2단계 - HTTP 웹 서버 리펙토링 미션 제출합니다.
woowacourse/jwp-was pull request #139
Opened 2020-09-21 09:28 UTC by fucct

안녕하세요 화투! 지난번 피드백 감사합니다! 많이 배웠어요!

하나 궁금했던 점이 Servlet 인터페이스를 한번 구현해보라고 하셨는데, 
Servlet이 해주는 역할이 init - service - destroy 라고 하더라고요.
따라서 service가 각 컨트롤러 메서드가 되는 방식으로 동작하는 건가요? 해당 Method에 따라 doGet과 doPost를 선택하는 식으로 동작하면 되나요? 정확하게 제가 맞게 생각한건지 잘모르겠네요..

전체적으로 이상한 부분있으면 최대한 말씀해주세요! 추가로 공부해야될 내용있다면 말씀해주시면 감사하겠습니다..!

2020-09-27 10:55 UTC, phs1116 requested changes
안녕하세요, 디디! 
이번주에 일이 많아서 리뷰가 많이 늦었네요. 죄송해요.
질문주신 부분이랑 몇가지 피드백 추가했는데 참고 한번 부탁드려요!

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/utils/FileIoUtils.java
> +            .orElseGet(() -> getPath(NOT_FOUND_PAGE));
NOT_FOUND_PAGE에 대해서는 파일 경로를 내려주는게 아닌, 예외로 처리하고 404 status 코드와 함께 관리해줘도 좋을 것 같네요.
이 경우 리소스가 없을 때 404 status code와 함께 관리가 어려우니까요.

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/response/ModelAndView.java
> +        ResponseBody responseBody = new ResponseBody(body);
ResponseHeader에 대해서는 HttpResposne를 통해서 관리해도 되지 않을까 싶어요.
모델 / 뷰에 대한 정보랑은 거리가 있어보여요.

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/response/ModelAndView.java
> +    }
viewName에 대한 내용이 responseBody로 만들어서 내려가는거 아닌가요?
만약 템플릿 엔진을 사용해서 모델이 viewName에 해당하는 템플릿에 반영이 된다면
ResponseBody보다는 이 객체의 이름에 맞게 Model이 더 적합한 것 같아요.

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/response/ServletResponse.java
> +    private final View view;
ServletResponse은 말 그대로 http response의 값이니. View 자체보다는 View를 통해 생성된 Response Body 데이터를 들고있는게 맞지 않을까요?

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/request/QueryParams.java
> +        if (!path.contains("?")) {
다른건 다 상수로 빼셨는데 깜빡 하신 듯 하네요 ㅋㅋ

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/messageconverter/DefaultHttpMessageConverter.java
> +                    logger.info(e.getMessage(), e);
info보단 에러나 워닝 로그가 더 적합하지 않을까요?

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/DispatcherServlet.java
> +            }
ExcptionHandler와 같은 이름으로 추상화해줘도 좋을 것 같네요.
IOException 외의 다른 예외 상황(NotFound등)에 대한 처리도 그에 맞춰 관리해줘도 좋을 것 같아요.

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/response/ModelAndView.java
> +public class ModelAndView {
ModelAndView가 그냥 Response와 거의 같은 책임을 가지고 있어요.
이름 그대로 모델과 뷰에 대한 책임만 가져보면 어떨까요?

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/controller/StaticResourceHandlers.java
> +        return ModelAndView.of(StatusCode.OK, headers, attributes, path);
resouce에 대해서는 ModelAndView가 꼭 필요할까 생각도 드네요 :)

2020-09-27 10:55 UTC, phs1116 commented on src/main/java/webserver/handlermapping/DefaultHandlerMapping.java
> +                .anyMatch(strategy -> strategy.isSupport(request, method.getAnnotation(RequestMapping.class))))
서블릿은 doGet, doPost등에 대한 메소드를 말씀드렸던것이었어요.
ServletRequest, ServletResponse 두 객체를 서블릿 객체에 전달하여 요청에 대한 값을 가져오고 응답값을 다루도록 되어있거든요.
현재 ServletResponse에 대한 역할을 ModelAndView가 다 가지고있는데, ModelAndView에는 모델과 뷰에 대한 책임만 가지도록 하고, 응답에 대해서는 별도로 처리를 해주는게 좋을 것 같아요.

2020-09-27 11:07 UTC, fucct commented on src/main/java/webserver/request/QueryParams.java
> +        if (!path.contains("?")) {
헉..!

2020-10-19 08:26 UTC, fucct commented on src/main/java/utils/FileIoUtils.java
> +            .orElseGet(() -> getPath(NOT_FOUND_PAGE));
Exception handler에서 처리해주도록 수정했습니다

2020-10-19 08:26 UTC, fucct commented on src/main/java/webserver/response/ModelAndView.java
> +        ResponseBody responseBody = new ResponseBody(body);
ModelAndView와 ServletResponse를 분리하였습니다!

2020-10-19 08:27 UTC, fucct commented on src/main/java/webserver/response/ModelAndView.java
> +    }
우선은 View를 ModelAndView에서 가지도록 하였습니다.

2020-10-19 08:27 UTC, fucct commented on src/main/java/webserver/messageconverter/DefaultHttpMessageConverter.java
> +                    logger.info(e.getMessage(), e);
수정했습니다!

2020-10-19 08:28 UTC, fucct commented on src/main/java/webserver/DispatcherServlet.java
> +            }
우선 ExceptionHandler에서 예외처리를 담당하도록 구현하긴 했는데, Enum을 통해 예상되는 예외에 대한 응답을 미리 생성해놓고 반환해주는 식으로 구현했습니다. 혹시 try/catch 문이 증식하는 문제를 해결할 수 있는 좋은 방법은 없을 지 조언 부탁드립니다 😭

2020-10-19 08:30 UTC, fucct commented on src/main/java/webserver/controller/StaticResourceHandlers.java
> +        return ModelAndView.of(StatusCode.OK, headers, attributes, path);
해당부분도 고민해봤는데, ModelAndView 대신 View를 리턴하려고 했더니 너무 많은 부분을 수정해야 하더라구요. Controller의 리턴값을 다양하게 갖는 방법 외에 다른 방법도 있을까요?

2020-10-24 13:26 UTC, phs1116 requested changes
안녕하세요 디디!
코드가 많이 바뀌었네요. :)
여러가지로 많이 고민하신게 보여요.
몇가지 피드백 더 추가했는데 참고부탁드릴게요!

2020-10-24 13:26 UTC, phs1116 commented on src/main/java/webserver/DispatcherServlet.java
> +            }
음 enum이 아니더라도 예외 자체를 상속을 통해서 처리할수 있을 것 같아요. :)

2020-10-24 13:26 UTC, phs1116 commented on src/main/java/webserver/DispatcherServlet.java
> +        } finally {
커스텀한 예외에서 직접 ExceptionHandler에 필요한 코드를 가지고 있도록 하고 이를 통해 예외 처리를 하도록 하고,
그 외의 경우에 대해서는 다 500으로 처리하면 깔끔하지 않을까요?
try-catch문의 증가도 없을꺼구요.

2020-10-24 13:26 UTC, phs1116 commented on src/main/java/webserver/controller/StaticResourceHandlers.java
> +}
정적파일의 처리는 Contoller랑 다른 레이어이지 않을까 싶어서 말씀드렸던 것이었어요. :)
디스패쳐 서블릿내에서 다른 컨트롤러와 다르게 풀어낼 수 있을 것 같아서요.
실제 톰캣을 생각해보면 정적 자원에 대해서 컨트롤러로 사용하지 않지 않나요? :)

2020-10-24 13:26 UTC, phs1116 commented on src/main/java/webserver/response/View.java
> +    private final boolean isRedirect;
redirect 등에 대해서 다형성으로 풀었어도 괜찮았을 것 같네요. :)

2020-10-24 13:26 UTC, phs1116 commented on src/main/java/webserver/response/View.java
> +    public View(byte[] view, String viewName) {
생성자로 인해서 redirect지만 그렇게 처리되지 않을 케이스가 발생할 수도 있겠네요.

2020-11-03 12:09 UTC, fucct commented on src/main/java/webserver/controller/StaticResourceHandlers.java
> +}
이해했습니다. ResourceHandler를 만들고 해당 객체에서 먼저 정적자원인지를 확인후 response를 만들고 정적자원이 아닌 경우 핸들러 매핑을 타도록 수정했습니다!

2020-11-03 12:11 UTC, fucct commented on src/main/java/webserver/DispatcherServlet.java
> +        } finally {
감사합니다. 이해되었습니다. 한가지 궁금한점은 Exception에서 해당 예외상황에 맞는 Response를 만들어서 반환하는 메서드를 갖도록 구현했는데 이게 혹시 어색하게 느껴질 수도 있을것 같다는 생각이 들더라고요. 이렇게 구현하는게 맞을까요..?

2020-11-03 12:12 UTC, fucct commented on src/main/java/webserver/response/View.java
> +    private final boolean isRedirect;
말씀주신것처럼 다형성으로 구현을 했습니다. DefaultView와 RedirectView로 나누어서 구현했습니다.

2020-11-03 12:12 UTC, fucct commented on src/main/java/webserver/response/View.java
> +    public View(byte[] view, String viewName) {
예외 처리를 해놓았습니다!

2020-11-15 14:34 UTC, phs1116 requested changes
안녕하세요, 디디!
구현 잘해주셨어요, 
질문주신 사항에 대해서
이부분만 리팩토링 해보면 좋을 것 같아서 하나만 더 피드백 달았습니다. :)

2020-11-15 14:34 UTC, phs1116 commented on src/main/java/webserver/DispatcherServlet.java
> +        } finally {
서블릿 리스폰스를 반환할 필요는 없고, StatusCode를 반환하도록만 해도 충분하지 않았을까 싶네요. :)

2020-11-15 14:34 UTC, phs1116 commented on src/main/java/exception/InvalidRequestHeaderException.java
> +            ModelAndView.of("static/notFound.html"));
서블릿 리스폰스 자체를 예외가 처리하는건 너무 많은 역할을 가져가는듯해 부자연스러워요, 뷰 정보 또한이요.
스테이터스 코드 정도만 예외에서 처리할수있도록 해도 괜찮을 것 같아요.

2020-11-21 16:01 UTC, phs1116 approved these changes
안녕하세요, 디디!
수정 깔끔하게 잘해주셨어요.
2단계 머지할게요. 수고 많으셨어요! :)

2020-11-21 16:01 UTC, phs1116 commented on src/main/java/exception/ViewNotFoundException.java
> +    public StatusCode getStatusCode() {
@Override를 빠트리셨네요 ㅎㅎ

2020-11-21 16:01 UTC, merged