[작은곰] 1단계 - HTTP 웹 서버 구현 미션 제출합니다.
woowacourse/jwp-was pull request #145
Opened 2020-09-23 05:03 UTC by KimGyeong

안녕하세요 리뷰 요청이 늦었습니다

구현 후 리팩토링 욕심이 계속 생겨서 시도하다가 리뷰를 받은 후에 하는 것이 낫다고 판단하였습니다.

현재 Request에 대한 리팩토링만 진행된 상황입니다.

부족하지만 잘 부탁드립니다 :)

2020-09-23 15:38 UTC, Hue9010 requested changes
간단한 피드백 몇가지만 남겼는데 확인해주세요. 궁금한 사항은 코멘트나 슬랙 DM으로 주시면 됩니다. 🙏

2020-09-23 15:38 UTC, Hue9010 commented on README.md
> +## 요구사항
커밋 메시지를 보니 요구사항1, 2, 3, 4, 5로 표현해 주셨는데 테크코스에 있는 요구사항 순서로 보이네요. 
요구사항 X로 함축적으로 표현을 했다면 요구사항의 순서도 같이 표시되어 있으면 좋을 것 같아요. 그것보다는 가능하다면 어떤 작업을 했는지 커밋 메시지만 보고 알 수 있게 작성해주시는게 더 좋답니다. (작업이 복잡해질 땐 변수명 짓기 못지 않게 어려운 작업...😋)

요구사항과 실제 완료된 사항은 사실 별개이기 때문에 [ ], [X]를 활용해서 진행사항도 표현해주면 좋을 것 같아요.

2020-09-23 15:38 UTC, Hue9010 commented on src/main/java/webserver/RequestHandler.java
> +			dos.writeBytes("HTTP/1.1 200 OK \r\n");
OS마다 개행 문자가 다르기 때문에 System.lineSeparator()가 존재합니다. 메서드 명만 봐도 무엇을 하는지 알 수 있지만 검색보다는 우선 메서드 상세 구현을 들어가면 깔끔하게 설명이 되어 있답니다. 😉

2020-09-23 15:38 UTC, Hue9010 commented on src/main/java/web/HttpRequest.java
> +			parameter = RequestPathUtil.extractParameters(body);
**RequestPathUtil**.extractParameters()
path가 아닌 body도 사용이 가능한걸로 보이는데 RequestPathUtil이라는 이름이 유효할 지 고민해 볼 수 있을 것 같네요.
테스트도 get일때만 있는데 post일 때도 필요하지 않을까요? 😉

2020-09-23 15:38 UTC, Hue9010 commented on src/main/java/web/HttpRequest.java
> +		String path = requestHeader[1];
HttpMethod와 Path에 대한 코드들이 HttpRequest에 꽤 많은 비중을 차지하는 것 같은데 RequestLine을 만드는건 어떨까요?
우선 한번에 너무 많은걸 고려하면 복잡해지니 버전은 1.1만 사용한다고 가정하고 지금 형태를 유지하도록 하죠.
헤더와 파라미터도 객체로 만드는걸 고려할 수 있을 것 같아요.(상수들도 각자의 위치로 이동하겠죠? 😉 )

2020-09-23 15:38 UTC, Hue9010 commented on src/main/java/webserver/RequestHandler.java
> +			request.getParameter("name"), request.getParameter("email"));
`request.getParameters.get(key)`로 불필요한 사항을 외부에 드러내지 않고 잘해 주셨네요. 👍

2020-09-23 15:52 UTC, Hue9010 commented
몇가지 고민을 했는데 다음 스텝이 리팩토링에 중심을 둔 내용이라 많은 부분은 다음 스텝에서 개선하는게 좋을 것 같다고 판단했습니다.

학습을 할 때는 좀 다르게 봐야하는 점이 있지만 개발을 할 때 생각해보면 좋은 점이 있는 링크 남깁니다.
https://twitter.com/nong____/status/1295374333716529157

무리한 일정을 잡진 말고 스스로가 언제까지 할지 일정을 정한 다음 진행하면 그에 따른 트레이드 오프가 발생 할 수 있을텐데 그런 상황을 겪어 보는것도 좋은 경험이 될 것 같아요. 사실 어느게 필요 없다가 아니라 선택과 집중의 영역이죠. 😉

2020-10-21 11:41 UTC, KimGyeong commented
너무나도 늦은 피드백 요청에 죄송합니다 😥
남겨주신 글은 읽어보았습니다. 너무나도 많은 도움을 얻은 것 같습니다.
잠깐동안에는 약간의 방황이라고 해야할까요. 제 마음을 바로잡지 못했던 것 같습니다.
여러가지 힘든 것들이 겹쳤다고 핑계를 댈 것 같네요...
남겨주신 피드백을 바탕으로 리팩토링을 해보았습니다.
남은 미션들 모두 잘 부탁드립니다. 🤗

2020-10-22 18:49 UTC, Hue9010 approved these changes
깔끔히 잘 구현해주셨네요! 👍 👍 
이번 단계는 여기서 머지할게요. 고생 많으셨습니다! 😉

2020-10-22 18:49 UTC, Hue9010 commented on src/main/java/web/Header.java
> +		while (!"".equals(line)) {
```java
!StringUtils.isEmpty(line)
```
취향이기 때문에 참고만 해주세요. 😉

2020-10-22 19:22 UTC, Hue9010 commented
원래 무슨 일이든 막바지에 이뤘을 때가 심적으로나 몸적으로나 가장 힘든 시기에요. 게다가 가을이잖아요!!!(요즘 봄/가을이 존재하는진 모르겠지만...😭)
자기자신을 잘 아는 것도 중요하다고 생각해요. 방황 혹은 번아웃 같은 상황이 왔을 때 어떤 상태가 되는지, 그 때는 어떤 방법으로 푸는게 효과적인지 등등 스스로에 대해서 알아 갈 시간을 가진 시간이라고 생각해요. 당장은 그 시간이 아깝게 소비한 시간이라고 생각될 수도 있지만 길게 봤을 땐(늙은이 처럼 얘기해보자면...) 이번 경험으로 다음에 같은 상황이 왔을 때는 번아웃이 오기 직전에 대비를 하거나 이번 보다 빠르게 회복 할 수 있을 거에요. 그러기 위해서는 마무리를 잘하는게 중요하다고 생각해요. 힘들 때 푹쉬라고 하고 싶지만 마무리 단계, 혹은 시작 단계로서 조금만 더 힘내서 잘 풀리시길 바랄게요.

사실 과제자체의 마무리보다는 올 한해를 가득 채운 이 과정의 마무리를 잘 하는게 중요하다고 생각해요. 여기서의 과정은 단순 우테코 과정자체만을 의미하기보다는 작은곰이 우테코를 통해 가져가고했던 것들을 잘 챙기는 마무리를 잘 하시길 바랄게요. 🙏 

혹여나 처음 계획했던 것에 비해 많이 부족하다고 느껴도 너무 상심하지 마세요. 우리모두 계획대로 다 이루는 사람이였으면 서울대 다녔어요.😏 (혹시 서울대 출신은 아니시죠? 🤣)

2020-10-22 19:22 UTC, merged