[티거] 2단계 - HTTP 웹 서버 구현 미션 제출합니다.
woowacourse/jwp-was pull request #155
Opened 2020-10-07 07:08 UTC by kimevanjunseok

잘 부탁드립니다!!!

2020-10-10 16:42 UTC, jihan805 requested changes
안녕하세요! 깔끔하게 리팩토링 잘하셨습니다 💯 
간단한 코멘트 남겼으니 확인해주세요 :)

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/controller/AbstractController.java
> +    private static final String POST = "POST";
추상 클래스 👍 
Http Method를 나타낼 수 있는 enum 클래스를 구현해보면 어떨까요?

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/controller/AbstractController.java
> +        throw new RuntimeException();
지원하지 않는 방식의 경우 지원하지 않는다는 에러를 던져주면 더 좋을 것 같아요 !!

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/controller/UserController.java
> +    private static final String CONTENT_LENGTH = "Content-Length";
CONTENT_LENGTH 와같이 응답의 헤더로 사용되는 상수는 별도의 클래스로 분리하여 관리하면 어떨까요?

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/controller/type/ControllerType.java
> +        return "/user/create".equals(url);
1. /user/create -> 상수
2. 만약 LoginController가 추가된다면, private static boolean~ 형태의 메서드가 추가되는걸까요? 맞다면, path 가 여러개 추가되면 해당 클래스가 너무 커질 것 같아요!

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/http/request/HttpRequestUrl.java
> +        return new HashMap<>();
2인경우만 if {}안의 로직을 수행한다면, 2가 아닌 경우 선 return하도록 조건을 변경해도 좋을 것 같아요 !

2020-10-10 16:42 UTC, jihan805 commented on src/main/java/webserver/WebServer.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(100);
스레드의 수를 상수로 선언해도 좋을 것 같아요!

2020-10-10 16:42 UTC, jihan805 commented on src/test/java/http/request/HttpHttpRequestHeaderTest.java
> +public class HttpHttpRequestHeaderTest {
src/test/resources 를 비롯하여 전체적으로 테스트를 꼼꼼하게 잘 작성해주셨어요 💯 
"2단계 - 추가 요구사항이나 변경이 발생하는 경우" 에 대한 테스트는 빠져있는 것 같아 확인부탁드릴게요 :) 

```
POST /user/create?id=1 HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 46
Content-Type: application/x-www-form-urlencoded
Accept: */*

userId=javajigi&password=password&name=JaeSung
```
추가로 혹시 요 테스트 클래스 네임에 HttpHttp~로 작성한 특별한 이유가 있을까요!? (궁금함입니다!!!)

2020-10-10 18:39 UTC, kimevanjunseok commented on src/test/java/http/request/HttpHttpRequestHeaderTest.java
> +public class HttpHttpRequestHeaderTest {
`HttpHttp~`한 이유는 실수입니다!! 하나만 있는 것이 맞습니다. 그리고 해당 추가 요구사항의 대한 테스트도 추가하겠습니다!!

2020-10-21 10:54 UTC, jihan805 approved these changes
안녕하세요~피드백 반영잘하셨습니다 👍 
다음단계 진행해주세요 !

2020-10-21 10:54 UTC, jihan805 commented on src/main/java/controller/AbstractController.java
> +        throw new NotSupportedMethodException("지원하지 않는 Method 입니다.");
👍

2020-10-21 10:54 UTC, jihan805 commented on src/main/java/controller/TemplateController.java
> +    void doPost(HttpRequest httpRequest, HttpResponse httpResponse) {}
지원하지 않는 메서드는 override하지 않도록 구현하는 방법도 있을것 같아요!

2020-10-21 10:54 UTC, jihan805 commented on src/test/java/http/request/HttpRequestTest.java
> +        String testDirectory = "./src/test/resources/";
setUp에서 모든 케이스를 준비해두고, getMethod, getUrl의등의 테스트로 나누는 것보다 
"Http_GET.txt" 각각에 대한 테스트케이스를 만드는것이 조금 더 정확한 테스트를 작성할 수 있을 것 같아요!

2020-10-21 10:54 UTC, jihan805 commented on src/test/java/type/method/MethodTypeTest.java
> +    void find(final String method, final MethodType expect) {
메서드명을 조금 더 구체적으로 작성해주어도 좋을 것 같아요!

2020-10-21 10:54 UTC, merged