[카프카] 2단계 - HTTP 웹 서버 구현 미션 제출합니다.
woowacourse/jwp-was pull request #160
Opened 2020-10-13 10:14 UTC by include42

안녕하세요. 카프카입니다.
리뷰 요청이 많이 늦어지게 되어 죄송한 마음입니다.
부족한 코드인 만큼, 개선할 부분을 짚어주신다면
성장하는 계기로 삼아보겠습니다.

감사합니다.

2020-10-17 03:36 UTC, jihan805 requested changes
안녕하세요~! 2단계 미션 깔끔하게 잘 하셨습니다 👍 
간단한 코멘트 남겨두었습니다!

2020-10-17 03:36 UTC, jihan805 commented on src/test/resources/request/HTTP_POST_2.txt
> +POST /user/create?id=1 HTTP/1.1
추가 요구사항에 대한 테스트 케이스 작성 👍

2020-10-17 03:36 UTC, jihan805 commented on src/main/java/controller/AbstractController.java
> +        throw new RequestMethodNotSupportedException("POST");
지원하지 않는 경우에 대한 예외처리 👍 
"GET", "POST"는  상수를 사용해도 좋을 것 같아요 !

2020-10-17 03:36 UTC, jihan805 commented on src/main/java/web/response/HttpResponse.java
> +            }
dateoutputstream에 write 하는 역할은 HttpResponse의 역할로 가지고 있어도 좋을 것 같아요!

2020-10-17 03:36 UTC, jihan805 commented on src/main/java/web/response/Status.java
> +public enum Status {
어떤 status인지 클래스 이름을 통해 나타내주면 어떨까요?

2020-10-17 03:36 UTC, jihan805 commented on src/main/java/webserver/RequestHandler.java
> +            controller.service(httpRequest, httpResponse);
리팩토링 👍

2020-10-20 11:10 UTC, include42 commented
피드백 감사합니다!! 조금 늦었지만 오늘 반영해서 다시 리뷰 요청을 드립니다.
어려운 듯 하면서도...진행할수록 많이 배우는 미션이네요. 다음은 어떨지 더욱 기대됩니다 👍

2020-10-24 06:30 UTC, jihan805 approved these changes
안녕하세요~! 2단계 리팩토링 깔끔하게 잘 진행하셨어요 👍 
다음 단계 진행해주세요!

2020-10-24 06:30 UTC, merged