[빙봉] 3단계 - HTTP 웹 서버 구현 미션 제출합니다.
woowacourse/jwp-was pull request #163
Opened 2020-10-19 14:11 UTC by aegis1920

3단계 미션 제출합니다!
많은 피드백 부탁드립니닷 :)
리뷰어님 항상 감사합니다! 👍 👍

2020-10-21 15:03 UTC, kingbbode requested changes
안녕하세요 :)
잘 구현해주셨네요!
아쉬운 부분이 남아 코멘트 작성해두었습니다.
확인 부탁드려요.

2020-10-21 15:03 UTC, kingbbode commented on src/main/java/utils/HandlebarUtils.java
> +        Template template = handlebars.compile(location);
생성된 `Template` 가 `thread safe` 한지 궁금하네요! `thread safe` 하다면 매번 생성할 필요가 없을 것 같아요 :)

2020-10-21 15:03 UTC, kingbbode commented on src/main/java/webserver/controller/ListUserController.java
> +        Optional<Cookie> loginedCookie = cookies.getCookie(LOGIN_COOKIE_NAME);
`map` 과 `orElse` 를 사용하면 쉽게 로그인 여부를 꺼내올 수 있을 것 같네요 :)
`Optional` 의 `isPresent`. `get` 을 사용한다면 안티패턴을 사용하고 있는 것이 아닌지 의심해보시길 바래요!

관련 좋은 아티클 첨부합니다 :)
http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2020-10-21 15:03 UTC, kingbbode commented on src/main/java/webserver/controller/ListUserController.java
> +        Optional<Cookie> loginedCookie = cookies.getCookie(LOGIN_COOKIE_NAME);
로그인을 쿠키로 구현하셨네요 :) 마지막 요구사항인 세션도 구현하셨구요.
쿠키와 세션의 차이는 무엇일까요?
로그인 정보를 어디에서 관리하는 것이 더 안전할까요?
고민을 해보셨으면 합니다 :)

2020-11-06 08:42 UTC, aegis1920 commented on src/main/java/utils/HandlebarUtils.java
> +        Template template = handlebars.compile(location);
그러네요! ClassPathTemplateLoader 객체와 Handlebars 객체를 정적으로 뺐습니다 :) 조언 감사합니다!

2020-11-09 05:16 UTC, aegis1920 commented on src/main/java/utils/HandlebarUtils.java
> +        Template template = handlebars.compile(location);
그러네요! ClassPathTemplateLoader 객체와 Handlebars 객체를 정적으로 뺐습니다 :) 조언 감사합니다!

2020-11-09 05:30 UTC, aegis1920 commented on src/main/java/webserver/controller/ListUserController.java
> +        Optional<Cookie> loginedCookie = cookies.getCookie(LOGIN_COOKIE_NAME);
가장 큰 차이는 정보의 저장 위치가 다른 것이라고 생각하며 그로 인해 파생되는 보안 문제, 성능 문제가 있습니다. 

로그인 정보는 개개인의 정보가 담겨있으므로 매우 중요합니다. 세션에 저장하는 것이 더 안전하다고 생각해 세션 방식으로 수정했습니다 :)

다만 세션에 유저의 정보 전체(User)를 저장하도록 구현했는데 현업에서도 유저의 정보 전체를 저장하도록 구현하는지 궁금합니다. 스프링은 메모리 세션을 제공한다고 하는데 세션에는 보통 어떤 것들이 들어가나요?

2020-11-10 12:02 UTC, kingbbode approved these changes
잘 반영해주셨네요.
이만 머지하겠습니다 :)
작성한 코멘트도 확인 부탁드려요!

2020-11-10 12:02 UTC, kingbbode commented on src/main/java/webserver/request/HttpRequest.java
> +            .orElse(HttpSessions.createHttpSession(UUID.randomUUID().toString()));
`orElse` 사용으로 메서드가 호출될 때 마다 `createHttpSession` 이 생성되게 됩니다.
`orElseGet` 을 사용하여 lazy-evalution 코드를 작성해야 합니다 :)

2020-11-10 12:02 UTC, merged

2020-11-10 12:06 UTC, kingbbode commented
스프링의 세션은 관계형 데이터베이스, 레디스, 메모리 등 다양한 구현체를 지원합니다.

세션에 저장되는 데이터는 사용자를 식별을 위해 필요한 데이터가 들어가게 될 것이고 시스템마다 다르게 들어갑니다.

다만 세션에 들어갈 데이터가 원본 데이터와의 정합성을 따르거나, 정합성에 영향을 주지 않도록 관리 및 작성합니다.