[웹서버] 르윈 미션 제출합니다
woowacourse/jwp-was pull request #17
Opened 2019-09-20 09:26 UTC by yuyu154

안녕하세요.
이번 미션에서는 

1. 객체간의 협력 관계 
2. 객체의 역할 분리
3. 테스트가 힘든 부분을 분리
하는 부분에서 많은 고민을 했습니다. 

감사합니다! 많은 조언 부탁드립니다!

2019-09-21 06:01 UTC, ssosso requested changes
안녕하세요, 르윈~ 쏘쏘입니다:)
몇 가지 피드백 남기오니 확인 부탁드립니다.
추가로 직접 화면을 띄워 확인하지 않고도 테스트로 요청에 대한 알맞은 페이지가 반환되는지 테스트할 수 있다면 좋을 것 같아요~

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/Response.java
> +    public void setStatusCode(int statusCode) {
전반적으로 setter를 사용하지 않도록 변경할 수 있을까요~?

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/ResponseHeader.java
> +        this.type = String.format("text/%s", type);
image나 font는 text/*로 해결되지 않을텐데 어떻게 하는 것이 좋을까요~?

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/ResponseHeader.java
> +    public void setType(String type) {
setter지양

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/ResponseHeader.java
> +    private static final int OK_STATUS_CODE = 200;
status code가 여러 파일에 걸쳐 흩어져 있는데 별도의 클래스로 분리하는 것은 어떨까요~?

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/Request.java
> +        if (url.equals(ROOT_URL)) {
ROOT_URL.equals(url)

2019-09-21 06:01 UTC, ssosso commented on src/main/java/http/RequestHeader.java
> +    public Map<String, String> extractQueryParameter() {
이미 request가 was에 들어올 때부터 queryParameter는 정해져있고 변할 일이 없는 값입니다.
queryParameter에 대한 연산을 하는 곳이 다양할 수 있는데 Request에게 계속해서 extract하도록 해도 될까요~?
한번 extract한 값을 저장하고 있다가 반환 되게끔 할 수 있을까요~?

2019-09-24 07:26 UTC, yuyu154 commented on src/main/java/http/Response.java
> +    public void setStatusCode(int statusCode) {
HttpResponse 클래스에 addHeader() 메소드를 추가해서 setter를 안쓰고 header를 등록하도록 수정했습니다.  
```
    public void addHeader(String key, String value) {
        headers.put(key, value);
    }
```

2019-09-24 07:27 UTC, yuyu154 commented on src/main/java/http/ResponseHeader.java
> +        this.type = String.format("text/%s", type);
ResourceType 인터페이스를 상속하는 Image, Text, Font ResourceType 클래스를 추가했습니다.

2019-09-24 07:27 UTC, yuyu154 commented on src/main/java/http/ResponseHeader.java
> +    private static final int OK_STATUS_CODE = 200;
StatusCode를 Enum을 활용해서 분리했습니다. 괜찮은 방식일까요?

2019-09-24 07:27 UTC, yuyu154 commented on src/main/java/http/Request.java
> +        if (url.equals(ROOT_URL)) {
수정했습니다. 감사합니다!

2019-09-24 07:28 UTC, yuyu154 commented on src/main/java/http/RequestHeader.java
> +    public Map<String, String> extractQueryParameter() {
HttpRequest클래스에서 Map 형태로 가지고 있다가 getParameter() 함수를 이용해 가져오게끔 변경했습니다.

2019-09-24 15:22 UTC, ssosso approved these changes
르윈 안녕하세요, 쏘쏘입니다~
변경사항이 많았네요:) 몇 가지 피드백 드리오니 다음 단계와 함께 고민 부탁드립니다.
고생 많으셨습니다:)

2019-09-24 15:22 UTC, ssosso commented on src/main/java/http/HttpRequestBody.java
> +            String value = queryParam.split(DELIMITER_OF_FORM_PARAMETER)[1];
split은 한번만 진행해도 될 것 같아요:)

2019-09-24 15:22 UTC, ssosso commented on src/main/java/http/support/resource/FontResourceType.java
> +}
Response Content type에는 현재 개선한 interface나 abstract 구조이면 다양한 type 지원을 위해 많은 클래스를 만들어야 할텐데, 조금 더 간결하고 유지보수하기 좋은 구조는 없을까요~? 현재 구조로 진행해도 당장은 문제가 없겠지만 고려해봐주세요:)

2019-09-24 15:22 UTC, merged