[학성] 4단계 - 멀티 모듈 적용 미션 제출합니다.
woowacourse/jwp-was pull request #177
Opened 2020-10-27 05:32 UTC by ordinCode

어느덧 마지막 단계네요:)

다음과 같은 구조로 나누어봤는데요
- webserver
- user
- common 

webserver 모듈을 만들고 user모듈에서 webserver모듈의 기능 가져다가 어플리케이션을 실행하는 구조로 수정해보았습니다.
common모듈에는 순수 java 로만 된 유틸성 코드를 배치시켜보았습니다. 잘부탁드립니다.

2020-10-29 14:07 UTC, jeonghoon1107 requested changes
안녕하세요 학성!
간단한 피드백을 남겼으니 확인해주세요.

2020-10-29 14:07 UTC, jeonghoon1107 commented on settings.gradle
> +include 'user'
모듈 이름만 보아서는 어떤 역할인지 잘 와닿지 않네요. user란 이름보다는 조금 더 범용적인 네이밍이 좋지 않을까요?

2020-10-29 14:07 UTC, jeonghoon1107 commented on web-server/build.gradle
> +    implementation project(':common')
common으로 분리한 장점이 없어보여요.
유틸성 클래스들은 패키지로 구분해도 충분할 것 같아요 :)

2020-10-29 14:07 UTC, jeonghoon1107 commented on user/src/main/java/util/TemplateMaker.java
>  import com.github.jknack.handlebars.Helper;
동시성 이슈는 발생하지 않을 것 같은데 ClassPathTemplateLoader와 Handlebars는 재사용할 여지가 없나요?

2020-10-29 14:07 UTC, jeonghoon1107 commented on web-server/src/main/java/webserver/WebServer.java
> +    public static void main(String args[], List<AbstractServlet> controllers) throws Exception {
main의 인자로 변경하신 이유가 있나요?

2020-10-29 15:05 UTC, ordinCode commented on settings.gradle
> +include 'user'
적절한 네이밍이 떠오르지 않아 미션에 "...사용자 관리라는 응용 애플리케이션으로 나눈다.."라고 되어있어서 user라고 지어봤는데 지금보니까 영 아니네요.
application-service-module로 수정해보긴했는데 사실 지금 나뉜 모듈의 역할을 정확히 뭐라고 정의할 수 있을지 와닿지가 않은 것도 있어요. 혹시 나뉜 모듈의 역할을 잘 표현할 수 있는 더 좋은 네이밍 하나 조언해주실 수 있나요?

2020-10-29 15:08 UTC, ordinCode commented on web-server/src/main/java/webserver/WebServer.java
> +    public static void main(String args[], List<AbstractServlet> controllers) throws Exception {
web-server 모듈의 main메서드를 다른 모듈에서 가져다가 사용하는데 그 때 다른 모듈에 있는 컨트롤러를 WebServer에 초기화 해주는 방법으로 위에 처럼 수정했습니다. 혹시... 잘못된 방법인가요?

2020-10-29 15:11 UTC, ordinCode commented on user/src/main/java/util/TemplateMaker.java
>  import com.github.jknack.handlebars.Helper;
이부분은 web-server 모듈로 가는게 맞을 것 같네요 감사합니다:)

2020-11-01 15:31 UTC, jeonghoon1107 requested changes
안녕하세요 학성!
아쉬운 부분이 있어서 피드백남겼으니 확인부탁드려요.

2020-11-01 15:31 UTC, jeonghoon1107 commented on build.gradle
> +        implementation 'com.github.jknack:handlebars:4.2.0'
gradle.properties를 이용해보면 어떨까요?

2020-11-01 15:31 UTC, jeonghoon1107 commented on application-service-module/src/main/java/Application.java
> +        WebServer.main(args, controllers);
지금은 controller만 있지만 controller이외의 다른 클래스가 필요하다면 확장성이 떨어져보이네요.
WebServer.main에 Application.class를 주고 프레임워크에서 Application.class의 root package부터 controller를 스캔하는 방법도 좋을것 같아요!
어떻게 생각하시나요?

2020-11-01 15:31 UTC, jeonghoon1107 commented on web-server/src/main/java/webserver/WebServer.java
> +    public static void main(String args[], List<AbstractServlet> controllers) throws Exception {
호출부에 의견남겼습니다!

2020-11-01 15:31 UTC, jeonghoon1107 commented on application-service-module/src/main/java/controller/LoginController.java
> +public class LoginController extends AbstractServlet {
validateLoginRequests 메서드에서 500 에러를 주고 있는데 더 적절한 상태를 주면 어떨까요?
controller 테스트가 부족한 것 같은데 각 정상, 예외 케이스에 대해서도 테스트가 추가되면 좋을 것 같아요 :)

2020-11-02 06:20 UTC, ordinCode commented on application-service-module/src/main/java/controller/LoginController.java
> +public class LoginController extends AbstractServlet {
네 테스트 추가해주었습니다!

그리고 500에러와 관련해서는...
현재 `validateLoginRequests` 메서드에서 발생시키는 에러는 `NotFoundUserIdException` 와 `IllegalPasswordException` 인데 둘다 `LoginException` 을 상속받고 있습니다.
그래서 
```java
 } catch (LoginException e) {
            logger.error(e.getMessage());
            session.setAttribute(SESSION_KEY_OF_LOGIN, Boolean.toString(false));
            httpResponse.sendRedirect("/user/login_failed.html");
        }
```
이렇게 처리하고 있는데 이러면 500에러가 발생 안하지 않을까요? 혹시 제가 놓치고 있는 부분이 있을까요?

2020-11-03 04:25 UTC, ordinCode commented on application-service-module/src/main/java/Application.java
> +        WebServer.main(args, controllers);
고민해봤는데 어노테이션을 사용하는게 나을 것 같아서 어노테이션을 사용하는 방향으로 수정해보았습니다!

2020-11-05 13:55 UTC, jeonghoon1107 approved these changes
안녕하세요 학성!
깔끔하게 구현 잘 하셨네요 👍 
간단한 피드백을 남겼습니다!
미션 진행하느라 고생하셨습니다 :)

2020-11-05 13:55 UTC, jeonghoon1107 commented on web-server/src/main/java/webserver/WebServer.java
> +    public static final String CONTROLLER_PACKAGE_PATH = "controller";
프레임워크가 controller라는 패키지를 알게 되었으니 의존성이 생긴 것 같네요.
Application.class를 인자로 넘겨 받아 package를 주었으면 더 좋았을 것 같아요!

2020-11-05 13:55 UTC, jeonghoon1107 commented on application-service-module/src/main/java/controller/LoginController.java
> +public class LoginController extends AbstractServlet {
비밀번호 혹은 없는 user일 경우 파라미터가 잘못된 것 아닐까요?
IllegalArgumentException이 더 명시적인 것 같아요!

2020-11-05 13:55 UTC, merged