[히로] 3단계 - HTTP 웹 서버 리팩토링 미션 제출합니다.
woowacourse/jwp-was pull request #178
Opened 2020-10-27 05:43 UTC by hotheadfactory

잘 부탁드립니다 (__)

2020-10-28 08:59 UTC, jaeyeonling requested changes
3단계 요구사항을 잘 구현해주셨네요 👍 
머지하는 과정에서 정리가 안된 부분과 피드백 확인해주세요 :)

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/AuthController.java
> +    protected HttpSession retrieveHttpSession(HttpRequest httpRequest) {
지금 구조에서는 HttpSession을 사용하기 위해서는 무조건 AuthController를 상속받아야 하네요!
HttpSession은 다른 상황에서도 쓰일 수 있는 기능이기 때문에 해당 기능을 HttpRequest에게 옮기는 것이 좋을 것 같아보여요!

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/AuthController.java
> +        if (httpRequest.hasCookie("SESSIONID")) {
SESSIONID는 특별한 의미를 가지고 있습니다!
매직 스트링보다 상수로 분리하여 관리해보아요.

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/response/HttpResponse.java
> +    private final String header;
String 타입은 헤더의 역할을 나타낼 수 없습니다!
별도 클래스로 관리한다면 어떠한 차이가 있을지 고민해보아요.

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/session/HttpSessionStorage.java
> +    private static Map<String, HttpSession> storage = new HashMap<>();
```suggestion
    private static final Map<String, HttpSession> storage = new ConcurrentHashMap<>();
```

static 변수에는 final을 붙여주는 관례가 왜 있을지 고민해보아요.
또한 여러 쓰레드에서 접근하는 경우 동시성을 보장하는 타입도 고려해보세요!

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/RawFileController.java
> +        } catch (NullPointerException e) {
NullPointerException시 NotFound를 응답하고 있네요!
의도하지 않은 상황에서 NullPointerException가 발생한다면 의도와 다르게 NotFound를 응답할 수 있기 때문에 명확한 예외처리를 해주는 것이 좋습니다.

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/UserListController.java
> +            Handlebars handlebars = new Handlebars(loader);
해당 객체를 요청마다 생성할 필요가 있을까요?
객체를 재사용한다면 어떠한 차이가 있을지 고민해보아요.

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/utils/HttpResponseHeaderParser.java
>  public class HttpResponseHeaderParser {
해당 클래스가 가지고 있는 역할을 Response에게 위임해보면 어떨까요?

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/UserLoginController.java
> +        } else {
규칙 2: else 예약어를 쓰지 않는다.

를 지켜보면 좋을 것 같습니다!

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/controller/UserLogoutController.java
> +        String header;
선언과 초기화를 따로 하신 이유가 있을까요!?

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/request/Cookie.java
> +            for (String token : tokens) {
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

규칙을 위반하셨습니다!

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/webserver/RequestHandler.java
> +<<<<<<< HEAD
머지가 제대로 안된 것 같아요 @_@
충돌난 부분은 정리 후 다시 리뷰하도록 하겠습니다!

2020-10-28 08:59 UTC, jaeyeonling commented on src/main/java/http/request/RequestHeader.java
> +        }
```suggestion
        this.cookie = new Cookie(params.getOrDefault("cookie", ""));
```

getOrDefault를 활용할 수 있겠네요!

2020-11-23 07:51 UTC, hotheadfactory commented on src/main/java/utils/HttpResponseHeaderParser.java
>  public class HttpResponseHeaderParser {
Response가 ok(), found(), badRequest()... 상황별 메소드를 다 들고 있어도 무관할까요? 그게 좀 지저분한 것 같아 뺐는데...

2020-11-24 07:30 UTC, jaeyeonling approved these changes
피드백을 잘 반영해주셨습니다 👍 
추가로 피드백 남겨드렸으니 다음 단계 진행하며 반영해주세요 :)

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/controller/UserLoginController.java
> +    public static final String SESSIONID = "SESSIONID";
중복되는 상수가 2개가 있네요!
상수로 분리하신 만큼 동일한 상수를 사용해보면 어떨까요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/request/HttpRequest.java
> +        }
```suggestion
        if (!this.hasCookie(SESSIONID)) {
            return HttpSessionStorage.create();
        }

        HttpSession httpSession = HttpSessionStorage.getSession(this.getSessionId());
        if (httpSession == null) {
            httpSession = HttpSessionStorage.create();
        }
        return httpSession;
```

Early Return이 주는 이점에 대해 고민해보아요.

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/controller/UserListController.java
> +                TemplateLoader loader = new ClassPathTemplateLoader();
최초 1회 초기화하는 것이 목적이라면 생성자에서 처리해줄 수 있을 것 같은데 어떻게 생각하시나요?
지금의 구조에서 발생할 수 있는 문제가 어떤게 있을지 같이 고민해보면 좋겠어요!

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/response/Header.java
> +public class Header {
해당 클래스는 어떠한 역할을 담당하고 있을까요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/resources/templates/user/list.html
> +        window.location.replace("/user/login.html");
Redirect 처리를 클라이언트가 아닌 서버에서 해주면 어떨까요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/controller/RawFileController.java
>      private static final Logger logger = LoggerFactory.getLogger(RequestHandler.class);
RequestHandler의 로거를 생성하는 것이 의도된 내용일까요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/controller/UserLoginController.java
> +        HttpSession httpSession;
변수의 선언과 초기화를 따로 하신 이유가 있을까요?
가능한 변수의 라이프 사이클을 작게 유지하는 것이 유지보수에 유리합니다!!

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/response/HttpResponse.java
> +    public void createResponse(DataOutputStream dos) {
create-라는 메서드 명은 생성한 정보를 return할 것 같은 느낌이 드네요!
조금 더 명확한 이름이 없을지 고민해보아요.

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/session/HttpSessionStorage.java
> +    private static final Map<String, HttpSession> storage = new HashMap<>();
```suggestion
    private static final Map<String, HttpSession> storage = new ConcurrentHashMap<>();
```

해당 변수는 여러 스레드에서 접근할 수 있기 때문에 최소한의 동시성을 보장해주는 것이 좋습니다 :)

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/service/UserService.java
> +        return userById.getPassword().equals(password);
getter를 사용하지 않고 메시지를 던져보면 어떨까요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/controller/RawFileController.java
> +        } catch (PageNotFoundException e) {
커스텀한 Exception을 만들어 해당 Exception에서 응답의 정보를 관리한다면 추후 예외처리가 늘었을 때 catch문을 늘리지 않아도 될 것 같습니다 :)

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/http/request/Cookie.java
> +public class Cookie {
Cookie.parseCookie Cookie.parse

Cookie라는 클래스 이름으로 Cookie의 기능이라는 사실을 알 수 있기 때문에 메서드 명에 Cookie를 제거해도 괜찮을 것 같은데 어떻게 생각하시나요?

2020-11-24 07:30 UTC, jaeyeonling commented on src/main/java/utils/HttpResponseHeaderParser.java
>  public class HttpResponseHeaderParser {
모든 상황에 대해 만드는 것이 가독성을 해친다 생각이 되신다면 자주 사용하는 메서드만 만드시는 것도 방법이 될 수 있고, 
기능 별 클래스를 분리하여 Facade를 통해 제공한다면 괜찮을 것 같은데 어떻게 생각하시나요?
해당 리뷰의 핵심은 응답의 정보를 `String`이 아닌 `Response` 내부에서 `ResponseLine`, `Header` 등의 도메인으로 처리해보면 좋을 것 같아 남겨드렸습니다 :)

2020-11-24 07:36 UTC, merged