[웹서버 - Step1] 규동 미션 제출합니다.
woowacourse/jwp-was pull request #19
Opened 2019-09-20 11:21 UTC by kmdngyu

안녕하세요 정훈 님! 처음 뵙겠습니다 😀.
이번에 리뷰 요청을 드리게 된 규동입니다. 앞으로 잘 부탁드립니다! 

먼저 몇 가지 질문드리고 싶습니다.
#### 1. StaticFile을 읽고 Content-Type을 읽는 방식
- 현재 Apache Tika로 요청한 파일의 MIME를 직접 읽어와 Content-Type을 내보내는 방식을 사용하고 있습니다. 다른 크루들의 경우 파일의 확장자와 Content-Type을 enum으로 만들고 요청 온 파일의 전체 path에서 확장자를 파싱한 확장자를 통해 Content-Type을 찾습니다. 전자의 방식은 파일을 불러올 때마다 메타데이터를 확인하는 비용이 있고 후자는 리소스 파일이 실제 타입과 확장자가 일치하지 않는 경우가 있을 수 있습니다. 어떤 방식이 더 알맞은지 궁금합니다.

#### 2. Redirect의 경우 body 포함 유무
- Redirect를 하는 경우 클라이언트가 body를 받지만 아무 역할을 하지 않는데 보내는 것이 의미가 있을까요? 혹시 Redirect에서도 body가 사용되는 경우가 있는지 궁금합니다.

전반적으로 아직 추상화나 테스트가 부족한데 그에 관한 조언을 얻고 싶습니다. 많은 지적 부탁드립니다.
감사합니다!

2019-09-21 12:47 UTC, jeonghoon1107 requested changes
안녕하세요 규동!
깔끔하게 잘 구현하셨네요 👍 
피드백 몇가지 남겼으니 참고하여 리팩토링 진행해주세요!

1. 두 방법 다 괜찮은 것 같지만, Accpet는 client 측에서 해당 타입으로 데이터를 달라고 요청하는 것이기 때문에 Accept를 사용해보면 어떨까요?
https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Accept
https://www.zerocho.com/category/HTTP/post/5b3ba2d0b3dabd001b53b9db

2. 원하는 답변이 될지는 모르겠지만, redirect시 데이터는 사용하기 나름일 것 같아요.
스프링에서는 redirect시 데이터를 같이 넘겨줄 수 있는 속성이 있어요.
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/support/RedirectAttributes.html

혹시 답변이 만족스럽지 못했거나 더 궁금한 것이 있으면 DM 주세요!

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/handler/MappingHandler.java
> +    public static HttpServlet getServlets(String absPath) {
path를 찾지 못하면 404를 반환하는게 올바른 응답이 되겠네요!

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/RequestHandler.java
> +        } catch (IOException | URISyntaxException e) {
적절한 행위가 추가되어야 할 것 같네요

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/servlet/RequestServlet.java
> +        throw new MethodNotAllowedException(METHOD_NOT_ALLOW_MESSAGE, HttpStatus.METHOD_NOT_ALLOW);
실제로 응답값에 의도한 상태코드가 들어갔나요?

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/response/HttpStatus.java
> +    METHOD_NOT_ALLOW(405, "Method Not Allow");
👍

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/test/java/webserver/servlet/UserCreateServletTest.java
> +        InputStream inputStream = new FileInputStream(new File(testDirectory + "request_form_post_test.txt"));
테스트 케이스를 추가할 때마다 파일이 추가될 것 같은데 다른 방식을 추가해보면 어떨까요?

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/test/java/webserver/servlet/UserCreateServletTest.java
> +    @Test
junit5를 사용하면 더 편리한 기능을 많이 제공해요.
DisplayName을 사용해보면 어떤 테스트를 하는 것인지 더 명시적으로 나타낼 수 있을 것 같네요.

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/parser/HttpRequestParser.java
> +        while (!"".equals(line) && null != line) {
조건이 많아질수록 가독이 안좋아 질 것 같은데 명시적으로 메서드로 추출하면 좋을 것 같아요.

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/handler/MappingHandler.java
> +    private static Map<String, Object> servlets = new HashMap<>();
map의 value type으로 HttpServlet를 사용하면 어떨까요?

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/handler/MappingHandler.java
> +        return (HttpServlet) path.orElse(new FileServlet());
getOrDefault를 사용하는게 가독성이 더 좋을 것 같아보이네요.

2019-09-21 12:47 UTC, jeonghoon1107 commented on src/main/java/webserver/response/HttpResponse.java
> +        dos.writeBytes("\r\n");
전반적으로 상수로 사용할만한 것들이 많이보이네요!

2019-09-24 15:55 UTC, kmdngyu commented on src/main/java/webserver/RequestHandler.java
> +        } catch (IOException | URISyntaxException e) {
URI 예외 처리 위치를 변경했습니다!

2019-09-24 15:56 UTC, kmdngyu commented on src/main/java/webserver/servlet/RequestServlet.java
> +        throw new MethodNotAllowedException(METHOD_NOT_ALLOW_MESSAGE, HttpStatus.METHOD_NOT_ALLOW);
제가 이해를 잘 못 했는데 일단 예외 처리 방식을 바꾸었습니다

2019-09-24 15:56 UTC, kmdngyu commented on src/main/java/webserver/response/HttpStatus.java
> +    METHOD_NOT_ALLOW(405, "Method Not Allow");
감사합니다!

2019-09-24 15:57 UTC, kmdngyu commented on src/test/java/webserver/servlet/UserCreateServletTest.java
> +        InputStream inputStream = new FileInputStream(new File(testDirectory + "request_form_post_test.txt"));
스트링을 버퍼를 만드는 메소드를 테스트 쪽에 헬퍼로 추가해 사용하는 방식으로 바꾸었습니다.

2019-09-24 15:58 UTC, kmdngyu commented on src/main/java/webserver/parser/HttpRequestParser.java
> +        while (!"".equals(line) && null != line) {
유틸로 추출하였습니다.

2019-09-24 15:59 UTC, kmdngyu commented on src/main/java/webserver/handler/MappingHandler.java
> +    private static Map<String, Object> servlets = new HashMap<>();
변경했습니다!

2019-09-24 16:01 UTC, kmdngyu commented on src/test/java/webserver/servlet/UserCreateServletTest.java
> +    @Test
가능하면 메소드의 이름만으로 어떤 테스트인지 알 수 있도록 하고 싶었는데 부족했던 것 같습니다. DisplayName으로 테스트 내용을 명시해 보충해주는게 확실히 더 좋은 방식 같습니다. 감사합니다.

2019-09-24 16:01 UTC, kmdngyu commented on src/main/java/webserver/response/HttpResponse.java
> +        dos.writeBytes("\r\n");
상수로 변경하였습니다!

2019-09-24 19:44 UTC, kmdngyu commented on src/main/java/webserver/handler/MappingHandler.java
> +    public static HttpServlet getServlets(String absPath) {
네 에러 처리를 추가 했습니다!

2019-09-24 19:49 UTC, kmdngyu commented
먼저 상세한 리뷰 정말 감사드립니다.!

1. accept에는 여러 MIME을 포함하고 있는데 처리 방법을 몰라 일단 기존 방법을 유지하고 있습니다. 어차피 요청이 그렇게 들어온거라 그 중 하나만 사용하면 되는 것인지 궁금합니다.
2. 현재 전반적인 구조 개선 중인데 스프링을 참조해서 고쳐보겠습니다.

2단계 진행을 생각하면 전체적으로 구조를 많이 변경하여야 할 것 같습니다. 시간이 많이 소요될 것 같아 일단 리뷰 요청 드립니다. 감사합니다.

2019-09-25 10:06 UTC, woowahanjeonghoon1107 commented on src/main/java/webserver/handler/MappingHandler.java
> +        if (requestUri.isFile()) {
url에 .의 유무로 판단하는 것은 좋지 않은 방식같아요.

2019-09-25 10:06 UTC, woowahanjeonghoon1107 commented on src/main/java/webserver/servlet/RequestServlet.java
> +        throw new MethodNotAllowedException(METHOD_NOT_ALLOW_MESSAGE, HttpStatus.METHOD_NOT_ALLOW);
method not allowed의 http status 코드는 405이죠.
그런데 현재는 MethodNotAllowedException 해당 exception을 뱉으면 client 측에는 다른 값으로 떨어질 것 같아요.

2019-09-25 10:12 UTC, woowahanjeonghoon1107 approved these changes
안녕하세요 규동! 리팩토링 잘하셨네요 👍 
사소한 피드백 몇가지 남겼으니 참고하여 다음 단계 진행해주세요 :)

2019-09-25 10:12 UTC, woowahanjeonghoon1107 commented on src/test/java/webserver/handler/MappingHandlerTest.java
> +        HttpServlet homeServlet = MappingHandler.getServlets("/");
파라미터 타입을 바꾸었으니 테스트에서도 바꾸어야겠네요 :)

2019-09-25 10:14 UTC, merged

2019-09-25 10:16 UTC, jeonghoon1107 commented on src/main/java/webserver/servlet/UserCreateServlet.java
> +        User user = new User(httpRequest.getBody("userId"), httpRequest.getBody("password"), httpRequest.getBody("name"), httpRequest.getBody("email"));
user를 저장해야하지 않나요?

2019-09-25 10:18 UTC, jeonghoon1107 commented on src/main/java/webserver/servlet/HttpServlet.java
> +    HttpResponse run(HttpRequest httpRequest) throws IOException;
Request, Response를 같이 받아서 처리해도 깔끔할 것 같아요.

2019-09-25 10:23 UTC, jeonghoon1107 commented on src/test/java/webserver/servlet/HomeServletTest.java
> +    void doGet_rootGetRequest_ok() throws IOException, URISyntaxException {
테스트 케이스를 더 추가하면 좋을 것 같아요.
테스트 케이스를 추가하면서 어떻게 중복을 제거 할지에 대한 고민도 같이 하면 좋겠네요 :)