[코즈] 2단계 - HTTP 웹 서버 리팩토링 미션 제출합니다.
woowacourse/jwp-was pull request #197
Opened 2020-11-13 12:36 UTC by kouz95

안녕하세요 화투! 좋은 리뷰 감사드립니다. 🙂
주신 피드백 최대한 반영하여 구현해보았습니다.
부족한 부분 있으면 피드백 부탁드립니다!
감사합니다.

2020-11-15 15:21 UTC, phs1116 requested changes
안녕하세요, 코즈! 
구현 깔끔하게 잘해주셨어요, 역할을 어떻게 나눌지 고민 많이하시넥 보여요. 👍 
몇가지 피드백 추가했는데 참고 부탁드려요!

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/RequestHandler.java
> +            new HttpServlet().doDispatch(httpRequest, response);
HttpServlet이 현재 상태를 가진 객체가 아닌데 굳이 매번 생성할 필요가 있을까요?

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/http/request/TemplateFile.java
> +    ICO(".ico", "image/x-icon");
아이콘도 템플릿으로 사용되나요??

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/http/response/HttpResponse.java
> +        }
try-catch를 한줄로 묶을 수 있을 것 같아요.
그리고 NPE는 어떤케이스에서 발생하는걸까요? 파일이 없을 경우에 IOException이 아니라 NPE도 발생하나요?

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/http/response/HttpResponse.java
> +        } catch (IOException e) {
notFound가 notFound를 호출하는 무한 재귀로 보이는데 괜찮을까요?
그리고 현재 케이스에서 NPE가 발생할 요인이 없어보이는데 해당 예외 처리가 필요할까요?

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/http/servlet/view/RedirectView.java
> +    }
render에 대해서 컨트롤러 등에서 실수로 호출하는 일이 없도록 접근제어 관리를 고민해봐도 좋을 것 같아요!

2020-11-15 15:21 UTC, phs1116 commented on src/main/java/webserver/http/servlet/controller/ResourceController.java
> +    }
리소스 처리에 대한 부분은 굳이 Controller로 묶일게 아니라 별도 처리로 나누었어도 괜찮았을 거 같네요. :)

2020-11-16 04:18 UTC, kouz95 commented on src/main/java/webserver/http/request/TemplateFile.java
> +    ICO(".ico", "image/x-icon");
현재 `resources/templates/favicon.ico` 가 있는데, static으로 옮기는게 좋을까요?

2020-11-16 05:07 UTC, kouz95 commented on src/main/java/webserver/http/response/HttpResponse.java
> +        }
파일 형식은 지원하지만 존재하지 않는 자원일때`FileIoUtils.loadFileFromClasspath()` 에서 NPE 발생하는것으로 확인했습니다.
`GET /test` 라는 요청을 보내면 지원하지 않는 파일이기 때문에 400 Bad Request를 응답하도록 하였고, `GET /test.html` 같은 경우는 존재하지 않는 자원이라고 판단하여 404 Not Found를 응답하도록 구현하였습니다!

2020-11-21 16:07 UTC, phs1116 approved these changes
안녕하세요, 코즈!
옵셔널 통한 리팩토링 매우 깔끔하게 잘해주셨네요. 👍 
View객체는 그냥 인터페이스로 뒀어도 괜찮았을 것 같아요. :)
2단계는 이만 머지할게요. 수고 많으셨습니다.

2020-11-21 16:07 UTC, phs1116 commented on src/main/java/webserver/http/request/TemplateFile.java
> +    ICO(".ico", "image/x-icon");
네. 파일 경로의 위치를 변경해도 괜찮을 것 같아요.
template 디렉토리는 순수하게 템플릿만 있는게 좋을 것 같네요. :)

2020-11-21 16:07 UTC, phs1116 commented on src/main/java/webserver/http/servlet/AbstractView.java
> +    abstract void render(HttpRequest request, HttpResponse response);
인터페이스에서 추상 클래스로 굳이 변경할 필요가 있었나 싶네요. :)

2020-11-21 16:07 UTC, phs1116 commented on src/main/java/webserver/http/servlet/controller/ControllerMapping.java
> +    public static Optional<Controller> get(RequestMapping requestMapping) {
옵셔널 활용 👍

2020-11-21 16:08 UTC, merged