Jun ho park93
woowacourse/jwp-was pull request #26
Opened 2019-09-20 14:29 UTC by JunHoPark93

안녕하세요! 리뷰어님! 리뷰이 제이입니다. 미션이 쉽지 않네요.
진행과정에서 몇 가지 궁금점이 있습니다.

처음에 구상한 프레임워크 사용법은 

개발자가 만드는 부분: 
* Controller 클래스의 get,post...요청로직처리. 
* HandlerMapper에 만든 컨트롤러를 직접 등록.
으로 요청을 처리하게끔 했습니다!

그리고 몇 가지 궁금한 것이 있습니다! 첫번 째로 처음에 수업자료에 있는 설계를 참고해 시작을 했습니다.

<img width="730" alt="Screen Shot 2019-09-20 at 10 46 06 PM" src="https://user-images.githubusercontent.com/20608121/65334725-fa0ee600-dbfd-11e9-9b8b-710fcf87dafc.png">

요 그림인데, 최상위 인터페이스인 Controller가 service 라는 추상화된 기능을 노출하고 그것을 추상컨트롤러가 먼저 받습니다. 그리고 그 추상클래스를 상속하는 여러 컨트롤러 (개발자가 구현하는 부분) 가 존재하는 모습이었습니다. 제가 이 그림을 이해하기로는 AbstractController에 doPost, doGet을 abstract로 두면 하위에서는 무조건 구현해야 하는 문제가 있었습니다. 그래서 doPost와 doGet은 직접 불리면 error response를 주도록 바디를 구현하였고 service 함수도 httprequest 객체의 status에 따라 get, post 분기를 나누었습니다. 직접 Abstract Controller를 생성하지 못하도록 abstract를 붙여주었구요. 그래서 개발자가 만든느 컨트롤러는 get post 요청이 필요한 부분만 선택적으로 override할 수 있게 만들었습니다. 

doPost와 doGet을 abstract로 두어 하위에서 각자 재정의하고 미리 추상클래스에 정의된 service메서드를 통해 실행하는 템플릿 패턴을 써보라는 의도인줄 알았지만 doGet, doPost를 전부구현하는 문제 때문에 Abstract Controller에서도 바디를 구현했습니다. **이 구조가 혹시 이상한지 궁금합니다**. 상위 메서드에 내부구현을 보지않고 쓰다가 오동작하는 것을 최소화 하기위해  클래스의 주의를 요하는 주석을 달아놓았습니다.

두 번째로 이름을 Controller 로 하여

```java
public class UserController extends AbstractController {
    @Override
    protected void doGet(HttpRequest request, HttpResponse response) {
        if ("/user/form.html".equals(request.getPath())) {
            request.getResource();
            response.sendRedirect("user/" + request.getResource(), HttpStatus.OK);
        }
    }
```

맞는 컨트롤러를 찾은 후, 요청 url 매핑 별로 if 문을 타게끔해서 request mapping 같이 하는 방법으로 구현했습니다. 메서드 이름에서 doGet, doPost들이 나오는데 클래스 이름이 컨트롤러가 아닌 (기능은 컨트롤러 비슷하게 하고있지만) 서블릿이 맞는 네이밍인지 궁금합니다.

항상 감사드립니다!

2019-09-21 14:03 UTC, byjo requested changes
안녕하세요. 리뷰를 맡은 브리입니다.
미션 진행을 하면서 전체적으로 고민을 많이 하신 점이 느껴졌습니다. 👍
다만, `RequestHandler`와 관련 로직들이 리팩토링 되면 더 좋을 것 같아 피드백 드려요.

그리고 PR 주시면서 질문하신 내용에 대한 답변은 💡 이모지를 달았으니 참고해주세요.
혹시나 코멘트 드린 내용에 더 궁금한 점이 있으시다면 편하게 문의 주시구요.

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
💡 먼저 `AbstractController` 클래스가 필요한 이유는 무엇일까요? 
요청 URL은 같지만 HTTP 메소드가 다른 경우 계속해서 새로운 Controller를 추가해야 하는 번거로움이 있기 때문입니다. 
(예를 들어 RESTful api를 적용했을 때 `/users` 요청이 get 일 때는 유저 목록을 제공하고, post일 때는 유저 생성을 지원하겠죠. 
이 때 `Controller` 인터페이스만을 사용한다면 요청의 개수만큼 Controller가 생기게 되겠죠.)

말씀 주신 대로 `doGet`, `doPost` 메소드가 추상 메소드라면, 하위 클래스에서 모두 구현을 해야하는 번거로움이 있기 때문에 목적에 맞게 잘 구현하신 것 같습니다.

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/controller/AbstractController.java
> +        response.sendError(HttpStatus.FORBIDDEN, "잘못된 doGet 메서드의 호출입니다");
하위 클래스에서 메소드를 오버라이딩 하지 않았을 때 해당 구문을 타게 되는데, 이 경우에 Not Allow 에러를 주는 것이 더 적절하지 않나요?
```suggestion
        response.sendError(HttpStatus.NOT_ALLOWED, "지원하지 않는 http method 형식입니다");
```
27 line의 if 문에서의 처리와 바뀐 것이 아닐까 싶은데 어떠신가요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/controller/AbstractController.java
> +        response.sendError(HttpStatus.FORBIDDEN, "잘못된 doGet 메서드의 호출입니다");
에러 메시지가 잘못 되었네요.

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/controller/UserController.java
> +        if ("/user/create".equals(request.getPath())) {
Controller에서 자신이 처리할 수 있는 요청인지 확인하는 분기가 있는 것이 어색하네요. 
Controller의 `service` 메소드가 실행되는 시점에는 이미 해당 컨트롤러가 요청을 처리할 수 있다는 것이 확인 된 이후가 아닐까요?

아래와 같이 `RequestHandler` 에서 요청에 따른 handler(controller를 wrapping한)를 조회할 때 요청 path가 아닌 directory로 조회를 하는데 그 이유가 있을까요?
https://github.com/woowacourse/jwp-was/blob/de05075a3bbc113b2c44799aefdb25a723773ee2/src/main/java/webserver/RequestHandler.java#L55

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/http/request/HttpRequest.java
> +        if (requestBody != null) {
위에서 정의한 `isBodyExists()` 메소드를 사용하면 더 좋지 않을까요?
```suggestion
        if (isBodyExists()) {
```

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/http/request/HttpRequest.java
> +    static HttpRequest createWithBody(RequestLine requestLine, RequestHeader requestHeader, RequestBody requestBody) {
HttpRequest에 빌더 패턴을 적용해보면 어떨까요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/http/request/RequestLine.java
> +        if (path.contains("?")) {
`?`와 같은 문자열은 상수로 관리하시면 코드 가독성이 높을 뿐만 아니라, 디버깅 및 유지보수에도 좋습니다.

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/http/response/HttpResponse.java
> +    public void sendRedirect(String location, HttpStatus httpStatus) {
리다이렉트의 경우는 HttpStatus를 파라미터로 받지 않아도 괜찮지 않나요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/RequestHandler.java
> +        for (Handler handler : HandlerList.LIST) {
`RequestHandler`가 직접 조건에 맞는 Handler를 찾기 보다는,
`HandlerList`에게 적합한 Handler 반환을 요청하면 어떨까요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/RequestHandler.java
> +    private void handleOutputStream(OutputStream out, ModelAndView mav, HttpResponse httpResponse) throws IOException
응답을 write하는 로직을 별도의 클래스로 분리하면 어떨까요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/controller/UserController.java
> +public class UserController extends AbstractController {
💡사실 Controller와 Servlet이 하는 역할은 동일합니다.
서블릿은 특정 기술 표준의 이름이기 때문에, 해당 기술을 사용하지 않는다면 여기서는 Controller가 더 적합하지 않을까요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/strategy/ControllerMappingHandler.java
> +        return null;
이 경우 요청 처리를 할 수 없는 것이니 null을 리턴하는 것보다 예외를 발생시키는 것이 좋지 않을까요?

2019-09-21 14:03 UTC, byjo commented on src/main/java/webserver/handler/strategy/ControllerMappingHandler.java
> +            controller.service(httpRequest, httpResponse);
💡 Model, View 객체를 도입하셨네요.
그렇다면 컨트롤러에서 요청 처리를 하면서 응답에 필요한 값은 Model에 넣어두고, 필요한 View를 생성하는 것이 더 자연스럽지 않을까요?
`HttpResponse`와 `ModelAndView` 두 객체의 역할과 책임이 무엇인지 정의해보시면 좋을 것 같아요.

2019-09-23 13:58 UTC, JunHoPark93 commented on src/main/java/webserver/handler/controller/AbstractController.java
> +        response.sendError(HttpStatus.FORBIDDEN, "잘못된 doGet 메서드의 호출입니다");
NOT_ALLOWED로 변경하였습니다!

2019-09-23 13:59 UTC, JunHoPark93 commented on src/main/java/webserver/handler/controller/UserController.java
> +        if ("/user/create".equals(request.getPath())) {
궁금한 점 DM 으로 해결하였습니다! 처음부터 구조를 directory, resource 로 나눠서 복잡하게 설계하여 어려움이 있었습니다. 조언 주신 것 참고하여 path 하나로만 간소화해보았습니다.

2019-09-23 14:05 UTC, JunHoPark93 commented
안녕하세요! 피드백 감사합니다!!
DM으로 문의드린 내용에서 더 많이 고민을 해보았습니다. 최대한 간단히 해보려고 노력했습니다.
 고민한 결과, Controller 매퍼가 컨트롤러의 Map을 가지고 있는 구조에서 -> 각 Controller 가 path를 보유하고 있는 방식으로 변경해보았습니다.
제가 생각한 장/단점은 map으로 관리하였을 때, 컨트롤러 검색 속도가 빠른점이 장점으로 생각하였지만 컨트롤러의 역할을 좀 더 고민한 결과 본인이 path를 알고 있는 구조가 조금 더 유연할 것 같아서 (속도는 최악의 경우 O(n)이지만) 그렇게 변경하였습니다. 유연하다고 생각한 이유는 커스텀 컨트롤러는 요청 url 자체만을 검사하고 리소스 컨트롤러같은 경우는 확장자,html 형식검사 등 url 매핑을 원하는대로 만들수 있어서 그렇게 생각했습니다.

고민결과 구조가 많이 바뀐점은 죄송합니다..ㅎㅎ😭
view 객체도 나중에 필요에 의해 만들어 가는 것으로 생각하고 일단은 삭제하였습니다!

2019-09-23 23:00 UTC, byjo approved these changes
피드백 드린 내용에 대해 많이 고민한게 느껴지네요! 👏
많은 내용이 바뀌었다 하셨지만, 구조화가 잘 되어 있어 이전보다 파악도 훨씬 수월했던 것 같습니다. 👍
다음 미션 진행하면서 코멘트 드린 내용도 함께 고민해보시면 좋을 것 같아요.

2019-09-23 23:00 UTC, byjo commented on src/main/java/webserver/handler/ControllerList.java
> +            new UserController(ViewResolverList.TEMPLATE_RESOLVER)
만약 Http Method에 따라 사용하는 ViewResolver가 다른 경우에는 어떻게 처리 할 수 있을까요?

2019-09-23 23:00 UTC, byjo commented on src/main/java/webserver/http/response/HttpResponse.java
> +    private void createHeader() {
리팩토링을 하며 HttpResponse 내 메소드에 많은 변화가 있었는데요.
클린코드에 코드의 순서 배치에 대한 도움될만한 내용이 있어 공유 드리니 참고하시면 좋을 것 같습니다.

[클린코드 - Ch. 05 형식 맞추기](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2005%20-%20%ED%98%95%EC%8B%9D%20%EB%A7%9E%EC%B6%94%EA%B8%B0.md#%EC%A2%85%EC%86%8D-%ED%95%A8%EC%88%98)

2019-09-23 23:00 UTC, byjo commented on src/main/java/webserver/http/response/HttpResponse.java
> +    public void flush(OutputStream out) {
`flush()` 란 메소드명이 stream이란 기술에 크게 연관되어 있네요. 

아래처럼 각 Controller에서 `send()`메소드를 호출할 때, 메소드명과 다르게 실제로 어떤 응답이 전달되지 않는 것도 어색하게 느껴지구요.
https://github.com/woowacourse/jwp-was/blob/f25dc52912c315071135ce996653bec814cebfaf/src/main/java/webserver/handler/controller/custom/HomeController.java#L18

의미있는 메소드명을 지어보는 것은 어떨까요?

2019-09-23 23:00 UTC, merged