[웹 서버 Step-1] 코나스 미션 제출합니다.
woowacourse/jwp-was pull request #34
Opened 2019-09-21 18:07 UTC by Conatuseus

안녕하세요 하비! ✋ 처음뵙네요!
목요일에 페어 프로그래밍으로 끝냈지만, 혼자 다시 짜보고 싶어서 며칠간 다시 짜서 늦어졌네요.
현재 **테스트코드 작성, 상수 처리**가 부족해서 내일(9.22 일요일) 추가하겠습니다!!
이번 미션 구현하면서 고민&질문들이 있어요.

1.  HttpRequest를 생성하는데 parser을 거의 다 사용하고 있어요.
짜고나서 패키지 구조 정리하는데 너무 많은 것 같아요.
이 부분이 이상하다거나, 고쳤으면 하는 방향이 있을까요?

2. 최대한 객체를 최대한 잘게 쪼갰습니다. 
그러다보니 HttpRequest, 연관된 객체들을 보면 by-pass성 메서드가 너무 많은 것 같아요.
이런 메서드들이 많아도 괜찮을지 걱정입니다.

3. 추상 클래스의 네임에 abstract이 들어가도 될까요?
controller 패키지에 AbstractController라는 추상 클래스가 있어요.
메서드 네임에는 'list', 'map', 'array' 이런 단어가 들어가 안되는 걸로 알고있는데, 클래스 네임에 `abstract`가 있으니 마음은 불편한데 고치기가 쉽지않네요. (인터페이스도 있어서)

세세하게 봐주시면 감사하겠습니다!! 내일 상수처리, 테스트코드 작성 등 작업 하겠습니다!
미리 감사해요 😄

2019-09-22 00:56 UTC, young891221 requested changes
안녕하세요, 리뷰어 하비입니다.
전체적인 구조가 깔끔하고 다음 미션인 어노테이션 활용을 위한 구조(?)가 잡혀 있는듯 보여서 좋았습니다. 👍 
코멘트 달을 부분만 고친다면 확실히 체계가 잡힐 듯 보입니다.
질문 주신 부분 코멘트입니다.

1. parser를 인터페이스를 두고 관리하는 방향은 어떠신가요?(추상화되어 관리되는)
현재도 괜찮지만 parser가 늘어날 수록 관리가 불분명할 듯 하네요.

2. 현재 과정이 객체를 최대한 쪼개는 부분이 포함되니 저는 괜찮아 보입니다ㅎㅎ
(개인적으로 보기도 편했어요)

3. `abstract`가 들어가도 괜찮습니다. 복수 자료구조의 경우 `s`를 마지막에 네이밍하여 관리하는 방향이 좋아보입니다

테스트 부분은 더 추가하신다고 하셔서 따로 보진 않았습니다. 찬찬히 리뷰보시고 반영 부탁드립니다.

2019-09-22 00:56 UTC, young891221 commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
`Function<HttpRequest, HttpResponse>`을 value로 선정하신점 훌륭합니다. 💯 
다만, `AbstractController`로 `doGet, doPost, doPut, doDelete`를 기본 뼈대로 잡고 구현하는 방식에는 몇 가지 한계점이 보입니다. 하위 클래스에는 불필요하게 사용 안되는 method를 오버라이드하고 있습니다. 이보다는 발상을 조금 더 전환하여...
`methodFinder`의 키값을 `<HttpMethod+URL>`이 결합된 형태로 하면 어떨까요? 제 생각에는 불필요한 메서드 구현 부분은 사라지고 더 정확한 키값으로 판별해 질 수 있을 것입니다. 또, 2댑스로 객체 레이어가 나뉜 부분들이 더 심플하게 개선될 듯 보입니다.

2019-09-22 00:56 UTC, young891221 commented on src/main/java/controller/ControllerFinder.java
> +        if (isInvalidUri(uri)) {
이런식의 url 유무의 체크는 `ResourceController`뿐만이 아니라 다양한 컨트롤러를 추가할 때 한계점이 있어 보입니다. 유연하지 못한 구조 같습니다. 이보다는 특정 url 패턴을 감지해서 `ResourceController`를 타도록 하는 방향으로 전환하면 어떨까요?

2019-09-22 00:56 UTC, young891221 commented on src/main/java/controller/UserController.java
> +public class UserController extends AbstractController {
이렇게 처리되면 `UserController `의 POST 방식 컨트롤러 메서드가 여러개 추가되면 분기 처리되어야 합니다. 위에서 설명한 구조로 고민해 주세요ㅎㅎ

2019-09-22 11:08 UTC, Conatuseus commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
말해주신 대로 고쳐봤습니다.
그렇게 했더니 구조가 간결하면서도 조금은 익숙하지 않은 상태가 된 것 같아요.

 제가 수정한 것을 보면, 
먼저 Controller Interface가 전혀 필요 없어 보이는데 어떻게 생각하시나요?
그리고 IndexController, ResourceController, UserCreateController가 Controllers를 상속할 이유가 없더라구요.
변경한 부분 잘 확인해주시면 감사하겠습니다! 깔끔하게 완성하고 싶어요!!

2019-09-22 11:09 UTC, Conatuseus commented on src/main/java/controller/ControllerFinder.java
> +        if (isInvalidUri(uri)) {
패턴을 사용하도록 변경했습니다. 👍

2019-09-22 11:14 UTC, Conatuseus commented
리뷰 감사합니다! 💯 
테스트 코드 작성, 리팩토링 등의 작업 중에 질문이 생겼습니다.

1. RequestBody 를 map으로 관리하는게 맞는건가요?

현재 RequestBody를 map 자료구조를 사용해서 관리하고 있어요.
처음에 QueryString만 들어온다고 생각해서 map을 사용했는데 
어떻게 생각하시나요?

2. HttpResponse가 abstract class이고 각 Response들이 상속하는 구조인데 이것은 문제가 없는가요?

3. Controllers 클래스를 테스트를 하고싶은데 service 메서드의 parameter에 HttpRequest가 있어서 힘든 것 같다. 이 부분을 테스트 할 방법이 없을까요?

감사합니다!! 😄

2019-09-23 00:39 UTC, young891221 commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
아 제가 의미를 제대로 전달 못한것 같네요. 조금 더 자세히 설명드리겠습니다.
`Controller`에는 지금의 `Controllers`에서 Map의 key과 같은 역할을 해주는 `isMapping()` 메서드가 추가되면 현재 구조에서 각각의 컨트롤러가 독립적인 역할을 수행하게 됩니다. 즉, `isMapping()`이 특정 룰에 대해서 매칭이 되는지를 확인하고 매칭이 된다면 `Service()` 메서드를 수행하게 됩니다. 이를 보통은 '전략 패턴'이라 칭합니다. 전략 패턴으로 처리하게 되면 `Controller` 인터페이스를 추상화 단계에서 이를 적극적으로 활용하게 됩니다.
기존의 `Map`으로 처리되던 부분들도 `List`로 관리하여 처리 가능합니다.

```java
   private List<Controller> controllers;

   controllers.stream()
   .isFilter(c -> c.isMapping(reqeust))
   ...
```

2019-09-23 00:39 UTC, young891221 commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
이런식으로 처리한다면 더 이상 개별적으로 `doGet, doPost, doPut, doDelete`로 생성할 필요도 없으며 인터페이스를 적극적으로 활용하게 됩니다.

2019-09-23 00:41 UTC, young891221 requested changes
수정하시느라 고생하셨습니다.
구조에 관해 하나 짚고갈 부분이 있어서 리뷰 확인해 주시고 반영 부탁드립니다~!

2019-09-24 06:37 UTC, Conatuseus commented
일단 말씀해주신 대로 고쳐봤는데, 맞는지 잘 모르겠네요.
오래 고민했더니 헷갈리네요 ㅎㅎ
코드 부족한 부분이나 고쳤으면 하는 부분 있으면 더 말씀해주시면 감사드려요!
😄

2019-09-24 08:26 UTC, Conatuseus commented
쓰레드풀 적용,   
UriExtension에서 contains로 확장자를 찾기 -> split해서 마지막 확장자 확인으로 변경했습니다.

2019-09-24 10:54 UTC, young891221 approved these changes
코나스 수고하셨습니다!
제가 의견드린데로 개선해 주셔서 감사합니다. 👍 
다음 미션 진행해 주세요!

2019-09-24 10:55 UTC, merged