[웹 서버 Step-1] 지노 미션 제출합니다.
woowacourse/jwp-was pull request #38
Opened 2019-09-22 08:22 UTC by hyunssooo

안녕하세요 써머! 지노입니다! 

아직 코드에 마음에 안드는 부분이 많지만 더 리뷰요청이 더 늦어지면 안될거 같아 리뷰 요청 합니다 ㅠㅠㅠ
http의 이해도가 많이 낮아 코드를 작성하면서 이게 맞는지 잘 모르는 부분이 많았습니다.
많이 부족한 코드지만 잘 부탁드립니다! :)

2019-09-22 16:04 UTC, phs1116 requested changes
안녕하세요 지노! 리뷰어 화투입니다.
전체적으로 매우 잘 구현하셨어요. 👍 
다만 각 객체가 너무 많은 책임을 가지고 있거나 책임이 명확하지 않은 점
Request, Response의 역할이 명확하지 않은 점이 있어 관련하여 피드백 추가했습니다.
확인 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +
지원하지 않은 요청에 대해서는 예외를 던지는게 맞지 않을까요? :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +        Arrays.stream(tokens)
컨트롤러가 queryString에 대해서 직접 파싱을 하고 있는데요. 
WAS에서 해줘야할 역할을 비즈니스에서 처리하고 있는 것 같습니다.
실제 서블릿 스펙에서는 HttpRequest에서 파싱하여 제공해주고 있습니다.
HttpRequest 생성시에 파싱을 하고, `httpRequest.getParameter(key)` 형태로 가져올 수 있도록 구현해보면 어떨까요?

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/controller/FileController.java
> +    public static FileController getInstance() {
싱글톤으로 관리할 필요가 있나요?
싱글톤으로 구현하지 않아도 WAS에서 싱글 인스턴스로 관리가 될 것 같은데요. :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/controller/FileController.java
> +            logger.error(e.getMessage());
예외 상황에 대해서는 로그만 찍고 무시하는 것이 아닌,
적합한 statusCode로 resposne를 주면 어떨까요?

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/http/request/HttpRequest.java
> +            this.httpRequestBody = new HttpRequestBody(lines.subList(getToIndex(lines) + 1, lines.size()));
ServletReqeust 스펙에 맞춰 HttpRequest 스펙을 수정해보면 어떨까요?
body의 경우 그저 String list로 오는 것이 아닌, form, json이면 이에 맞춰 파라미터로 제공하는 형식이 될 수 있을것 같아요. :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/http/request/HttpRequestLine.java
> +    private String uri;
자바에 URI와 같은 클래스들도 있는데요,  
이처럼 uri 내에 queryString, path 등 여러가지 구성으로 이루어진 클래스로 작성 할 수 있을것 같습니다. :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +        this.httpStatusLine = new HttpStatusLine("HTTP/1.1 302 FOUND \r\n");
httpResponse는 외부 메시지를 통한 파싱을 할 필요가 없는데 굳이 
문자열 파싱 -> Response를 위한 다시 문자열 생성을 반복할 필요가 있을까요?
또한 HttpVersion도 1.1로 강제하는게 맞는지도 고민이 좀 필요할 듯 해요. :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/webserver/RequestHandler.java
> +        controllers.put("/user/create", CreateUserController.getInstance());
어차피 RequestHandler를 통해 관리가 되는데 싱글톤이 필요한지 고민해보면 좋을 것 같아요.
RequestHandler를 통한 싱글 인스턴스 관리로 충분하지 않을까요?

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/webserver/RequestHandler.java
> +            dataOutputStream.writeBytes(httpResponse.getHttpStatusLine().toString());
Request를 생성할때 inputStream을 전달하듯이,
Response를 전달할 때 outputStream을 전달받아 처리하는 책임을 분리해보면 어떨까요?
현재로서는 HttpResponse가 outputStream을 직접 전달 받아서 처리할 수 있을 것 같아요.

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/webserver/RequestHandler.java
> +            if (httpRequest.isContainExtension()) {
현재 이 객체에서 상당히 많은 역할을 하고 있는 것 같아요.
컨트롤러에 대해서 Dispatch하는 책임또한 분리 할 수 있을 것 같아요.

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +    public void send200Ok(String uri) throws IOException, URISyntaxException {
현재 httpStatus를 설정하는 메서드가 전부 send로 명명되어있는데 현재는 값만 설정하는것이므로 적합한 네이밍이 아닐 것 같아요.
또한 현재 이 메서드에서는 전달받은 경로에 대해서 파일을 가져와 body에 저장하는 역할 까지 하고있는데 너무 많은 역할을 하고 있는 것 같습니다.  (FileController에서 책임질 역할까지 전부 책임지고 있어보여요 . :))
HttpResponse는 그저 전달받은 응답값을 설정하는 용도로만 사용하면 어떨까요?
body로 저장될 데이터들 (파일을 읽는 등)은 외부에서 처리하고, 여기서는 Response는 body만 전달 받을 수 있을 것 같아요.

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/http/request/HttpRequestHeader.java
> +        if (fields.containsKey("Content-Length")) {
보편적인 헤더는 상수로 관리할 수 있지 않을까요? :)

2019-09-22 16:04 UTC, phs1116 commented on src/main/java/webserver/RequestHandler.java
> +                controllers.get(httpRequest.getUri()).service(httpRequest, httpResponse);
현재 없는 URI로 요청시 NPE가 발생할 것 같아요.
컨트롤러를 핸들링해주는 별도 클래스에서 존재하는 요청시에 알맞은 status code로 내려주는게 더 적합하지 않을까요? (404 등)

2019-09-24 15:51 UTC, hyunssooo commented
안녕하세요 화투! 지노입니다! 
제 나름대로 고민한다고 고민해봤는데 많이 부족한거 같아요 ㅠㅠ 고민의 시간이 길어져 피드백 반영이 많이 늦어 졌습니다. 죄송합니다.
그래도 잘 부탁드립니다! :)

2019-09-25 13:03 UTC, phs1116 approved these changes
안녕하세요!  리뷰어 화투입니다.
피드백 반영하시느라 고생 많으셨어요!
몇가지 피드백 추가했는데 다음 단계 진행하시면서 개선해보면 좋을 것 같습니다. :)
궁금하신 점 있으시면 연락주세요!

2019-09-25 13:03 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +            httpResponseStatusLine = new HttpResponseStatusLine(httpRequest.getHttpVersion(), HttpStatusCode.of("302"));
사용하는 측에서 상세 코드를 알고 사용하기보단 enum을 직접 활용하는게 좋지 않을까요?
혹은 조금 더 명확하게 response.redirect(url) 형태로 표현할 수 있을 것 같아요. :)
httpRequest.getHttpVersion()는 Respones 생성시기에 Request를 기반으로 생성하는게 더 좋을 것 같아요. :)

2019-09-25 13:03 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +        httpResponse.setHttpResponseStatusLine(httpResponseStatusLine);
httpResponse는 통신 표준이지 Controller에서 너무 상세하게 알고가지 않아도 될 것 같습니다. :)

2019-09-25 13:03 UTC, phs1116 commented on src/main/java/controller/FileController.java
> +
지원하지 않은 메서드일시 예외를 던지는게 더 명확할 것 같아요. :)

2019-09-25 13:03 UTC, phs1116 commented on src/main/java/http/request/Resource.java
> +    private String path;
모든 요청의 타겟이 파일이라는 리소스를 대상으로 하는것처럼 보여요.
이보다는 URL 스펙에 맞춰 구현해보면 어떨까요?

2019-09-25 13:03 UTC, merged