[웹 서버 Step-1] 도넛 미션 제출합니다.
woowacourse/jwp-was pull request #44
Opened 2019-09-23 09:58 UTC by codeanddonuts

덜 구현한 부분은 계속 올리도록 하겠습니다 감사합니다.

2019-09-24 10:26 UTC, young891221 requested changes
안녕하세요, 도넛 리뷰어 하비입니다.
이번 미션에서는 웹 서버 구현인데 함수형 언어까지 공부하셨군요... 👍 
거의 라이브러리급으로 개발하셔서 놀랐습니다.
개인적으로는 심플한 구조를 더 어렵게 만든 부분이 있어서 몇 가지 코멘트 드렸습니다. 확인 부탁드립니다~!

2019-09-24 10:26 UTC, young891221 commented on src/main/resources/router-config.json
> +    "/test/{num}" : {
json을 이용하여 이런식의 테스트 괜찮네요. 👍

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/router/Router.java
> +            try {
이와 같은 구현은 컨트롤러의 네이밍에 종속적인 구현입니다. 항상 네이밍을 신경써서 개발해야 되는 문제점이 생기는 것이지요.
컨트롤러의 구현체의 네이밍과 별게로 HttpMethod & URL에 맵핑되는 방식으로 라우팅하는 방식으로 변경하면 어떨까요?

2019-09-24 10:26 UTC, young891221 commented on src/main/java/controller/IndexController.java
> +public class IndexController {
저는 이번 미션에서 Controller의 추상화가 핵심이라 생각합니다.
그런 의미에서 `IndexController`, `UserController`를 의미있게 추상화시켜주는 인터페이스를 구현해 보세요.
인터페이스로 추상화 단계가 올라간다면 응집도 + 반복적인 코드를 줄일 수 있는 방법으로 변경이 가능합니다.

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/http/HttpContentType.java
> +    private static final Map<String, HttpContentType> CACHE = new HashMap<>();
상당히 많은 타입을 구현하셨네요...

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/http/HttpRequest.java
> +        return (startLine.length != 3)
스칼라같은 함수형을 선호하시나 보네요.
이 과정이 자바라 안타깝군요 ㅠㅠ
자바니까 객체지향적인 방향으로 가야 반복되는 코드를 줄이고 가독성, 확장성을 높일 수 있습니다.
현재의 문제점은 다음정도라고 생각합니다.
 - 추가되는 HttpMethod에 대한 모든 분기처리가 필요하다.
 - 소스의 분리가 되지 않아 결합도가 크다.

분리와 추상화를 통해 개선해 보면 어떨까요?

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/http/HttpStatusCode.java
> +public enum HttpStatusCode {
와우 💯

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/http/HttpStatusCode.java
> +    public String toName() {
이런 방식으로 switch문을 사용하는건 enum을 적극적으로 활용하지 못하는 것 같습니다.
`String explain`과 같은 필드를 선언하여 처리하면 어떨까요?

2019-09-24 10:26 UTC, young891221 commented on src/main/java/webserver/router/Router.java
> +        switch (extension) {
`HttpContentType`에 필드가 하나 더 생성되면 반복문이 없어질 듯 합니다.

2019-09-25 08:39 UTC, codeanddonuts commented on src/main/java/webserver/router/Router.java
> +        switch (extension) {
파일의 확장자에 아무 관계 없이 어떤 응답을 줄지는 라우터의 영역이라고 생각했는데, 제가 다소 일관되지 못하고 급진적이었던 것 같습니다..

2019-09-25 08:47 UTC, codeanddonuts commented on src/main/java/webserver/router/Router.java
> +            try {
스프링을 처음 배우면서 @RequestMapping을 굉장히 편리하다고 생각하여 어노테이션 처리기를 만들어보려 하였으나, 처음에 작성할 때는 편해 보여도 프로젝트의 크기가 커지면 모든 라우팅 패스를 파악하기 위하여는 컨트롤러 코드를 전부 열어봐야할 것이라는 생각이 들어 하나의 설정 파일로 구현하였습니다. 설정 파일에서 존재하지 않는 컨트롤러 클래스 및 메소드 이름을 잘못 작성한 경우 예외가 발생하여 서버 구동을 막도록 하였는데 어떻게 생각하시나요? 제가 어노테이션을 만들어본 적이 없어서 생각을 못하였는데 다른 크루들과 이야기를 나눠본 결과 서버를 켤 때마다 어노테이션 처리기에서 하나의 파일에 모든 라우팅 패스를 적어주도록 만들어볼 수도 있을 것 같긴 합니다. 절대 JSON 파서를 한 번 만들어보고 싶어서 이렇게 한 것이 아닙니다 ..

2019-09-25 12:20 UTC, young891221 commented on src/main/java/webserver/router/Router.java
> +            try {
자신이 경험한 문제에 대해 더 나은 방향으로 접근하려는 마음을 칭찬드리고 싶네요ㅎㅎ
의견 주신 부분처럼 잘못 작성한 경우 예외 발생, 어노테이션 처리까지 되면 괜찮겠네요.
다만, 한눈에 json으로 파악할 수 있는 장점과 함께 번거롭게(?) json을 작성해야 하는 단점도 생기는 것 같습니다. 좀 더 고도화해서...문제가 되는 포인트가 라우팅 패스를 모두 파악하기 위해 코드를 모두 열어봐야 된다는 것이라면 처음 어플리케이션이 기동할 때 작성한 컨트롤러를 불러와 json or tree 형태로 파일을 떨궈주는 것은 어떨까요??ㅎㅎ (너무 번거로울까요)

2019-09-25 12:20 UTC, young891221 commented on src/main/java/webserver/router/Router.java
> +        switch (extension) {
음...그런의미와 별게로 enum을 사용하면서 if, switch문을 굳이 사용할 이유가 없어서 코멘트 드린 부분입니다ㅎ

2019-09-25 12:26 UTC, young891221 requested changes
리펙토링하느라 고생하셨습니다.
코드만 본다면 함수형을 격하게 지향하고 계신듯 하네요ㅎㅎ
때문에 복잡하지 않을 수 있는 부분이 복잡해 지는 부분이 몇 존재합니다.
제가 코멘트 드린 부분중에 `controller`의 인터페이스화와 함께 몇 가지 리뷰를 수행하면서 객체지향적인 코드와
융화되게 바꿔보면 어떨까요?? 리뷰주신 부분에 대한 의견은 언제나 환영입니다:)

2019-09-26 09:59 UTC, codeanddonuts commented
> 리펙토링하느라 고생하셨습니다.
> 코드만 본다면 함수형을 격하게 지향하고 계신듯 하네요ㅎㅎ
> 때문에 복잡하지 않을 수 있는 부분이 복잡해 지는 부분이 몇 존재합니다.
> 제가 코멘트 드린 부분중에 `controller`의 인터페이스화와 함께 몇 가지 리뷰를 수행하면서 객체지향적인 코드와
> 융화되게 바꿔보면 어떨까요?? 리뷰주신 부분에 대한 의견은 언제나 환영입니다:)

제가 컨트롤러에서 사용하는 메소드를 가진 베이스 컨트롤러를 만들었는데 인터페이스화 하라는 게 다른 의미인 것 같은데 잘 이해를 못하겠어서 구체적으로 좀 알려주실 수 있나요? 만약 인터페이스화하면 어떤 식으로 사용되게 완성되는 것인지 잘 모르겠습니다. 이후 의존성 주입과 관련된 부분인가요?

2019-09-27 00:39 UTC, young891221 commented
> > 리펙토링하느라 고생하셨습니다.
> > 코드만 본다면 함수형을 격하게 지향하고 계신듯 하네요ㅎㅎ
> > 때문에 복잡하지 않을 수 있는 부분이 복잡해 지는 부분이 몇 존재합니다.
> > 제가 코멘트 드린 부분중에 `controller`의 인터페이스화와 함께 몇 가지 리뷰를 수행하면서 객체지향적인 코드와
> > 융화되게 바꿔보면 어떨까요?? 리뷰주신 부분에 대한 의견은 언제나 환영입니다:)
> 
> 제가 컨트롤러에서 사용하는 메소드를 가진 베이스 컨트롤러를 만들었는데 인터페이스화 하라는 게 다른 의미인 것 같은데 잘 이해를 못하겠어서 구체적으로 좀 알려주실 수 있나요? 만약 인터페이스화하면 어떤 식으로 사용되게 완성되는 것인지 잘 모르겠습니다. 이후 의존성 주입과 관련된 부분인가요?

컨트롤러의 주 역할에 대해 생각해 볼까요? 컨트롤러는 특정한 HttpMethod, Path 기반으로 해당하는 메서드를 타서 결과값을 반환합니다. 그럼 여기서 2개 정도의 메서드를 뽑을 수 있겠네요.
1. HttpMethod + Path 기반의 맵핑 메서드
2. HttpMethod + Path에 해당하는 로직 메서드

아래와 같은 예제를 의미합니다. 
```java
public class Controller {
   boolean isMapping(RequestMapping requestMappin);
   void logicMapping(HttpRequest request, HttpResponse response);
}
```

이런식의 구조로 코드를 추상화하여 관리한다면 몇 가지 장점이 생깁니다.(한번 생각해 보세요.)
다만, 이러한 구조는 `Controller` 하나가 하나의 로직만을 담당한다라는 한계가 있긴 합니다. 이 부분도 고도화할 수 있는데요. 그건 다음 어노테이션 미션때 진행하면 될 것 같습니다ㅎㅎ

2019-09-27 00:40 UTC, young891221 requested changes
고생하셨습니다. 도넛!
컨트롤러 인터페이스 생성하여 관리하는 매커니즘까지만
추가로 작성하고 다음 단계 진행하는게 좋을것 같습니다. 다음 PR 기다릴게요~!

2019-09-30 09:23 UTC, closed without merging