Feat step2
woowacourse/jwp-was pull request #48
Opened 2019-09-24 08:17 UTC by jinwookh

2019-09-25 15:22 UTC, kingbbode requested changes
구현 잘 하셨네요 :)
몇 가지 피드백 작성하였습니다.

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/controller/AbstractController.java
이 클래스가 정말 추상화되어 제공되어야 할까요?

저는 아래 doGet 과 doPost 를 사용하는 측에서 반드시 구현해야 한다고 생각하지 않아요. 구현을 한다면 이 클래스를 상속하여 어떠한 메서드를 재구현하면 된다는 것을 사용자에게 안내하고, 오버라이드 되지 않은 메서드는 구현이 되지 않았으니 기본적으로 405 에러를 반환하도록 하는게 웹서버로서 옳바른 설계가 아닐까요?

우리는 어떠한 구조를 만들 때 인터페이스나 추상화 클래스를 두어 구현을 강제화해야 사용자에게 친절하고 명확할 것이라고 생각을 하고 어쩌면 그러한 고정관념을 가지고 있을 수도 있습니다 :) (제가 그랬어서 적어봅니다 ㅎㅎ)

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/controller/UserListController.java
> +        if (session != null && session.getAttributes("login-user") != null) {
Method 로 분리하여 의도를 명확히 해보는 것은 어떨까요?

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/controller/UserLoginController.java
> +            response.addHeader(HTTP.SET_COOKIE, httpSession.getId());
세션을 생성하는 일이 어플리케이션에서 할 일일까요?

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/http/request/RequestFirstLine.java
> -    private static final Logger log = LoggerFactory.getLogger(RequestFirstLine.class);
이 클래스 네이밍이 갖는 의미를 표준적으로 사용하는 명칭이 있네요.
https://tools.ietf.org/html/rfc2616#section-5.1

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/http/response/view/DefaultView.java
> +        logger.info("response body : {}", body);
실제 필요한 로그인가요, 확인을 위한 로그인가요?
확인을 위한거라면 적절한 로그 레벨로 작성되면 좋겠네요.

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/service/UserService.java
> +        if (user == null || !user.getPassword().equals(password)) {
User에게 물어보는 것은 어떤가요?

2019-09-25 15:22 UTC, kingbbode commented on src/main/java/webserver/RequestHandler.java
> +        Optional<AbstractController> maybeController = ControllerContainer.findController(httpRequest.getPath());
Optional 을 버리면 더 깔끔한 코드가 될 것 같아요.

2019-09-27 06:36 UTC, jinwookh commented on src/main/java/http/response/view/DefaultView.java
> +        logger.info("response body : {}", body);
에러 로그와 warining log 가 필요한 로그 이고, info log가 확인을 위한 로그라고 생각합니다. 혹시 현업에서는 확인을 위한 로그로 무엇을 쓰는지 알 수 있을까요?

2019-09-27 07:34 UTC, jinwookh commented on src/main/java/controller/AbstractController.java
interface를 사용하여, 유저에게 doGet과 doPost 메서드를 작성하도록 강제하고 싶었습니다. 하지만 유저 입장에서 봤을 때, 유저에게 필요없는 http 메서드는 작성하지 않도록 하는게 더 편할 것 같습니다. AbstractController에서 doGet과 doPost는 405를 반환하도록 수정했습니다.

2019-09-27 07:34 UTC, jinwookh commented on src/main/java/controller/UserListController.java
> +        if (session != null && session.getAttributes("login-user") != null) {
넵 분리했습니다!

2019-09-27 07:37 UTC, jinwookh commented on src/main/java/controller/UserLoginController.java
> +            response.addHeader(HTTP.SET_COOKIE, httpSession.getId());
```java
HttpSession httpSession = HttpSessionDB.getInstance().findOrCreateSession(request.getCookieValue(SESSION_ID));
```
세션 생성하는 코드를 위 코드로 수정했습니다.

2019-09-27 07:40 UTC, jinwookh commented on src/main/java/http/request/RequestFirstLine.java
> -    private static final Logger log = LoggerFactory.getLogger(RequestFirstLine.class);
RequestFirstLine -> RequestLine,
ResponseFirstLine -> StatusLine으로 수정했습니다.

2019-09-27 07:40 UTC, jinwookh commented on src/main/java/service/UserService.java
> +        if (user == null || !user.getPassword().equals(password)) {
넵!

2019-09-27 07:40 UTC, jinwookh commented on src/main/java/webserver/RequestHandler.java
> +        Optional<AbstractController> maybeController = ControllerContainer.findController(httpRequest.getPath());
넵 수정했습니다.

2019-09-28 03:18 UTC, woowahankingbbode commented
`SESSION_ID` 의 존재를 유저가 알아야할까요?
현재의 구현은 사용자의 입장에서 Session을 사용하기가 불편해보이네요.
세션은 구현체에 따라 다르게 동작할 수 있어요. 예를 들면 Redis Session, Jdbc Session 등의 구현체를 갖을 수도 있지요. 사용자가 세션의 구현을 알고 의도에 맞게 SESSION ID를  사용하도록 하는 것은 좋지 않은 사용성일 듯 해요.

구현체가 변경되어도 사용자가 세션을 사용하는 사용성은 변경되지 않도록 수정해보는 것은 어떨까요?

2019-09-28 03:21 UTC, kingbbode requested changes
안녕하세요 올레!
피드백도 잘 반영해주셨고, 구현도 잘 해주셨네요 감사합니다!
세션에 대한 마지막 피드백 드렸습니다. 코멘트 확인 부탁드려요 :)

2019-09-28 07:00 UTC, jinwookh commented
안녕하세요 킹뽀대님, 피드백 반영하여 올렸습니다.

유저 입장에서 봤을 때, 세션 id를 몰라도 세션을 쓸 수 있는게 더 편할 것 같습니다.
컨트롤러에서 session_id를 사용하는 부분을 모두 httpRequest 또는 httpCookie로 옮겼습니다.
그 밖에 피드백 할 사항이 있다면, 알려주셔도 됩니다! 감사합니다.

2019-09-28 09:20 UTC, kingbbode reviewed
다시 한번만 부탁해요!

2019-09-28 09:20 UTC, kingbbode commented on src/main/java/http/request/HttpRequest.java
> +    public HttpSession getSession(HttpSessionManager httpSessionManager) {
HttpSessionManager 구현체가 만약 쿠키를 사용하지 않는다면 어떻게 될까요? 혹은 쿠키를 더 복잡한 방법으로 사용한다면 어떻게 될까요?
HttpRequest 가 HttpSessionManager 구현체의 동작을 알야할까요? HttpSessionManager 의 인터페이스를 만든다면 무엇을 인자로 받는 것이 좋을지도 한번 더 고민해보시면 좋을 것 같습니다 :)

2019-09-28 09:20 UTC, kingbbode commented on src/main/java/controller/UserLoginController.java
> +    private void setSessionToCookie(HttpResponse response, HttpSession httpSession) {
session 쿠키의 기록을 이제 framework에게 맡겨볼 수 있지 않을까요?

2019-09-28 09:20 UTC, kingbbode commented on src/main/java/http/HttpCookie.java
> +    public HttpCookie(HttpSession httpSession) {
HttpCookie 가 HttpSession 을 의존하게 되는 것은 좋지 못한 의존 방향인 것 같아요 :)
세션을 기록하는 구현체의 방법을 HttpCookie 가 알아할까요? 각 객체의 역할과 책임의 경계를 잘 생각해보셨으면 좋겠습니다.

2019-09-30 03:13 UTC, kingbbode approved these changes
고생 많으셨어요. 리뷰 하면서 즐거웠습니다.
머지할게요 :)

2019-09-30 03:14 UTC, merged