Feat step1
woowacourse/jwp-was pull request #5
Opened 2019-09-19 09:44 UTC by jinwookh

2019-09-20 12:26 UTC, woowahankingbbode requested changes
안녕하세요! 리뷰가 늦었습니다 ㅜㅜ 
피드백 몇가지 남겼습니다 :) 
확인 부탁드려요.

2019-09-20 12:26 UTC, woowahankingbbode commented on build.gradle
> +    implementation 'org.mockito:mockito-core:1.+'
mockito-core 가 implementation 되는 것이 무엇을 위한 것인가요?

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/controller/AbstractController.java
> +        if (request.getMethod().equals(RequestMethod.GET)) {
존재할 가능성이 큰? 것으로부터 equals 비교하는 습관을 가지면 좋겠네요 :)

```
a.equals("a")  (X)
"a".equals(a)  (O)
```

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/controller/AbstractController.java
> +        if (request.getMethod().equals(RequestMethod.GET)) {
ENUM 은 "==" 비교만으로도 충분합니다

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/webserver/ControllerContainer.java
> +        Optional<AbstractController> maybeController = findController(httpRequest.getPath());
Optional 을 통해 얻을 수 있는 이득이 없어보이네요. Map이 가지고 있는 API만으로도 충분히 처리할 수 있지 않을까요?

2019-09-20 12:26 UTC, woowahankingbbode commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
테스트를 검증 기준으로 분리한 이유가 궁금하네요!

동일 조건 동일 행위를 하나의 테스트에서 여러가지 검증 조건을 가지고 있다면 좋을 것 같아요. 검증을 기준으로 테스트를 분리하였을 경우 오히려 문제를 찾기 더 어려워질 가능성이 크고, 매번 번거로운 중복 작업을 하게 될 가능성이 크다고 생각해요 :)

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/model/User.java
> +    public static User fromMap(Map<String, String> info) throws IllegalAccessException {
Map 에서 값을 꺼내어 User 객체를 생성하는 것과 비교하여 아래 코드는 어떤 장점을 갖나요?

리플렉션은 무엇이든 할 수 있도록 해주지만 아래와 같은 상황에 사용되는 것은 과용이라고 생각해요 :)
사용자에게 편의를 제공해야하는 프레임워크나 라이브러리 영역에서는 사용하기도 하지만, 요구사항이 쉽게 변경될 수 있는 어플리케이션 영역에서는 무엇이든 해주는 코드를 만들기보단 누구든지 변경할 수 있는 코드를 만들었으면 합니다.

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/utils/FileIoUtils.java
> +        if (!optionalURL.isPresent()) {
Optional 의 isPresent -> get 사용하면서 얻을 수 있는 이득이 있을까요?

isPresent -> get 으로 이어지는 패턴을 옵셔널의 안티 패턴으로 분류하기도 한답니다.

https://dzone.com/articles/optional-ispresent-is-bad-for-you

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/controller/UserCreateController.java
> +            log.error(e.getMessage());
전체적으로 예외에 대한 처리가 아쉽네요. 예외가 발생했을 때 Client 에게 어떤 응답을 돌려주어야 하는지 생각해보면 좋을 것 같습니다.

2019-09-20 12:26 UTC, woowahankingbbode commented on src/main/java/http/request/RequestHeader.java
> +        System.out.println(headerContents.getOrDefault(key, ""));
sysout 은 사용하지 않는 습관을 들이는 것이 좋습니다 ㅎㅎ

2019-09-20 13:40 UTC, jinwookh commented on src/main/java/http/request/RequestHeader.java
> +        System.out.println(headerContents.getOrDefault(key, ""));
넵!

2019-09-20 13:41 UTC, jinwookh commented on build.gradle
> +    implementation 'org.mockito:mockito-core:1.+'
현재로서는 들어갈 아무 이유가 없습니다. 적용할까 말까 고민했던 흔적입니다 ㅠㅠ 지웠습니다!

2019-09-20 13:44 UTC, jinwookh commented on src/main/java/controller/AbstractController.java
> +        if (request.getMethod().equals(RequestMethod.GET)) {
넵 확인했습니다!

2019-09-21 06:49 UTC, jinwookh commented on src/main/java/webserver/ControllerContainer.java
> +        Optional<AbstractController> maybeController = findController(httpRequest.getPath());
map.keySet() 를 사용하는 코드로 수정했습니다!

2019-09-21 07:43 UTC, jinwookh commented on src/main/java/utils/FileIoUtils.java
> +        if (!optionalURL.isPresent()) {
좋은 자료 감사합니다. Optional을 사용해도 가독성면에서 큰 효과가 없을 것 같아, null값을 비교 연산하는 코드로 수정했습니다.

2019-09-22 00:11 UTC, jinwookh commented on src/main/java/controller/UserCreateController.java
> +            log.error(e.getMessage());
넵! 사용자가 존재하지 않는 url로 접속 시, 서버가 404 에러를 리턴하도록 만들었습니다. 후에 400 에러를 리턴하는 로직 등을 추가할 예정입니다.

다만 response 내용을 outstream에 write할 때 생기는 ioexception의 경우, 어떻게 처리해야 할지 아이디어가 떠오르지 않습니다. 현재 ioexception은 log를 띄우는 것 외에 아무 처리를 하고 있지 않습니다. 
더 좋은 방법이 있다면 알려주실 수 있을까요?

2019-09-22 00:25 UTC, jinwookh commented on src/main/java/model/User.java
> +    public static User fromMap(Map<String, String> info) throws IllegalAccessException {
1. 현재 User 객체가 리플렉션 기능을 수행하고 있고, 2. 그렇기 때문에 User 객체가 유연한 코드(누구든지 변경할 수 있는 코드)가 되지 못하고 있다는 말씀으로 이해해도 될까요?

구체적인 예시가 잘 떠오르지 않는데, 누구든지 변경할 수 있는 코드와 그렇지 못한 코드의 예시를 하나씩 들어주시면 감사하겠습니다!

2019-09-22 00:37 UTC, jinwookh commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
테스트를 먼저 작성한 후 기능을 구현하다 보니 검증 기준으로 테스트가 분리된 것 같습니다. 빠르게 기능을 구현하고 싶은 마음에 테스트 안에 있는 검증 개수도 하나가 된 것 같구요! 궁금한 점이 있습니다.

테스트 안에 여러 검증 기준이 있으면 좋다는 말은, 하나의 메서드 안에 여러 개의 assure 메서드가 호출하라는 말씀이신가요?
테스트 메서드 안에 하나의 검증을 가지고 있고, 여러 개의  assure 메서드가 있다면, 문제를 찾기가 더 어려울 것이라고 생각합니다. 예로 들어 get 메서드 검증과 post 메서드 검증이 한 테스트에 묶여 있다면, 이 테스트가 fail이 났을 때 get에서 fail이 났는지, post에서 fail이 났는지  알기 어렵습니다.

권용근 님은 어떻게 생각하시나요?

2019-09-22 01:30 UTC, kingbbode approved these changes
깔끔하네요! 수고하셨습니다 :)
코멘트에 대해 궁금한게 생기시면 계속 이어가도 좋습니다.

2019-09-22 01:30 UTC, kingbbode commented on src/main/java/model/User.java
> +    public static User fromMap(Map<String, String> info) throws IllegalAccessException {
누구든지 변경할 수 있는 코드 == 가장 단순하고 쉽게 작성하는 것
을 의도 했어요 ㅎㅎ

버전 분기든, 새로운 기능이든 어떠한 이유로 요청 파라미터명이 일부 변경되었습니다. 작성하신 코드와 아래 코드 중 어느 것이 변경하기 더 수월할까요?

```
String userId = map.get(“userId”)
String password = map.get(“password”)
String name = map.get(“name”)
String email = map.get(“email”)

return new User(userId, password, name, email);
```

2019-09-22 01:30 UTC, kingbbode commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
예로 들어주신 내용은 get을 수행하느냐 post를 수행하느냐의 행위가 분리되는 것 같네요.  

위에서 말씀드린 내용은 조건과 행위를 기준으로 테스트를 묶을 수 있다는 말 입니다.

“A”라는 조건으로 “ㄱ” 이라는 행위를 수행. 
```
assertThat(actual1).isEqualsTo(expected1)
assertThat(actual2).isEqualsTo(expected2)

---출력--
Expected :expected2
Actual   :actual2
```
말씀하신 "어디에서 실패했는지"는 assure 메서드가 추적하기에 충분한 기능을 제공하고 않을까요?

테스트 초심자들이 테스트를 그만두게 되는 이유 중 큰 몫을 차지하는 것이 변경이 생겼을 때 테스트의 유연함 입니다. 코드가 변경되자 테스트가 모두 깨지는 것을 보고 떠나버리는 것이죠 ㅎㅎ 

현재의 테스트 코드가 그렇습니다.

- “A”라는 조건으로 “ㄱ” 이라는 행위를 수행.  검증 1
- “A”라는 조건으로 “ㄱ” 이라는 행위를 수행.  검증 2
- “A”라는 조건으로 “ㄱ” 이라는 행위를 수행.  검증 3
- “A”라는 조건으로 “ㄱ” 이라는 행위를 수행.  검증 4

조건이나 행위에 대한 변경이 이루어졌을 때 모든 테스트가 변경되어야 합니다. 또한 조건이나 행위의 변경이 모든 테스트를 실패하게 할 가능성이 큽니다. 위와 같은 방법으로 테스트를 작성하는 것은 빠른 피드백과 변경 사이클을 제공해줄 수 없습니다. 우리는 행위를 이루는 설계를 테스트 해야합니다. 행위의 일부 요소를 떨어트려 테스트할 필요는 없다고 보아요. 결국 행위에 대한 변경이 이루어졌을 때는 분리해놓은 모든 테스트가 실패할 가능성이 크니까요.

더 궁금하신 내용도 답글 달아주세요 ㅎㅎ
제가 스프링캠프에서 발표했던 자료인데 아직 영상은 안올라왔네요. 테스트에 대해서 궁금한 것은 이 슬라이드 참고하셔도 좋을 것 같아요. 회사폰트를 사용했더니 전체화면해야지 글씨가 나오네요 ㅜㅜ 
https://www.slideshare.net/ssuser59a869/ksug-2019

2019-09-22 01:30 UTC, kingbbode commented on src/main/java/controller/UserCreateController.java
> +            log.error(e.getMessage());
5xx 대역의 상태 코드를 사용하면 되지 않을까요? :)

2019-09-22 01:30 UTC, merged

2019-09-22 02:14 UTC, kingbbode commented
예외처리에 대해 참고하시면 좋습니다 :)
https://www.slipp.net/questions/350

2019-09-22 13:12 UTC, jinwookh commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
권용근 님, 발표 자료 모두 읽었습니다. 자료 감사합니다.
두 가지 질문이 있습니다.
1. 행위를 테스트하는 것과 설계를 테스트하는 것의 차이는 무엇인가요? 
제가 이해한 바로는, 검증을 기준으로 테스트를 만드는 건 곧 행위를 기준으로 테스트를 만드는 것과 같습니다. 그리고 행위를 기준으로 테스트를 만드는 일은 불필요한 리팩토링을 발생시키기 때문에 지양해야 합니다. 그리고 행위를 테스트하기보다는, 설계를 테스트해야 합니다.
하지만 설계를 테스트한다는 말을 아직 이해하지 못했습니다.

로또 미션을 예로 들겠습니다.
6개의 숫자를 반환해야 한다는 조건을 테스트하려고 한다면, 이건 곧 6개의 숫자를 반환하는 '행위'를 테스트하는 일 아닌가요? 설계를 테스트한다고 하면 '6개의 숫자를 반환한다'는 테스트를 어떻게 해석해야 하는지 궁금합니다.

2. 구현에 종속적이지 않은 테스트를 만드는 게 가능한가요?
발표 자료에서는 구현을 테스트하지 말고 설계를 테스트하라고 적혀 있었습니다. 하지만 테스트 코드에는 어떤 형식으로든 '구현'이 들어가 있을텐데, 어떻게 테스트를 '구현' 종속적으로 만들지 않을 수 있는지 궁금합니다.
제가 쓴 코드를 예시로 들겠습니다.
```java
@Test
    void InputStream_GET_확인() throws IOException {
        String request = "GET /index.html HTTP/1.1\nHost: localhost:8080\nConnection: keep-alive\nAccept: */*";

        InputStream in = new ByteArrayInputStream(request.getBytes());
        HttpRequest httpRequest = new HttpRequest(in);

        assertThat(httpRequest.getMethod()).isEqualTo(RequestMethod.GET);
    }
```
위 코드에서 저는 http header에서 메서드를 파싱하는 '설계'를 테스트하고 싶었습니다. 하지만 설계에 대한 테스트 코드를 만들 때, 'httpRequest라는 클래스가 필요하고, httpRequest에는 inputstream 매개변수가 필요하겠구나..'라는 구현에 대한 고려를 자연스럽게 하게 되었습니다.(구현에 앞서 테스트를 먼저 짰습니다.) 결국 생각한 '구현'대로 테스트 코드를 짰고, 테스트 코드는 제가 생각한 '구현'에 종속적이게 되었습니다. 구현에 유연하게 대응할 수 있는 테스트 코드를 짤 수 있는 방법이 있다면, 그 방법이 무엇이지 궁금합니다.

2019-09-22 13:18 UTC, jinwookh commented on src/main/java/model/User.java
> +    public static User fromMap(Map<String, String> info) throws IllegalAccessException {
제가 코드를 쓰는 클라이언트라고 생각해 보았을 때, 위와 같이 설계되어 있는 코드가 더 좋을 것 같아요!

2019-09-22 14:02 UTC, woowahankingbbode commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
크으 질문 감사합니다 :)

1. 일단 지금 서로 다른 2개의 개념이 같이 이야기되고 있는 듯 하여 정리하겠습니다. 설계를 테스트해야한다는 내용과 위에서 드린 피드백은 별게의 내용입니다 :)  위에서 드린 피드백을 요약하면 간단합니다. 동일한 조건과 동일한 행위를 수행하는 테스트를 여러개 나열하여 작성된 테스트가 과연 의미가 있는가 입니다. 저는 그에 대한 잃게 되는 것을 말씀드리고 싶었습니다 :)
설계를 테스트할 때 당연히 행위를 기반으로 검증을 하겠지요. 행위는 테스트한다는 것이 반드시 구현을 테스트하는 것은 아닙니다 :)

2. 당연히 가능하고, 그러기 위해 노력해야 합니다 :) 
위에서 말씀하신 inputstream 을 사용하게 된 것은 구현이라기 보다는 값을 입력받기 위한 조건이며, 결국 Http 요청 스팩을 받아서 HttpRequest 안에 정보를 잘 저장한다는 설계를 구현한 것으로 보이네요. 구현의 범위를 너무 넓게 생각하고 계신 것이 아닐까요?ㅎㅎ 현재 코드에서는 구현을 테스트했다는 느낌을 받는 코드는 거의 없었기에 그런 피드백을 남기지 않았어요.

작성하신 코드에서.... `RequestHeader`, `RequestBody` 를 테스트하려고 했다면 저는 구현을 테스트하지 말라고 할 것 같네요 :)

2019-09-22 22:12 UTC, jinwookh commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
권용근님 답변 감사합니다. 테스트에 대한 자료를 더 찾아보겠습니다!

2019-09-22 22:56 UTC, jinwookh commented on src/main/java/controller/UserCreateController.java
> +            log.error(e.getMessage());
서버의 에러를 클라이언트에게 전달하고 싶어도, 클라이언트에게 전달하는 행위(outStream.write()) 자체에서 exception이 일어난다면 서버의 에러를 클라이언트에게 전달하기 힘들 것 같습니다. 이런 상황에서 catch해서 다시 한 번 5xx로 서버가 클라이언트에게 전달하는 행위를 한다면 계속해서 try catch문이 chaining 될 것 같은데, 로그를 띄우는 게 더 낫지 않을까요?

2019-09-23 03:23 UTC, woowahankingbbode commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
저라면 "결과물로서 get 메서드 추출 기능 테스트, post 메서드 추출 기능 테스트 두 개가 있지만, 같은 로직임을 알게된 이상", 두 테스트를 하나의 테스트로 통합해야겠지요.

Junit5나 Spock 등의 테스트 프레임워크에는 조건을 여러가지로 넘겨줄 수 있는 기능들이 있어요. Junit5 의 ParameterizedTest 나 스폭의 Where 절이 있겠지요.

테스트는 끊임없이 변합니다. 삭제가 되기도 하고 추가가 되기도 하겠지요. 테스트는 고정적인 것이 아닙니다. 요구사항의 변경으로 불필요한 테스트가 되었다면 제거를 할 것이고, 검증이 달라졌다면 검증을 수정하겠죠. 또한 중요한 것이 테스트 역시 지속적으로 리펙토링 되어야하는 대상이라는 점을 생각해보시면 좋겠네요 :) 변경이나 영향에 더 효율적으로 대응할 수 있도록 지속적으로 테스트 역시 리펙토링 되어야할 것이에요. 이 때에 리펙토링 한다고 테스트의 목적이 변하면 안되겠지요.

2줄 요약
1. 테스트는 변경된다.
2. 변경에 대응하기 유연하도록 지속적으로 리펙토링한다.

2019-09-23 11:23 UTC, jinwookh commented on src/test/java/http/HttpRequestTest.java
> +class HttpRequestTest {
킹뽀대님 답변 정말 감사합니다!