[웹서버 Step - 2] 이지 미션 제출합니다.
woowacourse/jwp-was pull request #52
Opened 2019-09-25 04:57 UTC by skygl

이번 피드백도 잘 부탁드립니다!

2019-09-26 04:28 UTC, byjo requested changes
쿠키/세션이 추가되면서 전체적인 구조와 흐름이 더 정리가 잘 된 것 같네요. 👍
예외 처리도 꼼꼼하게 잘 하셨구요. 👏
다만, 좀 더 사용성이 높을 수 있도록 보완하면 좋을 점들이 보여 피드백 드렸으니 확인 부탁드려요.

2019-09-26 04:28 UTC, byjo commented on src/main/java/controller/LoginController.java
> +        SessionManager.addSession(session);
세션이 필요한 컨트롤러가 추가된다면, SessionManager를 사용해서 세션을 관리하는 로직이 중복되겠네요.
또한, 로그인 요청 시점에 세션이 초기화 되는 이슈도 있구요.
아래 첨부드린 아티클을 참고해보시고 세션의 생성 시점에 대해서 고민해보시면 좋을 것 같아요.
- [쿠키(Cookie)와 세션(Session) & 로그인 동작 방법](https://cjh5414.github.io/cookie-and-session/)

2019-09-26 04:28 UTC, byjo commented on src/main/java/controller/UserListController.java
> +                .anyMatch(cookie -> cookie.contains("SESSIONID="));
요구사항에 따르면 로그인 여부가 쿠키를 통해 전달되는데 이에 맞게 구현해주세요.

2019-09-26 04:28 UTC, byjo commented on src/main/java/model/User.java
> +    public void matchPassword(String password) {
이런 메소드가 boolean 타입의 return value를 가지면, 메소드를 호출하는 쪽에서 판단이 더 명확하지 않을까요?

2019-09-26 04:28 UTC, byjo commented on src/main/java/webserver/DispatcherServlet.java
> +            httpResponse.setStatus(405);
custom exception에 대한 처리에 대한 중복 코드가 있는데, 각 exception이 status 를 가지고 있으면 처리를 단순화 할 수 있지 않을까요?

2019-09-26 04:28 UTC, byjo commented on src/test/java/controller/CreateUserControllerTest.java
> +        assertThat(DataBase.findAll()).hasSize(size + 1);
요청으로 보낸 유저가 잘 생성되었는지 검증해보면 더 좋은 테스트가 될 수 있을 것 같아요.

2019-09-26 04:28 UTC, byjo commented on src/main/java/http/HttpRequest.java
> +    public String[] getCookies() {
쿠키 값을 가져올 때 마다 매번 파싱을 해야할까요?
어플리케이션 단에서 쿠키 값을 사용하기 편하게 제공해주면 어떨까요?

2019-09-26 04:28 UTC, byjo commented on src/main/java/webserver/DispatcherServlet.java
> +    public static void doDispatch(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException {
해당 메소드가 static인 특별한 이유가 있을까요?

2019-09-26 04:28 UTC, byjo commented on src/main/java/webserver/DispatcherServlet.java
> +            httpResponse.addHeader(SET_COOKIE, "SESSIONID=''; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT");
쿠키 값이 header에 들어간다는 세부 스펙을 어플리케이션에서 알아야 할까요?
`HttpResponse` 객체가 잘 wrapping 을 해주면 어떨까요?

2019-09-26 05:30 UTC, skygl commented on src/main/java/controller/LoginController.java
> +        SessionManager.addSession(session);
세션이 어떻게 동작하는지 순서대로 정리되어 있어서 잘 이해되었습니다. 👍

2019-09-26 09:12 UTC, skygl commented on src/main/java/controller/LoginController.java
> +        SessionManager.addSession(session);
세션 주기

1. 클라이언트가 서버에 처음으로 Request를 보냄 (첫 요청이기 때문에 세션 ID가 존재하지 않음)
   - Request가 들어올 때 쿠키에 세션 ID가 있는지 검사
   - 없다면 첫 요청이라고 판단하여 세션 생성 후 응답 헤더에 넣어줌
2. 클라이언트가 로그인을 요청하면 서버는 세션을 로그인한 사용자 정보로 갱신하고, 새로운 세션 ID를 발급하여 검사
   - 로그인을 요청해서 성공하면 새로운 세션을 생성하고, 로그인한 사용자 정보를 넣어줌
   - 응답 헤더에 만들어준 세션 ID로 갱신
   - 기존 세션 삭제
3. 로그아웃할 경우 (TODO)
   - 새로운 세션을 발급
   - 응답 헤더에 만들어준 세션 ID로 갱신
4. 클라이언트 종료 시 (TODO)
   - 어떻게 종료 되었는지 알고, 삭제할 것인가?
     - Time-Out 

이런 식으로 이해했는데, 괜찮을까요??

2019-09-26 13:07 UTC, byjo commented on src/main/java/controller/LoginController.java
> +        SessionManager.addSession(session);
먼저, 공유드린 글의 경우 세션을 통해 로그인 정보를 관리하는 방법에 대한 설명이 있었구요.
우리의 미션 요구사항에서는 쿠키를 통해 로그인 여부를 관리 하면 됩니다.
>  로그인이 성공하면 cookie를 활용해 로그인 상태를 유지할 수 있어야 한다. 로그인이 성공할 경우 요청 header의 Cookie header 값이 logined=true, 로그인이 실패하면 Cookie header 값이 logined=false로 전달되어야 한다.

요구사항과는 별개로 세션의 생명주기는 브라우저가 열려있는 동안이기 때문에 로그인/로그아웃 여부에 따라 세션을 새로 생성/삭제 해주지 않아도 괜찮긴 해요.(만약 세션에 사용자 정보를 담아둔다면 로그인/로그아웃 시 기존 세션에 그 정보를 저장하면 되겠죠.)

2019-09-30 06:20 UTC, skygl commented
안녕하세요~
로그인 관련 처리는 쿠키의 logined 헤더 값으로 판단하도록 했고, 세션은 말씀하셨던대로 처음에 생성해주고, 닫히기 전까지 계속 사용하도록 구현했습니다.
쿠키도 클래스로 만들어서 좀더 사용자 입장에서 헤더에 넣고, 빼기 쉽도록 구현했어요.
DispatcherServlet를 쓰레드 밖에서 생성자로 주입하도록 구현했는데, 성능이나 메모리 측면에서 좋다고 생각되었습니다. 혹시 다른 좋은 방법이 있는지 궁금합니다 ❓ 
Exception에 Status 코드를 가지고 있는 것 좋은 것 같아요. 👍

2019-09-30 10:24 UTC, skygl commented
추가로 물어보고 싶은게 있어요!
현재 DispatcherServler 요청들이 들어왔을 때 요청들이 같은 DispatcherServlet 인스턴스를 쓰는게 문제 될 수 있나요?

2019-09-30 23:45 UTC, byjo approved these changes
리팩토링 잘 진행하셨네요! 👏
이전 코드에 비해 훨씬 사용성이 좋아진 것이 느껴지네요.
몇 가지 피드백과 질문에 대한 코멘트 드렸으니, 확인 후 더 궁금한 점이 있다면 편하게 문의 주시구요. 😊
2주동안 즐거웠습니다! 고생 많으셨어요.

2019-09-30 23:45 UTC, byjo commented on src/main/java/webserver/exception/AbstractHttpException.java
> +public abstract class AbstractHttpException extends RuntimeException {
👍
추상 메소드가 있지는 않기 때문에 `abstract` 키워드는 없어도 괜찮을 것 같아요.
대신 예외 클래스 이름을 다르게 짓는 것이 좋겠죠.
찾아보니 스프링에도 비슷한 exception이 있는데 참고하셔도 좋을 것 같습니다! 
- [HttpStatusCodeException](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/HttpClientErrorException.html)
- [HttpClientErrorException](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/HttpClientErrorException.html)

2019-09-30 23:45 UTC, byjo commented on src/main/java/controller/UserListController.java
> +        return "true".equals(httpRequest.getCookie().get("logined"));
[Boolean.parseBoolean()](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String)) 메소드를 사용해도 좋을 것 같아요.

```suggestion
        return Boolean.parseBoolean(httpRequest.getCookie().get("logined"));
```

2019-09-30 23:45 UTC, byjo commented on src/main/java/webserver/RequestHandler.java
> +    public RequestHandler(Socket connectionSocket, DispatcherServlet dispatcherServlet, SessionInitiator sessionInitiator) {
1. 생성자 주입을 사용하셨네요 💯 
싱글 인스턴스를 보장하면서 의존관계가 있는 객체 사이에 커플링을 낮출 수 있게 잘 구현하신 것 같습니다. 테스트 작성이 더 쉬워지는 장점도 있구요.
이러한 형태의 코드는 추후에 DI 프레임워크 미션을 하면서 자주 사용하게 될 것이니 익숙해지면 좋을 것 같아요. 

2. 요청들이 같은 인스턴스를 사용해도 `doDispatch` 메소드와 그 내부에서 호출되는 메소드들의 동작이 read-only 이기 때문에 괜찮지 않을까요?
만약 어떠한 상태 값을 갖는 (그리고 메소드에 의해 이 값이 변경되는) 클래스 변수가 있다면 thread safe하지 않기에 조심해야 하지만, 이 경우에는 문제가 없어보여요.

2019-09-30 23:45 UTC, merged