[웹서버 - Step2] 제이 미션 제출합니다.
woowacourse/jwp-was pull request #54
Opened 2019-09-25 12:54 UTC by JunHoPark93

안녕하세요 리뷰어님! 항상 고생 많으십니다! 😅
두 번째 과제 제출합니다. 미션이 쉽지 않네요.
전체적으로 바뀐 점은, view resolver 를 새로 만들었습니다. 핸들바 리소스와 일반 리소스의 구분의 필요성 때문에 새로 만들게 되었습니다! 그리고 Cookie가 생각보다 매우 많은 설정들이 있어서 공부해보고 몇 가지 적용을 해보았습니다.

감사드립니다 ❤️

2019-09-26 12:26 UTC, byjo requested changes
쉽지 않은 미션이지만 잘 구현하셨어요. 👍
쿠키, 세션 관리와 예외 처리에서 보완하면 좋을 점들이 보여 피드백 드렸습니다.
코멘트 확인 부탁드리고, 혹시나 설명이 불충분하거나 더 궁금한 점이 생기시면 편하게 문의 주세요.

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/handler/controller/custom/UserListController.java
> +        if (SessionContextHolder.isExists(sessionId)) {
요구사항 1,2의 스펙에 따르면 유저 로그인 여부는 `logined` 쿠키를 보고 판단합니다.
>로그인이 성공하면 cookie를 활용해 로그인 상태를 유지할 수 있어야 한다. 로그인이 성공할 경우 요청 header의 Cookie header 값이 logined=true, 로그인이 실패하면 Cookie header 값이 logined=false로 전달되어야 한다.

스펙에 맞게 구현해주세요.

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/handler/controller/custom/LoginController.java
> +        HttpSession httpSession = HttpSession.newInstance();
지금은 세션의 생성이 사용자 로그인과 긴밀하게 연결되어 있네요.
컨트롤러가 세션 관리(세션 및 세션 ID 생성)의 역할까지 하고 있기도 하구요.

첨부드린 아티클을 참고하여 세션이 무엇이고 왜 필요한지, 어떤 방식으로 동작하는지 정리해보시고
생성 및 관리 주체에 대한 작업을 진행 하면 좋을 것 같습니다.

- [쿠키와 세션 개념](https://interconnection.tistory.com/74)
- [쿠키(Cookie)와 세션(Session) & 로그인 동작 방법](https://cjh5414.github.io/cookie-and-session/)

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/handler/controller/custom/LoginController.java
> +    private void validUser(String password, User user) {
유저 validation은 `User` 객체에게 넘겨도 괜찮지 않을까요?
그리고 예외 상황에 대해 단순히 RuntimeException과 메시지만을 던지기 보다는 사용자에게 의미를 줄 수 있는 Exception을 사용하면 좋을 것 같아요.
예를 들어 비밀번호를 틀려서 로그인이 실패했을 때, 사용자가 실패의 원인을 알 수 있다면 다른 비밀번호를 입력하는 등 다음 행동에 대한 도움을 받을 수 있겠죠.

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/http/request/HttpRequest.java
> +            return CookieParser.parse(requestHeader.getHeaderValue("Cookie"));
쿠키 값을 가져올 때마다 String 파싱이 발생하네요. 
`HttpRequest` 를 좀 더 요청에 대해 잘 나타낼 수 있는 객체로 만들어보는 것은 어떨까요?
꼭 HTTP 스펙을 그대로 객체로 만들 필요는 없어요.

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/view/HandlebarResourceResolver.java
> +    public ViewResolveResult resolve(String path) throws Exception {
현재 상황에서는 메소드 오버로딩을 하면 중복을 줄일 수 있지 않을까요?

2019-09-26 12:26 UTC, byjo commented on src/main/java/webserver/view/StaticResourceResolver.java
> +        throw new RuntimeException("정적 resolver 는 model 을 내려줄 수 없습니다");
위에서도 한 번 말씀 드렸지만 코드 전체적으로 적절한 예외를 던지고 처리하는 로직이 들어가면 좋을 것 같아요.
예외 처리에 대한 참고 자료는 정말 많아서, 일단 이펙티브 자바의 예외 챕터에 대한 요약글을 첨부 드릴게요.

- [Effective Java 2/E - Chatper 09 예외 (1)](http://redutan.github.io/2016/03/11/effective-java2-chapter09)
- [Effective Java 2/E - Chatper 09 예외 (2)](http://redutan.github.io/2016/03/12/effective-java2-chapter09-2)

2019-09-27 13:04 UTC, JunHoPark93 commented on src/main/java/webserver/handler/controller/custom/UserListController.java
> +        if (SessionContextHolder.isExists(sessionId)) {
넵! 마지막에 session 구현 미션에서 그것으로 대체하라고 잘못 이해하였습니다 죄송합니다. 다시 요구사항에 맞게 수정하였습니다!

2019-09-27 13:06 UTC, JunHoPark93 commented on src/main/java/webserver/handler/controller/custom/LoginController.java
> +        HttpSession httpSession = HttpSession.newInstance();
다시 보니 컨트롤러에서 session을 생성하는 것이 책임에 있어서 맞지 않다고 생각했습니다. HttpRequest 객체에서 getSession 을 처음 호출 할 때 만들어지는 것으로 변경해보았습니다.

2019-09-27 13:08 UTC, JunHoPark93 commented on src/main/java/webserver/http/request/HttpRequest.java
> +            return CookieParser.parse(requestHeader.getHeaderValue("Cookie"));
지적 해주신 것 처럼 매번 Cookie 를 파싱하니 비효율적으로 보였습니다. Cookie 가 있다면 HttpRequest 객체가 처음 생성 될 때 만들어 놓고 추후 Cookie 가 필요할 때 그것을 조회하는 형식으로 변경하였습니다.

2019-09-27 13:20 UTC, JunHoPark93 commented
안녕하세요 브리님! 피드백 감사합니다.
덕분에 잘못 알고있었던 부분들을 좀 더 보완할 수 있었습니다.
몇 가지 공부해보며 적용해보았는데 틀린 부분이 있다면 지적부탁드립니다. 
주로 바뀐 부분들
1. 존재하지 않는 css, js 등을 요청 할 때 브라우저에서 200으로 표시가 되었던 부분 -> 존재하지 않는다면 내부에서 ResourceNotFoundException 으로 잡아서 response 에 404를 넣어주어서 클라이언트에 리턴하게 변경하였습니다. html 같은 경우에 에러 페이지(error.html)를 주기때문에 상태코드가 200인 것으로 잘못 이해하고 있었습니다. 에러 페이지를 똑같이 주되 상태코드를 404로 변경하였습니다.

2. 세션에 있어서 생성 주체를 HttpRequest에 주었습니다. Cookie 에서 session id를 가지고 있다면, 그 세션을 반환해서 주고 없다면 새로 session을 생성하는 방식으로 변경해보았습니다.

3. 예외처리에 있어서 아직 미흡한 것 같지만ㅠ 최대한 처리할 수 있는 것들을 잡아서 처리를 시도 해보았습니다. checked exception 을 잡아서 (예를들어 IOException) 명시적인 커스텀 예외를 throw 하여 호출한 쪽에서 커스텀 예외를 catch 하는 방식으로 해보았는데 괜찮은 방법인지요.

감사합니다!

2019-09-28 12:20 UTC, byjo approved these changes
리팩토링을 통해 요청과 쿠키, 세션 등의 객체들이 깔끔해졌네요. 👍
피드백 드린 부분과 코드에 대해 많이 고민해보시고 정리한 점이 느껴져서 좋았습니다. 💯
다음 미션도 즐겁게 하시길 바랄게요!

2019-09-28 12:20 UTC, byjo commented on src/main/java/model/User.java
> +    public void checkPassword(String password) {
`checkPassword()` 메소드는 참/거짓 여부를 알려주고, 이를 호출한 쪽에서 예외 처리를 하는 것이 자연스럽지 않을까요?

2019-09-28 12:20 UTC, byjo commented on src/main/java/webserver/http/request/HttpRequest.java
> +    public HttpSession getSession() {
👍

2019-09-28 12:20 UTC, merged