[웹 서버 - Step2] 버디 미션 제출합니다.
woowacourse/jwp-was pull request #59
Opened 2019-09-27 09:27 UTC by imkimheejoo

안녕하세요 화투님!
시간이 얼마 남지 않아 먼저 PR보냅니다.
아직 테스트 코드가 부족하여 주말에 추가할 예정입니다.
많은 지적 부탁드립니다!

2019-09-28 17:50 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
기존 코드 개선 및 세션 구현 👍 
매우 구현 잘 해주셨습니다.
몇가지 피드백 추가했는데 참고 부탁드리구요, 궁금하신 점 있으시면 언제든지 연락주세요! :)

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/controller/LoginController.java
> +        throw new BadRequestException();
BasicController에서 예외에 대해서는 미리 구현해놓을수 있지않을까요?(상속을 혀용하는 protected 접근제어자 등으로요 :))

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/controller/LoginController.java
> +                response.addCookie("JSESSIONID", session.getId());
세션의 생성, 세션 정보에 대한 쿠키 베이킹을 컨트롤러에서 직접 할 필요가 있을까요?
WAS에서 책임을 질 수는 없을까요? :)

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +        byte[] body = HandlebarsGenerator.render(modelAndView);
조금 더 개선해보면 어떨까요?
`Controller는 어떤 데이터를 내려줄지(JSON, Template 등)에 대한 정보를 담은 ModelAndView를 리턴하고, WAS에서 이를 처리한다.`

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +        header.addHeader("Content-Type", "text/" + contentType + ";charset=utf-8");
기본적인 헤더들은 상수로 관리해보면 어떨까요? :)

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +        header.addHeader("Content-Length", "" + body.length);
String.valueOf, Integer.toString도 활용해보세요 :)

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +        if (!cookie.isEmpty()) {
쿠키 세팅은 다른 response들에도 공통적으로 해줘야하는 내용 아닐까요? :)

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/session/SessionRepository.java
> +    private static Map<String, Session> sessions = new HashMap<>();
여러 쓰레드에서 동시 접근가능한 객체인데 동기화에 대해 고민해보면 어떨까요?

2019-09-28 17:50 UTC, phs1116 commented on src/main/java/controller/LoginController.java
> +        Session session = SessionRepository.create();
HttpRequest.getSession(boolean create), HttpRequest.getSession() 스펙도 참고해보세요 :)

2019-09-30 03:59 UTC, imkimheejoo commented on src/main/java/controller/LoginController.java
> +        throw new BadRequestException();
수정했습니다!

2019-09-30 04:03 UTC, imkimheejoo commented on src/main/java/controller/LoginController.java
> +                response.addCookie("JSESSIONID", session.getId());
컨트롤러에서는 사용자의 비즈니스로직만 가지고 있어야 된다고 생각해서 컨트롤러에 쿠키설정을 제거 했습니다. 그런데 쿠키 베이킹을 was어디에 둬야하는지에 대한 고민을 하다가 억지로(?) request.getSession할때 파라미터로 response를 주어 getSession안에 addCookie를 하게 둔 상황입니다..

2019-09-30 04:11 UTC, imkimheejoo commented on src/main/java/controller/UserListController.java
> +        byte[] body = HandlebarsGenerator.render(modelAndView);
리팩토링하면서 Controller의 역할에 맞게 View처리와 response 설정을 분리하려고 노력했습니다. view처리와 response를 RequestHandler 클래스에서 처리하고 싶었는데 그러면 정적파일 요청의 반환도 ModelAndView로 반환해야 하는 문제가 발생해서 현재는 DispatcherServlet(NormalRequestResolver)에 처리하게 두었습니다. 정적파일도 ModelAndView로 반환해야하는지 아니면 다른방법이 있는지 알고 싶습니다!

2019-09-30 04:11 UTC, imkimheejoo commented on src/main/java/http/response/HttpResponse.java
> +        header.addHeader("Content-Type", "text/" + contentType + ";charset=utf-8");
수정했습니다!

2019-09-30 04:12 UTC, imkimheejoo commented on src/main/java/http/response/HttpResponse.java
> +        header.addHeader("Content-Length", "" + body.length);
body.length를 Integer.toString으로 리팩토링 했습니다!
 String.valueOf는 어느 곳에 적용해야하는지 아직 감이 잡히지 않습니다.

2019-09-30 04:12 UTC, imkimheejoo commented on src/main/java/http/response/HttpResponse.java
> +        if (!cookie.isEmpty()) {
redirect메소드와 okResponse에 중복로직인 cookie확인 로직을 메소드로 분리하였습니다!

2019-09-30 04:13 UTC, imkimheejoo commented on src/main/java/session/SessionRepository.java
> +    private static Map<String, Session> sessions = new HashMap<>();
동기화가 지원되는 Collections.synchronizedMap으로 적용했습니다!

2019-09-30 04:13 UTC, imkimheejoo commented on src/main/java/controller/LoginController.java
> +        Session session = SessionRepository.create();
수정했습니다!

2019-10-02 04:53 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적인 피드백 반영 👍 
모델뷰 분리 등 전체적으로 구현 매우 잘해주셨습니다.
간단한 피드백 추가했는데 확인 부탁드릴게요 :)

2019-10-02 04:53 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +        byte[] body = HandlebarsGenerator.render(modelAndView);
네. 리소스는 ModelAndView를 사용하지 않아도 될 것 같습니다. :)
DispatcherServlet에서만  ModelAndView를 처리해도 충분해보여요.

2019-10-02 04:53 UTC, phs1116 commented on src/main/java/controller/LoginController.java
> +        Session session = request.getSession(response);
request 내 혹은 공통으로 관리할 수 있는 데이터에 저장후 response를 생성할 때 전달할수도 있을 것 같아요 :)

2019-10-02 04:53 UTC, phs1116 commented on src/main/java/webserver/resolver/NormalRequestResolver.java
> +        byte[] body = ViewResolver.render(modelAndView);
render 방식이 현재 template으로 고정되어있는데요,
ModelAndView가 어떤 방식으로 렌더링을 할지 구현할 수 있을 것 같습니다.
JSON으로 렌더링하도록 구현되어있다면 JsonView로, 템플릿이면 TemplateView 등 :)

2019-10-08 08:04 UTC, imkimheejoo commented on src/main/java/webserver/resolver/NormalRequestResolver.java
> +        byte[] body = ViewResolver.render(modelAndView);
ViewProcessor를 통해 RedirectViewProcessor, TemplateViewProcessor 를 구현하여 렌더방식이 확장되도록 수정하였습니다!

2019-10-08 08:05 UTC, imkimheejoo commented on src/main/java/controller/LoginController.java
> +        Session session = request.getSession(response);
HttpRequest의 Cookie에 데이터를 저장후 Response생성자를 통해 response에 전달하는 로직으로 수정했습니다!

2019-10-09 16:51 UTC, phs1116 approved these changes
정말 고생 많았습니다. 버디.
구현 매우 잘해주셨어요. :) 👍 
이번 과제는 머지하도록 할게요.
개발하시느라 정말 수고 많으셨습니다.

2019-10-09 16:51 UTC, merged