[웹 서버 - Step2] 히브리 미션 제출합니다.
woowacourse/jwp-was pull request #66
Opened 2019-09-28 04:11 UTC by yk1028

안녕하세요. 히브리입니다:)
저번에 머지하면서 주신 피드백을 반영하면서 step2 기능 구현했습니다.
잘 부탁드립니다.

2019-09-29 02:41 UTC, jeonghoon1107 requested changes
안녕하세요 히브리!
깔끔하게 잘 구현하셔서 피드백할 내용이 거의 없네요 💯 
아쉬운 점이 있어서 몇가지 피드백남겼으니 확인부탁드려요 :)

2019-09-29 02:41 UTC, jeonghoon1107 commented on src/main/java/servlet/AbstractServlet.java
> +    protected void doGet(HttpRequest request, HttpResponse response) {
LoginServlet은 doPost만 구현이 되어있는데 get 요청을 하면 어떻게 되나요?
해당 부분에도 METHOD_NOT_ALLOWED를 구현하면 좋을 것 같아요.

2019-09-29 02:41 UTC, jeonghoon1107 commented on src/main/java/servlet/UserListServlet.java
> +            ViewResolver.resolveWithBody(request, response, view.getBytes());
applyModelInView 해당 메서드에서 null이 반환될 수 있을 것 같은데, getBytes를 하면 NPE 발생하겠네요 :)

2019-09-29 02:41 UTC, jeonghoon1107 commented on src/main/java/servlet/UserListServlet.java
> +            String view = TemplateEngine.applyModelInView("/user/list", model);
view를 객체로 사용하는 것은 어떨까요?

2019-09-29 02:41 UTC, jeonghoon1107 commented on src/main/java/handlebars/TemplateEngine.java
> +public class TemplateEngine {
템플릿 엔진에는 종류가 많죠.
확장성을 고려해 바꾸어보면 어떨까요? ViewResolver를 포함해서..

2019-09-29 05:51 UTC, yk1028 commented on src/main/java/servlet/AbstractServlet.java
> +    protected void doGet(HttpRequest request, HttpResponse response) {
추가했습니다!

2019-09-29 08:12 UTC, yk1028 commented
리뷰 감사합니다!
한가지 궁금한점이 있는데 body 생성을 어디서 하면 좋을지 고민됩니다. 중간에 에러가 발생해서 그에 따른 화면을 보여줘야 하기 때문에 미리 body를 가져오고 랜더링하는 작업이 이루어진다면 손해라고 생각했습니다. 그래서 가장 늦게 처리하는 것이 좋아 보여 response를 보내기 직전에 파일을 읽고 랜더링하는 과정을 거쳐 body를 보내도록 수정했습니다. Content-Type, Content-Length 헤더 때문에 코드가 지저분해지는것 같아 Body 생성 시점을 어디로 하면 좋을지 고민됩니다. 
리뷰어님의 의견이 궁금합니다:)

2019-09-29 08:14 UTC, yk1028 commented on src/main/java/handlebars/TemplateEngine.java
> +public class TemplateEngine {
View 인터페이스를 활용하여 여러 형태의 View를 랜더링 할 수 있도록 구현했습니다.

2019-09-30 13:23 UTC, jeonghoon1107 requested changes
안녕하세요 히브리!
피드백 반영을 잘 해주셨네요 👍 
마지막으로 피드백 한가지 남겼으니 확인부탁드려요 :)

아래에도 의견을 남겼지만, response에 관한 것은 각 ~Servlet 에서 끝내면 조금 더 깔끔할 것 같아요.
혹시 다른 의견이 있으면 DM 주세요!

2019-09-30 13:23 UTC, jeonghoon1107 commented on src/main/java/webserver/RequestHandler.java
> +            ResponseSender.send(out, response);
각 Servlet안에서 response를 write하는 것은 어떨까요?
response가 View를 가지고 다닐 필요가 없어질 것 같아요.

현재 구현을 보면 response의 header와 body만 변경될 것 같은데, body의 length역시 각 요청의 응답에 따라 달라질테니 각각의 response에 대한 책임은 ~Servlet에 주는게 좋을 것 같아요. 현재도 각 Servlet이 대부분의 데이터를 set하는 것 같네요!

2019-09-30 17:07 UTC, yk1028 commented
리뷰 감사합니다:) 
Servlet에서 write하는 방식으로 변경하니 코드가 많이 정리된 것 같습니다. response가 약간 무거워진것 같지만 그것보다 정리되는 코드가 더 많기 때문에 더 나은 코드라고 생각합니다.

추가 질문이 있습니다. 어제 DataOutputStream flush하는 부분은 없나요!?라고 말씀하셨었는데 DataOutputStream의 flush의 경우 close 되면서 호출되기 때문에 따로 호출하지 않아도 되지 않을까요? 따로 flush를 호출해야한다면 어떤 이유가 있을지 궁금합니다!

2019-10-01 14:53 UTC, jeonghoon1107 requested changes
안녕하세요 히브리!
정말 깔끔하게 리팩토링하셔서 피드백 할 내용이 없네요 💯 
구현한 세션을 활용하면 훨씬 좋을 것 같아서 바로 머지는 하지 않을게요.

2019-10-01 14:53 UTC, jeonghoon1107 commented on src/main/java/servlet/UserListServlet.java
> +        if (request.matchCookie("logined", "true")) {
메서드로 분리하면 더 명확하고 깔끔할 것 같아요!

2019-10-01 14:53 UTC, jeonghoon1107 commented on src/main/java/http/request/HttpRequest.java
> +    private HttpSession session;
세션을 사용했으면 좀 더 좋았을텐데 아쉽네요.

2019-10-02 01:30 UTC, yk1028 commented on src/main/java/servlet/UserListServlet.java
> +        if (request.matchCookie("logined", "true")) {
분리했습니다!

2019-10-02 05:47 UTC, yk1028 commented on src/main/java/http/request/HttpRequest.java
> +    private HttpSession session;
로그인 정보를 세션에 담아 로그인 처리를 하도록 수정했습니다!

2019-10-02 13:32 UTC, jeonghoon1107 approved these changes
안녕하세요 히브리!
세션으로 잘 바꾸셨네요 👍 
마지막으로 간단한 피드백 몇가지 남겼으니 확인 부탁드려요. 추가로 궁금하신 점은 언제든 DM 주세요.
해당 미션은 여기에서 머지할게요!
고생하셨습니다 :)

2019-10-02 13:32 UTC, jeonghoon1107 commented on src/main/java/http/HttpCookie.java
> +public class HttpCookie {
원하는대로 동작하지 않을 것 같은데
cookie의 path를 공부해보면 좋을 것 같아요.

2019-10-02 13:32 UTC, jeonghoon1107 commented on src/main/java/servlet/LoginServlet.java
> +        setLoginInfo(request, response, false);
session이 각 Servlet에서 만들어지고 있네요.
레이어를 하나 더 만드는 것으로 프레임워크 단에서 session을 만드는 것도 고려해보면 좋을 것 같아요.

2019-10-02 13:32 UTC, jeonghoon1107 commented on src/main/java/servlet/LoginServlet.java
> +        String loginValue = isLogin ? "true" : "false";
굳이 다시 변환해야 하나요?

2019-10-02 13:32 UTC, merged

2019-10-02 13:33 UTC, jeonghoon1107 commented on src/main/java/servlet/LoginServlet.java
> +        response.setCookie("sessionId", session.getId());
하드코딩하지 않고 상수로 관리하는 것이 좋겠네요.

2019-10-02 13:34 UTC, jeonghoon1107 commented on src/main/java/http/session/HttpSession.java
> +    public void invalidate() {
HttpSessionTable에서 삭제해야하지 않을까요?

2019-10-02 14:14 UTC, yk1028 commented on src/main/java/http/HttpCookie.java
> +public class HttpCookie {
Path를 정의해주지 않으면 현재 document의 위치가 Path로 들어가기 때문에 현재 코드에서 Path=/user와 같은 상태가 된것 같습니다. 그래서 그 경로가 포함된 경로에서만 cookie가 적용됩니다. 모든 경로에서 쿠키를 지원하기 위해서 HttpCookie 생성시 기본적으로 Path=/를 포함하도록 구현했습니다.

2019-10-02 14:24 UTC, yk1028 commented on src/main/java/servlet/LoginServlet.java
> +        String loginValue = isLogin ? "true" : "false";
session의 logined에 true와 false만 들어가도록하고싶어서 이런 방식으로 구현했습니다.