[웹 서버 2단계] 티버 미션 제출합니다.
woowacourse/jwp-was pull request #73
Opened 2019-09-28 15:49 UTC by yjll1019

2019-09-30 14:10 UTC, kang-hyungu requested changes
새벽까지 구현하느라 고생했어요 @.@
구조를 어떻게 개선하면 좋을지 간단하게 피드백 남겼어요
계속 리팩토링 해보시고 궁금한 점 생기면 언제든 dm 주세요!

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/CreateUserController.java
> +	public static final String JSESSION_ID = "jsessionId";
세션키는 컨트롤러가 아닌 다른곳에서 관리하는게 좋지 않을까요?

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/CreateUserController.java
> +			if(!httpRequest.isCookieValue(JSESSION_ID)) {
isCookieValue보다 hasCookieValue라고 하는게 어떨까요?
세션키를 가지고 있는지 쿠키로부터 확인하는 기능이니깐요

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/ResourceController.java
> +				httpResponse.setInitialSession(uuid);
css, js 같은 정적 파일을 호출할 때도 세션을 생성해야될까요?

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/UserListController.java
> +	private byte[] generateDynamicResource() throws IOException {
템플릿 엔진을 컨트롤러에서 구현하는 것보다 view에서 처리하도록 해보는게 어떨까요?
핸들바가 아닌 다른 템플릿 엔진을 쓸 수 있도록 구현하면 더 좋겠네요

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/UserLoginController.java
> +		boolean result = userService.login(httpRequest.getHttpRequestBody().get("userId"),
한 줄에 너무 많은 내용을 담고 있어 코드 읽기가 힘드네요
가독성을 위해 변수에 담아보는게 어떨까요?
```suggestion
		final Map<String, String> requestBody = httpRequest.getHttpRequestBody();
		final String userId = requestBody.get("userId");
		final String password = requestBody.get("password");

		boolean result = userService.login(userId, password);
```

2019-09-30 14:10 UTC, kang-hyungu commented on src/main/java/controller/UserLoginController.java
> +			byte[] responseBody = FileIoUtils.loadFileFromClasspath(path);
파일을 읽어오는 로직을 http response로 옮기거나 view로 옮기는게 좋겠네요
컨트롤러에서 너무 많은 일을 처리하고 있어요

2019-10-05 07:58 UTC, yjll1019 commented on src/main/java/controller/CreateUserController.java
> +	public static final String JSESSION_ID = "jsessionId";
SessionManager에 두어야하나 고민했는데 
SESSION_ID 라는 변수가 해당 클래스에 사용되지 않아서 
Header 클래스에 두도록 수정했습니다!

2019-10-05 07:59 UTC, yjll1019 commented on src/main/java/controller/CreateUserController.java
> +			if(!httpRequest.isCookieValue(JSESSION_ID)) {
네! 수정했습니다. 감사합니다~

2019-10-05 08:00 UTC, yjll1019 commented on src/main/java/controller/ResourceController.java
> +				httpResponse.setInitialSession(uuid);
해당 클래스에서 html 파일인지 검사하여 세션을 생성하도록 수정했습니다!

2019-10-05 08:01 UTC, yjll1019 commented on src/main/java/controller/UserListController.java
> +	private byte[] generateDynamicResource() throws IOException {
ViewResolver와 ModelAndView 객체를 생성하여 처리하도록 수정했습니다!

2019-10-05 08:01 UTC, yjll1019 commented on src/main/java/controller/UserLoginController.java
> +		boolean result = userService.login(httpRequest.getHttpRequestBody().get("userId"),
수정했습니다~! 감사합니다 :)

2019-10-05 08:02 UTC, yjll1019 commented on src/main/java/controller/UserLoginController.java
> +			byte[] responseBody = FileIoUtils.loadFileFromClasspath(path);
HandlebarsHtmlTemplate과 HttpResponseGenerator 에서 처리하도록 수정했습니다~ 감사합니다.

2019-10-05 08:16 UTC, yjll1019 commented
안녕하세요! 구구님 리뷰이 티버입니다! :)
빠른 피드백 주신 것에 비해 피드백 반영이 너무 늦어졌네요. 죄송합니다 ㅠㅠ 

여쭤보고 싶은 부분이 있습니다! 
현재 각 컨트롤러에서 해당 HttpRequest 객체에 sessionId 가 포함되어 있는지 확인하는 기능이 중복으로 들어가있습니다.
이 부분을 AbstractController 클래스의 service() 메서드에서 처리하려고하니 메서드의 매개변수로HttpResponse가 필요했습니다.

Controller 인터페이스의 매개변수를 HttpRequest와 HttpResponse를 받도록 수정하면 
RequestHandler 에서 이처럼 생성자의 매개변수로 OutputStream을 받고 
`controller.service(httpRequest, new HttpResponse(outputStream));`
`    public HttpResponse(StatusLine statusLine, Header header, byte[] responseBody) {` 

HttpResponse의 생성자에 필요한 매개변수를 setter를 이용해서 받아야한다고 생각했습니다.
setter를 사용할지 중복로직을 그대로 둘지 고민이 되어 일단 후자의 방법을 택했는데요.
혹시 이 이슈를 해결할 힌트를 주실 수 있으신가요..?

2019-10-07 15:35 UTC, kang-hyungu commented
자바로 was 서버를 구현할 때 서블릿 표준이 정해져 있습니다.
https://en.wikipedia.org/wiki/Java_servlet#Example

HttpServlet을 상속해서 구현하다보면 http response에 세션을 설정하기 위해 setter를 사용할 수 밖에 없는 구조로 이미 규약이 잡혀 있어 어쩔 수 없이 setter를 쓰게 될거에요
이부분은 setter를 써도 크게 문제 없다고 생각해요

2019-10-07 15:40 UTC, kang-hyungu approved these changes
피드백 반영하고 리팩토링 하느라 고생하셨어요 👏 
was 구현하기가 파고들다보면 자연스럽게 mvc 구현까지 넘어가면서 이것저것 개발해야될게 계속 보일거에요 ㅎㅎ;
was에서 http를 어떻게 처리하는지 직접 구현해보면서 파악하게 되었다면 충분히 목표 달성했다고 생각합니다.
mvc 미션도 재밌는 부분이 많으니 was는 이쯤에서 정리하는게 좋겠어요 :) 수고하셨어요!

2019-10-07 15:40 UTC, merged