[웹 서버 - Step2] 쿠기 미션 제출합니다.
woowacourse/jwp-was pull request #77
Opened 2019-09-29 11:41 UTC by men7627

안녕하세요 박시홍 리뷰어님!
웹서버 Step2로 다시 리뷰를 받게 된 쿠기입니다! 🙇 

먼저 Step1에서 merge와 동시에 남겨주신 피드백에 대해서 500error와 404에러를 구분해 보았습니다.
정확히 404, 500을 어느 시점에서 구분해야 할지 몰라 일단은 RequestHandler에서 구분해 보았습니다.
또한 parse method를 좀 더 간소화해보려 했었는데, 그 부분은 잘 되지 않았습니다.😢

Step1에서 불필요하게 클래스를 나누다 보니 많이 복잡해진 느낌이 많이 들어서 전체적으로 View 관련 된 클래스들을 제거하고 구조를 변경해보았습니다.
Render 클래스에서 전체적인 렌더링을 담당하고 Response를 Convert해주는 클래스를 구현하였습니다.
전체적인 클래스 네이밍도 수정해보았습니다.

Response를 생성하는 데에는 Builder패턴을 적용하면 좀 더 깔끔해질 수 있을 것 같아서 구현해 보았습니다.
Session을 구현하고 로그인 및 유저 리스트 조회할 때 Session을 적용해 보았습니다.

잘 부탁드립니다! 😁

2019-09-30 14:05 UTC, hongsii requested changes
2단계도 잘 구현해주셨습니다 👍 
몇 가지 아쉬운 점이 있어서 피드백 드렸으니, 반영해보면 좋을 듯 합니다.

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/ControllerHandler.java
> +                .collect(Collectors.toList());
`resolveRequestMapping(...)` 는 매핑된 첫 번째 컨트롤러만 가져오니 아래와 같이 구현하면 메서드를 제거할 수 있을 듯 합니다 :)
``` java
        return controllers.keySet().stream()
                .filter(key -> key.match(httpRequest))
                .sorted()
                .findFirst()
                .orElseThrow(NotFoundException::new)
```

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/ListController.java
> +    private Map<String, String> getCookieMap(HttpRequest httpRequest) {
매번 쿠키가 필요한 컨트롤러에서는 반복해서 작성해야하는 코드 같습니다. 클래스로 추출해보면 어떨까요?

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/LoginController.java
> +        if (!(user == null) && password.equals(user.getPassword())) {
비밀번호 확인을 User라는 클래스로 메시지를 보내서 확인하는 구조로 바꿔보면 어떨까요?

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/supoort/HttpRequestParser.java
> +    private static HttpParameters parseRequestBody(List<String> headerLines) {
현재 `HttpRequestParser` 에서 `Request` 객체 생성을 위해 관련 객체를 생성하는 책임을 모두 가지고 있어서 클래스가 상당히 복잡해보입니다. 각 클래스에게 파싱하는 로직을 위임하고 이 클래스에서는 각 객체를 생성해 조립만하는 역할만 하도록 리팩토링 해보면 좋을 듯 해요!
ex) `HttpParameters` 클래스의 정적 팩토리 메서드를 만들고 거기서 객체에 필요한 데이터를 만들어 객체 생성

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/ListController.java
> +            Handlebars handlebars = getHandlebars();
사용자는 매번 Handlerbars가 필요한 컨트롤러에서는 이와 같은 코드를 반복해야 합니다.
사용자는 경로만 입력하면 프레임워크단에서 파일을 읽어와 매핑해주는 방식으로 추상화해보면 좋을 것 같아요!

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/LoginController.java
> +                    .addHeader(SET_COOKIE, "JSESSIONID=" + httpSession.getId() + "; Path=/")
프레임워크 사용자가 JSESSIONID로 저장해야한 다는 것을 알아야 할까요? 전체적으로 컨트롤러에서 너무 많은 것을 사용자가 반복적으로 구현해야하는 구조입니다. 개선해보면 좋을 것 같아요!

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/LoginController.java
> +        String userId = httpParameters.getParameter("userId");
`HttpRequest` 클래스의 `getParameters()`를 직접 호출하지 않고, 파라미터명을 전달하면 파라미터가 조회되는 구조로 바꿔보면 어떨까요?

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/view/Renderer.java
> +        if (HttpStatus.FOUND.equals(httpResponse.getStatusLine().getHttpStatus())) {
getter보다는 메시지를 보내는 방식으로 변경하면 좋을 것 같아요.

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/ControllerMapping.java
> +        Matcher matcher = pattern.matcher(httpRequest.getRequestLine().getHttpUri().getResourceLocation());
현재 반복된 getter로 값을 꺼내고 있습니다. 각 클래스로 메시지를 보내도록 변경해보면 좋을 것 같아요.

2019-09-30 14:05 UTC, hongsii commented on src/main/java/http/controller/ListController.java
> +        if (cookieMap != null && cookieMap.get("JSESSIONID") != null) {
로그인 여부를 쿠키(또는 세션)에 담아 필요한 시점에서 성공 여부를 체크하는 게 요구사항입니다!

2019-10-05 08:58 UTC, men7627 commented on src/main/java/http/controller/ControllerHandler.java
> +                .collect(Collectors.toList());
감사합니다!
stream 최종 연산에 대한 개념이 부족해서 생각을 잘못한 것 같습니다.
stream 최종 연산에 대해 다시 공부하고 적용하였습니다.

2019-10-05 09:08 UTC, men7627 commented on src/main/java/http/controller/ListController.java
> +    private Map<String, String> getCookieMap(HttpRequest httpRequest) {
수정하였습니다.
쿠키 클래스를 만들어 쿠키에 대한 맵을 만드는 과정은 생성자로, 쿠키 값을 검사하는 로직은 메서드로 수정하였습니다.

2019-10-05 09:16 UTC, men7627 commented on src/main/java/http/controller/LoginController.java
> +        if (!(user == null) && password.equals(user.getPassword())) {
수정하였습니다.
유저 내부에서 password를 확인하고, password를 꺼내오는 것도 옳지 않다고 판단하여 getPassword()를 제거하였습니다.

2019-10-05 09:26 UTC, men7627 commented on src/main/java/http/controller/LoginController.java
> +        String userId = httpParameters.getParameter("userId");
수정하였습니다.
Controller에서 HttpParameters를 모르도록 하니까 좋은 것 같습니다!

2019-10-05 09:30 UTC, men7627 commented on src/main/java/http/view/Renderer.java
> +        if (HttpStatus.FOUND.equals(httpResponse.getStatusLine().getHttpStatus())) {
수정하였습니다!

2019-10-05 09:40 UTC, men7627 commented on src/main/java/http/controller/ControllerMapping.java
> +        Matcher matcher = pattern.matcher(httpRequest.getRequestLine().getHttpUri().getResourceLocation());
uri는 HttpUri 클래스에서 method는 HttpMethod 클래스에서 검증하도록 각각의 역할을 분리 했습니다!

2019-10-05 10:02 UTC, men7627 commented on src/main/java/http/controller/ListController.java
> +        if (cookieMap != null && cookieMap.get("JSESSIONID") != null) {
로그인 시 "Set-Cookie"를 등록 하고, 리스트 조회 시 "Cookie" 값을 검사하는 것으로 이해했었는데, 이것이 아닌가요?

2019-10-06 14:43 UTC, men7627 commented on src/main/java/http/controller/ListController.java
> +            Handlebars handlebars = getHandlebars();
Template에 의존한 Response 생성하는 과정을 HttpResponse의 메서드 forwardByTemplate으로 구현하였습니다.

2019-10-06 15:58 UTC, men7627 commented on src/main/java/http/controller/LoginController.java
> +                    .addHeader(SET_COOKIE, "JSESSIONID=" + httpSession.getId() + "; Path=/")
프로토콜, 상태코드, 컨텐트 타입과 같은 기본적인 헤더들은 forward, sendRedirect, forwardByTemplate 시 내부적으로 자동 설정되게 구현했습니다. 그리고 사용자가 임의로 수정할 수 있도록 기존 코드도 두었습니다.

JSESSIONID 관련 로직은 외부로 빼거나 내부로 넣어보려고 했는데, 저는 JSESSIONID 라는 것은 로그인 성공 시에만 발급 된다고 판단하여, 로그인 시에 설정이 되어야 되는데, 그것이 외부나 내부로 들어가면 판단이 쉽지 않은 것 같아 해결하지 못하였습니다. 
추가적인 피드백 부탁드립니다 !

2019-10-06 15:59 UTC, men7627 commented on src/main/java/http/supoort/HttpRequestParser.java
> +    private static HttpParameters parseRequestBody(List<String> headerLines) {
HttpRequestParser의 책임을 모두 나누어 각각의 클래스에서 생성할 때로 분리했습니다.
HttpRequestParser의 책임 및 복잡성을 낮출 수 있었습니다.

2019-10-06 18:40 UTC, men7627 commented
피드백 감사드립니다!

피드백을 반영하던 도중 질문이 하나 생겼습니다.
controller에서 JSESSIONID 값을 setting 해주는 것이 사용자가 할 필요가 없는 작업이라고 피드백을 주셨는데, 그것은 저도 동의합니다. 그래서 그 부분을 어디론가 빼야 겠다고 생각을 했는데, 제가 판단하기에 제일 마땅한 곳은 로그인이 성공하고 session에 setAttribute를 해줄 때라고 생각했습니다.
그런데 session이 response에 대해서 알고 있는 것도 부자연스럽고, 딱히 방법이 떠오르지 않아 반영하지 못했습니다.😢

이 부분에 대하여 추가 피드백 부탁드립니다!
감사합니다.🙇

2019-10-07 13:58 UTC, hongsii requested changes
피드백 반영을 잘해주셨습니다 💯 
질문주신 내용에 대해 피드백드렸으니, 참고해서 반영해보세요 :)

2019-10-07 13:58 UTC, hongsii commented on src/main/java/http/controller/LoginController.java
> +                    .addHeader(SET_COOKIE, "JSESSIONID=" + httpSession.getId() + "; Path=/")
세션/쿠키는 상태가 유지되지 않는 HTTP 프로토콜을 보완하기 만들어졌습니다.
여기서 JSESSIONID 는 톰캣 컨테이너가 세션을 발급하고 나서 다음 요청에서도 특정 사용자에게 부여한 세션을 기억하기 위해 사용하는 쿠키 헤더값입니다.
즉, 로그인 여부와 상관없이 세션이 만들어졌으면 이미 발급된 세션이 있으니깐 다음 요청 때에 서버가 알 수 있게 하는 장치입니다.
그리고 세션은 클라이언트가 최초 접속 시 생성하는게 일반적인 구조입니다!

* [[참고1](https://codedragon.tistory.com/4723)]
* [[참고2](https://jeong-pro.tistory.com/80)]

이를 참고해서 리팩토링해보면 좋을 듯 합니다 :)

2019-10-07 13:58 UTC, hongsii commented on src/main/java/webserver/RequestHandler.java
> +            HttpResponse httpResponse = controllerHandler.doService(httpRequest);
응답 전 `HttpRequest`, `HttpResponse` 가 서로 협력하면 세션을 설정해줄 수 있지 않을까요?

2019-10-13 22:21 UTC, men7627 commented
감사합니다!
JSESSIONID가 로그인 시에만 발급해 줘야한다고 착각하고, 세션은 세션에 접근을 할 때(로그인 같은 경우)만 생성해 주어야 한다고 착각하고 있었던 것 같습니다.
세션은 클라이언트가 최초접속 시 생성되고 로그인 여부와 상관없이 발급이 된다는 점을 고려하니, Controller 구분 없이 추후에 공통적으로 처리하면 된다고 판단하였습니다.
그래서 요청에 대한 해당 컨트롤러를 찾아 서비스를 수행하게 하는 ControllerHandler에서 Request와 Response의 협력으로 JSESSIONID를 발급하였습니다.

2019-10-14 12:36 UTC, hongsii approved these changes
피드백 반영하시느라 고생하셨습니다! 👍 
머지하겠습니다 :)

2019-10-14 12:36 UTC, merged