[웹서버 - Step2] 비모 미션 제출합니다.
woowacourse/jwp-was pull request #78
Opened 2019-09-29 11:56 UTC by SEOKHYOENCHOI

안녕하세요!

피드백을  중복을 없애는 것을 목표로 2단계 진행했습니다!

아직 컨트롤러 테스트가 부족한데, 얼른 추가하도록 하겠습니다ㅠㅠ

잘 부탁드립니다!

2019-09-30 14:45 UTC, hongsii requested changes
추상화 및 전체 설계를 잘 하셨습니다! 💯 
간단한 피드백 남겼으니, 반영해보면 좋을 듯 합니다 :)

2019-09-30 14:45 UTC, hongsii commented on src/main/java/http/common/HttpVersion.java
> +                //.orElseThrow(HttpVersionNotFoundException::new)
안 쓰는 코드는 바로바로 제거해주세요!

2019-09-30 14:45 UTC, hongsii commented on src/main/java/controller/LoginController.java
> +            httpResponse.addHeaderAttribute("Set-Cookie", "SessionID=" + session.getId() + "; Path=/");
이 동작은 사용자가 구현하는 Controller가 아닌 프레임워크에서 처리해주면 어떨까요? 세션의 생명주기를 고민해서 변경해보면 좋을 듯 합니다 :)

2019-09-30 14:45 UTC, hongsii commented on src/main/java/http/common/HttpHeader.java
> +        if (httpHeader.containsKey(key)) {
Map의 `getOrDefault(..)` 를 활용하면 분기문 없이 일정한 로직으로 구현이 가능할 듯 합니다.

2019-09-30 14:45 UTC, hongsii commented on src/main/java/http/session/SessionRepository.java
> +        return sessions.containsKey(sessionId) ? sessions.get(sessionId) : createSession();
여기도 `getOrDefault(...)` 를 활용할 수 있을 듯 합니다.

2019-09-30 14:45 UTC, hongsii commented on src/main/java/http/session/SessionRepository.java
> +        while (sessions.containsKey(uuid)) {
do-while(..) 구문으로 바꾸면 UUID 생성 로직의 중복을 막을 수 있을 듯 합니다.
그리고 UUID는 중복이 될 가능성이 매우 희박하기 떄문에 일반적으로는 고유하다고 보고 별도의 중복 체크를 하지 않는 편입니다. :)

2019-10-01 10:04 UTC, SEOKHYOENCHOI commented on src/main/java/http/common/HttpHeader.java
> +        if (httpHeader.containsKey(key)) {
이 메서드는 맵에 키가 있으면 맵에 있는 리스트를 꺼내 밸류를 추가하고,
없으면 맵에 키, 밸류와 함께 새로운 리스트를 넣습니다.
이 메서드에서는 getOrDefault()를 사용할 수 없을 것 같습니다.

2019-10-01 10:04 UTC, SEOKHYOENCHOI commented on src/main/java/http/session/SessionRepository.java
> +        return sessions.containsKey(sessionId) ? sessions.get(sessionId) : createSession();
반영했습니다!

2019-10-01 10:09 UTC, SEOKHYOENCHOI commented on src/main/java/http/session/SessionRepository.java
> +        while (sessions.containsKey(uuid)) {
do-while 문 적용했어요!
희박할 것 같긴 하지만 중복될 가능성도 없지는 않아 중복 체크를 추가했습니다.

2019-10-01 10:09 UTC, SEOKHYOENCHOI commented on src/main/java/http/common/HttpVersion.java
> +                //.orElseThrow(HttpVersionNotFoundException::new)
넵 미처 못 봤네요ㅠㅠ
제거했습니다!

2019-10-01 11:46 UTC, SEOKHYOENCHOI commented on src/main/java/controller/LoginController.java
> +            httpResponse.addHeaderAttribute("Set-Cookie", "SessionID=" + session.getId() + "; Path=/");
Request 생성 시 Session을 만들고, 응답 시 세션 정보를 출력하며 프레임워크에서 관리하도록 수정했습니다!

2019-10-01 11:56 UTC, SEOKHYOENCHOI commented
기존 테스트 수정과 컨트롤러 테스트 추가했습니다!
또, 세션을 프레임워크에서 관리하도록 수정했고, 쿠키 구현도 스펙에 맞게 변경했어요.

궁금한 점 몇 가지 질문 드리겠습니다!
1. 기존에는 Map<Predicate, Function>에서 Predicate를 이용해 View를 찾았습니다.
그런데 페어에게 Predicate를 이용하는 것은 맵의 자료구조 형식과 맞지 않는다는 피드백이 와서
ViewResolver에서 List<ViewMatcher> 를 조회하며 View를 찾는 방식으로 바꿔봤어요.
기존과 비교해 어떤 방식이 나을까요?

2. 아직까지는 로그인 이외에는 세션에 값을 저장하는 부분이 없어 매 요청마다 만드는 것은 불필요하다고 생각하는데, 프레임워크에서 세션을 관리하기 위해 모든 요청마다 세션을 생성하고 있습니다. 새로운 모든 요청에 세션을 만들어도 괜찮을까요?

리뷰 감사합니다!

2019-10-02 08:49 UTC, hongsii approved these changes
피드백 반영 및 구조 개선이 잘 되어서 피드백 드릴게 없네요 👍 
미션 진행하느라 고생 많으셨습니다! 머지하겠습니다 :)

2019-10-02 08:49 UTC, hongsii commented on src/main/java/http/common/HttpHeader.java
> +        if (httpHeader.containsKey(key)) {
앗! 제가 잘못 생각했습니다.. ㅠㅠ 
제가 말한 메서드로는 아래와 같은 코드 밖에 작성할 수 없을 듯 하네요.
작성하고 나니 비모가 작성하신 코드가 가독성이 좋아보입니다!

```
List<String> values = httpHeader.getOrDefault(key, Lists.newArrayList());
values.add(value);
httpHeader.putIfAbsent(key, values);
```

2019-10-02 08:49 UTC, hongsii commented on src/main/java/http/response/HttpResponse.java
> +        addSessionCookie();
클라이언트가 최초 요청마다 세션을 생성하는 것도 좋은 방법이라고 생각합니다.

2019-10-02 08:49 UTC, hongsii commented on src/main/java/view/ViewResolver.java
> +        VIEW_MATCHERS.add(new RedirectViewMatcher());
`Map` 은 key를 통해 매핑된 value를 손쉽게 찾기 위한 자료구조입니다.
비모가 이전에 구현한 코드는 `Map` 의 모든 key를 순회하면서 key의 조건에 맞는 value를 찾는 방식으로 구현했습니다.
그렇기 때문에 순회하면서 일치하는 조건을 찾는 용도로는 `List`가 더 적절하지 않을까요?

2019-10-02 08:50 UTC, merged