[웹서버 - step 2] 로비 미션 제출합니다.
woowacourse/jwp-was pull request #80
Opened 2019-09-29 15:05 UTC by kangmin46

테스트 코드의 중복이 많아서 제거할 필요성이 있을 것 같습니다.

1단계와 달라진 점은 HttpResponse 의 구조가 바뀌었습니다.
빌더패턴이 가독성이 좋다고 생각해서 적용해 보았습니다!

세션의 구조를 파악하는데 도움이 된 미션인 것 같았습니다!

2019-09-30 12:55 UTC, byjo requested changes
2단계 미션 진행하면서 코드가 좀 더 깔끔하게 정리되었네요 👍 
세션과 쿠키가 유효하게 동작할 수 있도록 몇 가지 수정되면 좋을 점이 보여 피드백 드렸어요.
확인 부탁드려요.

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/controller/LoginController.java
> +    private HttpResponse sendLoginPage(HttpRequest httpRequest, String userId, String password) {
`sendLoginPage()` 메소드에서 다음의 여러 로직이 수행되고 있네요.
  1. DB에서 user 조회 
  2. user password 일치 여부 확인
  3. 2에 따른 분기 

하나의 함수에서는 하나의 일만 수행할 수 있도록 변경해보면 어떨까요?
- [클린코드 - 함수](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2003%20-%20%ED%95%A8%EC%88%98.md#%ED%95%9C-%EA%B0%80%EC%A7%80%EB%A7%8C-%ED%95%B4%EB%9D%BC)

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/controller/LoginController.java
> +            .map(user -> HttpResponse.sendRedirect(httpRequest, LOGIN_SUCCESS_INDEX, true))
redirect 요청 마다 유저 로그인 여부를 넘겨줘야 하네요.
그럼 리다이렉트를 하는 컨트롤러마다 유저 로그인 여부를 확인하는 로직이 추가 되어야 하는 걸까요?
다음의 아티클에 있는 쿠키의 동작 방식을 참고하셔서 사용자 로그인 로직을 정리하면 좋을 것 같아요.
- [쿠키와 세션 개념](https://interconnection.tistory.com/74)

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/controller/UserListController.java
> +        String[] logined = httpRequest.getHeaderFieldValue("Cookie").split("=");
현재 쿠키 값을 사용하기 위해선 
1. Request의 Header에 cookie 정보가 있다는 세부 스펙을 알아야하고
2. 이 쿠키 정보를 가져와서 파싱을 해야 하네요.

`HttpRequest` 를 통해 좀 더 쉽게 쿠키 정보를 알 수 있도록 설계해보면 어떨까요?

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/controller/request/HttpRequest.java
> +        return new HttpSession(UUIDGenerator.generateUUID());
매번 새로운 세션을 생성하면 세션 유지가 안되지 않을까요?
다음 아티클의 세션 동작 순서를 참고하셔서 세션 동작이 유효하도록 변경해보시면 좋을 것 같아요.
- [쿠키(Cookie)와 세션(Session) & 로그인 동작 방법](https://cjh5414.github.io/cookie-and-session/)

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/engine/TemplateEngine.java
> +    private Handlebars handlebars;
현재는 handlebar에 대해서만 View 지원이 가능한데요.
추상화를 통해 여러 템플릿 엔진을 사용할 수 있도록 변경하는 것도 좋은 도전 포인트일 것 같습니다! :)

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/controller/response/HttpResponse.java
> +    private static class ResponseBuilder {
👍 
빌더 패턴을 적용해보니 어떤 장점이 있으셨나요? ㅎㅎ

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/RequestHandler.java
> +            HttpResponse.badRequest(e.getMessage());
1. `Render.render()` 메소드가 호출 되어야 실제로 사용자에게 메시지가 전달 되지 않을까요?
2. 현재 모든 Exception에 대해서 badRequest 응답을 주고 있는데요. 400 에러의 경우 잘못된 클라이언트 요청에 대한 에러인데, 모든 Exception이 다 잘못된 요청에 의한 것일까요?

2019-09-30 12:55 UTC, byjo commented on src/main/java/webserver/Router.java
> +    private static final UserController USER_CONTROLLER = new UserController();
https://github.com/woowacourse/jwp-was/pull/42#discussion_r328934087 지난 PR 때 문의주신 내용 여기서 이어갈게요.

먼저 스프링이 싱글톤 레지스트리를 사용하는 것은 맞습니다. 다만, 우리가 흔히 아는 싱글톤 패턴으로 구현하지는 않았어요.
이는 싱글톤 패턴의 단점 때문인데 이를 공부하고 정리해보셔도 좋을 것 같아요.
그리고 싱글톤 레지스트리는 `@MVC/DI 프레임워크 구현` 미션을 하면서 직접 적용해보실 수 있으실거에요. 😊

2019-10-01 15:42 UTC, kangmin46 commented on src/main/java/webserver/controller/LoginController.java
> +    private HttpResponse sendLoginPage(HttpRequest httpRequest, String userId, String password) {
스트림으로 처리를 한다고 해도 한가지 일만 수행하는 원칙은 변함이 없군요 ㅎㅎ 
sendLoginPage() 메소드안에 있는 로직이 변경될 경우에 전체를 변경하는 것이라 그렇군요!
세심한 지적 감사드립니다~

2019-10-01 15:43 UTC, kangmin46 commented on src/main/java/webserver/controller/LoginController.java
> +            .map(user -> HttpResponse.sendRedirect(httpRequest, LOGIN_SUCCESS_INDEX, true))
보내드린 링크 잘 읽었습니다~!! 덕분에 쿠키와 세션에 대해서 정확하게 알고 넘어가는 계기가 된 것 같아요.
쿠키와 세션이 동작하는 원리대로 최대한 리팩토링 해보려고 노력하겠습니다~!

2019-10-01 15:44 UTC, kangmin46 commented on src/main/java/webserver/controller/UserListController.java
> +        String[] logined = httpRequest.getHeaderFieldValue("Cookie").split("=");
이번 미션을 진행하면서 HttpRequest 엔 최대한 상태값만 남기고 로직을 다른곳으로 분리해야 된다고 생각했는데, 어떤경우엔  HttpRequest 에 파싱을 한다던지 하는 로직이 들어가도 괜찮을까요? 
기준이 조금 궁금해졌어요!

2019-10-01 15:46 UTC, kangmin46 commented on src/main/java/webserver/engine/TemplateEngine.java
> +    private Handlebars handlebars;
항상 추상화 상속등을 배웠지만 언제 써먹어야 하는지 타이밍이 아직 감이 잘 안오네요 ㅠㅠ 
언제 추상화를 적용하는 것이 좋을지 아직 잘 감이 오질 않는 것 같습니다!

2019-10-01 15:46 UTC, kangmin46 commented on src/main/java/webserver/controller/response/HttpResponse.java
> +    private static class ResponseBuilder {
일단 가독성이 정말 좋아졌어요. 
저는 개인적으로 가독성이 좋은 코드가 정말 좋다고 생각했습니다.
그리고 원하는 필드들을 가져와서 필요할때 빌드해주는 것도 빌더 패턴과 잘 맞는다고 생각했습니다!

2019-10-01 15:47 UTC, kangmin46 commented on src/main/java/webserver/RequestHandler.java
> +            HttpResponse.badRequest(e.getMessage());
말씀드리신 대로 예외에 대한 처리를 RequestHandler에 다 몰아넣는 것이 아니라 조금더 세심하게 분리해보겟습니다~~

2019-10-07 09:21 UTC, byjo approved these changes
리팩토링을 통해 세션과 쿠키 로직이 잘 정리되었네요.
피드백드린 내용에 대해서도 많이 고민하고 공부해보신 것 같구요. 👏
고생 많으셨고, 다음 미션도 즐겁게 수행하시길 바랄게요!

2019-10-07 09:21 UTC, byjo commented on src/main/java/webserver/controller/request/HttpRequest.java
> +        return this.httpCookie.getFields();
> 이번 미션을 진행하면서 HttpRequest 엔 최대한 상태값만 남기고 로직을 다른곳으로 분리해야 된다고 생각했는데, 어떤경우엔 HttpRequest 에 파싱을 한다던지 하는 로직이 들어가도 괜찮을까요?
기준이 조금 궁금해졌어요!

객체가 어떠한 정보를 가지고 있을 때, 그 정보를 의미 있는 형태로 가지는 것이 중요한 것 같아요. 

예를들어, 쿠키 값이 궁금한 객체는 이 정보에 접근할 수 있는 `HttpRequest` 에게 요청하겠죠. 이 때 쿠키 값을 이전처럼 header를 통해 가져와서 파싱을 해야 알 수 있다면, `HttpRequest`는 HTTP 요청을 잘 표현하고 있는 것일까요?

이처럼 객체가 어떠한 개념을 잘 표현하기 위해서 파싱을 통해 의미있는 형태로의 변환이 필요하지 않을까요?

2019-10-07 09:21 UTC, byjo commented on src/main/java/webserver/ModelAndView.java
> +        HandleBar handleBar = new HandleBar();
> 항상 추상화 상속등을 배웠지만 언제 써먹어야 하는지 타이밍이 아직 감이 잘 안오네요 ㅠㅠ
언제 추상화를 적용하는 것이 좋을지 아직 잘 감이 오질 않는 것 같습니다!

정말 간단하게 생각하면 새로운 로직이 추가될 때 중복되는 코드가 발생하거나 분기가 생기게 된다면, 공통적인 속성을 빼내어 추상화를 할 수 있지 않을까 싶어요.
앞으로 다른 미션들을 하면서 자주 적용하게 될 것이기 때문에 곧 익숙해지실 거에요. 😊

2019-10-07 09:21 UTC, byjo commented on src/main/java/webserver/RequestHandler.java
> +            httpResponse = HttpResponse.badRequest(e.getMessage());
👍

2019-10-07 09:21 UTC, merged