[웹서버 - step2] 지노 미션 제출합니다.
woowacourse/jwp-was pull request #86
Opened 2019-09-30 09:57 UTC by hyunssooo

안녕하세요 화투! 지노입니다.

많은 고민을 하느라 pr이 많이 늦어 졌습니다. ㅠㅜ 

죄송합니다. 많이 모자라지만 잘 부탁드립니다! :)

2019-10-03 05:11 UTC, phs1116 requested changes
안녕하세요 지노! 
피드백이 늦어서 미안해요.
커밋 정리가 상당히 깔끔하네요. 
구현도 매우 잘해주셨어요. 👍 
조금 더 개선할 수 있을것 같아 몇가지 피드백 추가했는데 참고 부탁드릴게요. :)

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/ControllerContainer.java
> +            return controllers.get("file");
controller 맵에 file로 넣는것보다는 controller 맵과는 독립적으로 서빙하는게 좋을것 같네요 :)

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +        httpResponse.redirect("/");
redirect를 나타네는 statusCode가 302 Found인데요
굳이 status를 명시적으로 설정하지 않아도 redirect 메서드 내에 켑슐화하여해보면 어떨까요?
(굳이 세터를 쓰지 않아도 될 것 같아요. :))

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/FileController.java
> +            httpResponse.forward(httpRequest.getUri());
redirect랑 마찬기조로 고민해보시면 좋을 것 같아요 :)

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/LoginUserController.java
> +            httpResponse.setCookie("logined=true;path=/");
setCookie에서 쿠키의 문자열을 만들어서 전달하기보단 쿠키가 어떻게 생겼는지도 추상화하여 전달 할 수 있지 않을까요? :)
그리고  Session도 구현했는데 세션기반으로 로그인을 변경해보면 어떨까요?

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +        throw new NotSupportMethod("Not support" + httpRequest.getMethod());
AbstractController에서 이를 구현해놓으면(protected 등) 지원하지 않을때마다 굳이 예외를 적지 않아도 될 것 같아요 :)

2019-10-03 05:11 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +                httpResponse.setHttpResponseBody(new HttpResponseBody(HandlebarsHelper.apply(DataBase.findAll())));
컨트롤러에서 템플릿을 명시적으로 호출하여 세팅하는게 아니라 이에 대한 책임을 WAS에 맡겨보면 어떨까요? :)


힌트 )
controller는 Model과 View를 반환한다.
View는 어떤 식으로 화면을 노출할지를 책임진다. (Json형태로 노출하는 JsonView, 핸들파 형태로 노출하는 HandlebarView 등)
Model는 View에 전달할 데이터를 책임진다.

2019-10-10 03:29 UTC, hyunssooo commented
안녕하세요 화투!
우선 피드백 반영이 늦어진 점 죄송합니다. 
현재 구조에서 어떻게 Model과 View를 전달해줄까 고민하다. 피드백 반영이 늦어 졌습니다. 
현재의 구조에서도 Model부분을 어떻게 처리해줄까 고민하다 결국 완성을 하지 못했습니다.ㅠ
Spring의 구조를 제가 명확히 모르는 점이 가장 큰거 같아요. ㅠㅠ 
우선 리뷰 부탁 드립니다.. ㅠ

2019-10-11 17:08 UTC, phs1116 requested changes
안녕하세요 지노!
피드백 반영하시느라 정말 고생 많으셨어요. :)
구현 매우 잘하셨는데 조금 더 개선할 수 있을것 같아서
몇가지 피드백 추가했습니다.
참고 부탁드릴게요. 궁금하신 점 있으시면 언제든지 연락주세요! :)

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/controller/IndexController.java
> +        httpResponse.forward(httpRequest.getPath() + "index.html");
forward를 여기서 해주는게 조금 부자연스럽기도 하네요.
어차피 외부에 view를 리턴해주는데 view에서 해당 기능을 구현하고 받는쪽에서 처리할수도 있지 않을까요?

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/controller/LoginUserController.java
> +            e.printStackTrace();
실 운영에서의 e.printStackTrace는 안티패턴으로 간주됩니다. :)

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/controller/CreateUserController.java
> +    RedirectView doPost(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException, URISyntaxException {
AbstractController는 Object를 리턴하고, 어떤 객체는 RedirectView나 다른 View를 리턴하기도 하네요.
ModelAndView를 리턴하는것도 있고요.
ModelAndView 혹은 공통화된 인터페이스를 리턴하는게 확장상 더 적합하지 않을까요?

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/http/request/factory/HttpRequestHeaderFactory.java
> +        if (fields.containsKey("Cookie")) {
하드코딩이 아니라 상수로 관리해보면 어떨까요? 
상당히 여러곳에서 같은 문자열을 사용하고있네요. :)

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/http/response/HttpResponse.java
> +        httpResponseHeader.addField("Content-Type", contentType + ";charset=utf-8");
마찬가지로 일반적인 헤더나 쿠키 키 값들은 상수로 관리해보면 어떨까요?

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +                httpResponse.setHttpResponseBody(new HttpResponseBody(HandlebarsHelper.apply(DataBase.findAll())));
RedirectView를 구현했듯이, HandlebarView를 구현하고, 이 내부에서 핸들바를 적용하는 방법도 있을 것 같아요. :)

2019-10-11 17:08 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +        }
`이펙티브 자바 Item 65 - 예외를 무시하지마라.` 참고 부탁드릴게요. :)

2019-10-12 07:57 UTC, hyunssooo commented
안녕하세요 화투!
미션 진행이 더딘 점 , 주말에 리뷰 요청 드린 점 죄송합니다. 😿
좋은 주말 보내세요! 😊

2019-10-13 12:52 UTC, phs1116 approved these changes
안녕하세요 지노! 
피드백 반영 👍깔끔하게 잘 구현해주셨어요.
바쁜와중에도 끈기있게 과제를 다 수행하시느라 정말 고생많으셨어요.
이번 과제 머지할게요. :)
구현하시느라 수고 많으셨습니다.

2019-10-13 12:52 UTC, phs1116 commented on src/main/java/controller/UserListController.java
> +        modelAndView.setView(view);
setter를 안쓰는 방법도 가능했을 것 같네요. :)

2019-10-13 12:52 UTC, merged