[웹서버] 철시 미션 제출합니다.
woowacourse/jwp-was pull request #9
Opened 2019-09-20 08:20 UTC by pkch93

안녕하세요 써머! 다시 한번 리뷰를 부탁드리게된 철시입니다!

페어와 함께 리펙토링 전 1단계 요구사항을 구현하였습니다. 이번주가 가기 전에 현재 구현한 결과를 써머에게 피드백 받고 싶어 이렇게 리뷰요청드립니다!

많은 지적 부탁드립니다. 감사합니다!

2019-09-21 09:24 UTC, jihan805 requested changes
안녕하세요 철시, 깔끔하게 잘 구현하셨어요 💯 
간단한 피드백 남겼으니 확인 후 머지할게요 :)

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/request/HttpRequestParams.java
> +        if (queryString.equals("")) {
NPE가 발생할 수 있을 것 같아요!
어떻게 해결할 수 있을까요?

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/request/HttpRequest.java
> +
작은 단위로 HttpRequest에 필요한 클래스들을 잘 분리했어요 💯 
RequestLine에 대해 찾아보고, 작게 분리한 클래스들을 묶어주면 어떨까요?
추가로 관련 테스트코드 작성도 함께 해보면 좋을 것 같아요 

[참고링크]https://blog.outsider.ne.kr/888

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/request/HttpRequestParams.java
> +            return "";
왜 ""를 리턴하는지 의미를 나타낼 수 있도록 상수를 활용하면 어떨까요?

추가로 코드 전체적으로 상수를 사용할 수 있는 부분들이 있으면 적용해도 좋을 것 같아요!

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/response/HttpResponse.java
> +    private HttpVersion httpVersion;
HttpRequest에 남긴 피드백과 동일해요! 
해당 클래스 역시 작은 단위로 분리 👍 👍 
참고 링크의 StatusLine에 대해 찾아보면 어떨까요?

[참고링크] https://blog.outsider.ne.kr/888

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/request/HttpRequestParser.java
> +    private static HttpRequest parsePost(final BufferedReader bufferedReader, final HttpMethod method,
Post 요청시 query string이 들어오는 경우에 대한 처리는 어떻게 될까요?

2019-09-21 09:24 UTC, jihan805 commented on src/main/java/http/request/HttpRequestParser.java
> +        }
HttpMethod가 늘어날때마다 if/else 분기가 추가되어야 하지 않을까요?

2019-09-21 09:24 UTC, jihan805 commented on src/test/java/http/request/HttpRequestTypeTest.java
> +    @ValueSource(strings = {"/index.html", "/user/form.html"})
ParameterizedTest 사용 👍 
DisplayName을 이용해서 어떤 테스트인지 더 명확하게 남겨도 좋을 것 같아요 :) 

추가로, 1단계 힌트를 참고하여 테스트 코드를 조금 더 보충해보면 어떨까요?

2019-09-24 09:29 UTC, pkch93 commented on src/main/java/http/request/HttpRequestParams.java
> +        if (queryString.equals("")) {
아아 감사합니다!
queryString이 null이 들어올 수 있으니 확실한 `""`으로 equals 메서드를 호출했습니다!

2019-09-24 09:37 UTC, pkch93 commented on src/main/java/http/request/HttpRequestParser.java
> +    private static HttpRequest parsePost(final BufferedReader bufferedReader, final HttpMethod method,
https://stackoverflow.com/questions/611906/http-post-with-url-query-parameters-good-idea-or-not

위 링크를 참조하여 POST HTTP Method 요청시의 query string에 대해 학습하였습니다. POST 요청시에도 query string 값이 요청의 보조 역할을 할 수 있다는 내용이 있었습니다. 때문에 `HttpRequestParams`로 query string 값을 관리하고 `HttpRequestBody`로 Body 값을 관리하도록 설계하였습니다. 이 구조에 대한 써머의 의견이 궁금합니다 :)

2019-09-24 09:56 UTC, pkch93 commented
주신 피드백과 함께 강의 자료의 리팩토링 힌트를 참고하여 추가적으로 구현하였습니다!

한가지 여쭙고 싶은 부분이 있는데 제 코드 중 HttpRequest와 HttpResponse가 거의 DTO에 가까운 역할을 하고 있습니다. 이 객체들을 가지고 각종 로직을 처리하는 클래스들이 많은 상황이라 HttpRequest와 HttpResponse을 데이터만 관리하도록 얇게 설계한 상황인데 이 구조에 대해 써머의 생각이 궁금합니다.

2019-09-24 14:53 UTC, jihan805 approved these changes
안녕하세요~! 피드백 반영 & 구현 모두 잘하셨어요 💯 
아주 간단한 피드백 남겼으니 다음 단계 진행하기전 확인해주세요 :)
머지할게요 !

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/request/HttpRequest.java
> +
이전에 비해 HttpRequest 구조가 한결 더 깔끔해진 것 같아요 💯 

답변 :
현재 구현한 코드에서 지금과 같은 구조도 좋다고 생각해요! 👍 
또한 HttpRequest/HttpResponse내 일부 로직을 추가하여 혼용해서 사용하는 것도 괜찮다고 생각해요!
정해진 답은 없으니 다음 단계 진행하면서 같이 더 고민해보도록 해요 :)

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/request/HttpRequestParams.java
> +    private static final String QUERY_PARAM_DELIMITER = "&";
상수 👍

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/application/CreateUserController.java
> +        ContentType contentType = ContentType.of(httpRequest.getHttpHeader().get(CONTENT_TYPE));
해당 메서드에서는 사용하지 않고 있는 것 같아요!

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/application/CreateUserController.java
> +        Map<String, String> formData = bodyParser.parse(httpRequest.getHttpRequestBody());
만약 Controller가 새로 추가된다면 위의 로직은 중복 발생하지 않을까요?
HttpRequest parsing에 대한 부분을 RequestHandler의 HttpRequest httpRequest = HttpRequestParser.parse(in) 가 모두 처리할 수 있도록 위임하면 어떨까요?
현재의 구조에서 HttpRequestBody가 String  대신 Map<>을 가지도록 해도 괜찮을 것 같아요!

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/common/HttpHeader.java
> +        return 0;
상수로 사용할 수 있을 것 같아요 :)

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/response/HttpResponse.java
> +            e.printStackTrace();
logger.error !!

2019-09-24 14:53 UTC, jihan805 commented on src/main/java/http/application/ControllerMapper.java
> +public class ControllerMapper {
url에 맞는 올바른 controller를 return 하는지에 대한 테스트도 추가되면 좋을 것 같아요!

2019-09-24 14:53 UTC, jihan805 commented on src/test/java/http/request/HttpRequestTest.java
> +        assertThat(httpRequest.getRequestLine()).isEqualTo(new RequestLine(
객체 비교도 좋지만, 실제 값을 비교하는 것도 더 좋을 것 같아요!

2019-09-24 14:54 UTC, merged