[비밥] WAS 미션 1단계 미션 제출합니다.
woowacourse/jwp-was pull request #95
Opened 2020-09-09 18:47 UTC by pci2676

안녕하세요!
리뷰 잘 부탁 드리겠습니다!

정적 자원을 로드 하는 부분에서 폰트를 제대로 불러오지는 못하는데 요구사항에는 일단 html, js, css 만 불러오면 되서 폰트는 건너뛰었습니다.
폰트 부분을 추가하자니 코드가 더러워 지는 것 같아서요
더 깔끔하게 처리할 수 있는 방법이 있을까요?
힌트를 주신다면 감사하겠습니다!

2020-09-12 07:27 UTC, kang-hyungu requested changes
안녕하세요 비밥~ 리뷰어 구구입니다
HTTP 1단계 구조 잘 잡으셨네요 👍 
몇 가지 챙겨보면 좋을 부분에 코멘트 남겼어요
수정해보시고 궁금한 점 생기면 코멘트 남기거나 dm 주세요!

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/filter/FilterChain.java
> +    private int filterIndex = 0;
이 변수는 안전하게 doFilter 메서드 안의 지역변수로 만드는게 어떨까요?
웹서버처럼 동시에 여러 사용자가 접근하면 객체 멤버 변수가 공유될 수 있습니다.

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/filter/FilterChain.java
> +        if (filterIndex < filters.size()) {
이 부분이 잘 파악이 안되는데... foreach를 쓰면 되지 않을까요?
if로 값을 비교한 이유가 있을까요?

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/filter/ResourceFilter.java
> +        if (ResourceMatcher.isResource(requestPath) && httpRequest.getMethod().isGet()) {
httpRequest.getMethod().isGet()
대신
httpRequest.isGet()
로 바꾸면 httpRequest 내부 구조가 외부로 드러나는 걸 감출 수 있겠네요

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/filter/ResourceMatcher.java
> +    HTML(".html", "./templates", "text/html;charset=UTF-8"),
HttpResponse 클래스에서도 text/html;charset=UTF-8 같은 값들이 중복으로 나오고 있네요
Enum으로 관리해보면 어떨까요?

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/filter/FilterChain.java
> +        if (filterIndex < filters.size()) {
request, response 객체를 유지하면서 filters에 있는 필터를 순서대로 실행시키려는거군요
서블릿에 맞춰서 구현하려는 의도는 좋네요
구조를 좀더 파악하기 좋게 개선해보면 어떨까요?

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/servlet/UserCreateServlet.java
> +public class UserCreateServlet implements Servlet {
이 내용을 서블릿으로 구현하게 되면 DispatcherServlet를 만든 이유가 없어지지 않을까요?
2단계에서 컨트롤러로 만들어보면 좋겠네요

2020-09-12 07:27 UTC, kang-hyungu commented on src/main/java/web/HttpResponse.java
> +public class HttpResponse {
Content-Type, Content-Length 같은 HTTP 규약들은 자주 등장하는 문자열이니 enum으로 관리하면 어떨까요?
HttpStatus도 분리해볼 수 있겠네요

2020-10-15 09:33 UTC, pci2676 commented on src/main/java/web/filter/ResourceFilter.java
> +        if (ResourceMatcher.isResource(requestPath) && httpRequest.getMethod().isGet()) {
디미터 법칙을 위배하고 있었네요!
수정했습니다!

2020-10-15 09:40 UTC, pci2676 commented on src/main/java/web/filter/ResourceMatcher.java
> +    HTML(".html", "./templates", "text/html;charset=UTF-8"),
ContentsType 이라는 Enum을 만들어서 관리하도록 변경했습니다.

2020-10-15 10:05 UTC, pci2676 commented on src/main/java/web/HttpResponse.java
> +public class HttpResponse {
마찬가지로 분리했습니다!

2020-10-15 12:03 UTC, pci2676 commented on src/main/java/web/filter/FilterChain.java
> +    private int filterIndex = 0;
FilterChain 객체는 RequestScope 를 가지는 객체로 생각을 하고 설계를 했었습니다.
그래서 각 요청마다 새롭게 생성되는 객체라고 생각을 했습니다.
doFilter 로직을 실행할때 이 변수는 이전 값을 그대로 가지고 시행을 해야한다고 생각하고 만들었습니다...

2020-10-15 12:04 UTC, pci2676 commented on src/main/java/web/filter/FilterChain.java
> +        if (filterIndex < filters.size()) {
정말 많은 고민을 했는데요 ㅠㅠ
어떻게 지금 재귀를 타면서 Filter를 순회하는 로직을 변경해야할지 감이 잘 안잡히는 것 같습니다 흑흑..

2020-10-15 12:05 UTC, pci2676 commented
@kang-hyungu 
피드백 반영이 많이 늦었습니다.
정말 많은 고민을 했는데요...!
아직도 잘 모르겠는 부분이 있습니다..
리뷰감사합니다...!

2020-10-18 23:28 UTC, kang-hyungu commented on src/main/java/web/ContentType.java
> +    HTML_UTF_8("text/html;charset=utf-8"),
charset=utf-8 이 부분도 반복적으로 보이네요
중복을 제거할 방법 없을까요?

2020-10-18 23:28 UTC, kang-hyungu commented on src/main/java/web/filter/FilterChain.java
> +        if (filterIndex < filters.size()) {
재귀 구조를 없애 보라는 뜻이었어요
Filter와 FilterChain이 메서드 파라미터로 서로 돌아가며 실행되는 구조인데 이걸 한 눈에 파악하기가 어려워서 남긴 피드백이었습니다.

2020-10-18 23:34 UTC, kang-hyungu commented
코멘트 남긴 질문을 늦게 봤네요;;
폰트도 html, js, css처럼 리소스 자원 처리를 담당하는 클래스에서 처리하도록 만들어야겠죠
구현해보시고 코드가 지저분한 부분은 리팩토링 하면서 정리하는 방향으로 진행하시기 바랍니다

2020-10-18 23:42 UTC, kang-hyungu approved these changes
안녕하세요 비밥~ 오랜만이네요
피드백 반영한 내용 확인했어요
이번에 남긴 피드백은 2단계 진행하면서 같이 적용해보아요
그리고 피드백이 이해 안되거나 잘 모르는 부분은 편하게 코멘트 남기시거나 dm 주세요

2020-10-18 23:42 UTC, kang-hyungu commented on src/main/java/web/UrlParameter.java
> +            throw new IllegalArgumentException(String.format("%s : 올바르지 않은 입력입니다.", splittedParam));
splittedParam 변수가 배열이라 이렇게 하면 객체 주소가 나오지 않을까요?
잘못 입력한 텍스트가 아니라요.
splittedParam를 2개 이상 입력해주세요로 코멘트를 바꾸는게 좋겠네요

2020-10-18 23:42 UTC, merged